//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC6WeChat37MMFinderLiveTaskKaraQualityPrediction : NSObject
{
    // Error parsing type: , name: positive
    // Error parsing type: , name: currentStep
    // Error parsing type: , name: stepInterval
}

- (id)init;
@property(nonatomic) long long stepInterval; // @synthesize stepInterval;
@property(nonatomic) long long currentStep; // @synthesize currentStep;
@property(nonatomic) _Bool positive; // @synthesize positive;

@end

