//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface _TtC6WeChat31WCPayJsApiPaySesssionReportData : NSObject
{
    // Error parsing type: , name: chatType
    // Error parsing type: , name: sendType
    // Error parsing type: , name: sessionType
    // Error parsing type: , name: sessionName
    // Error parsing type: , name: timelineObjId
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) NSString *description;
- (id)initWithFinderData:(id)arg1;
- (id)initWithTopicReportItem:(id)arg1;
- (id)initWithGetUrlInfoSession:(id)arg1 msgUserName:(id)arg2;
- (id)initWithTalker:(id)arg1 sender:(id)arg2;
- (id)initWithTimelineSender:(id)arg1;
@property(nonatomic, readonly) NSString *sessionTypeValue;
@property(nonatomic, readonly) NSString *sendTypeValue;
@property(nonatomic, readonly) NSString *chatTypeValue;
@property(nonatomic, readonly) NSString *timelineObjId;
@property(nonatomic, readonly) NSString *sessionName;

@end

