//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSDate, NSString;

@protocol _TtP6WeChat29IKaraFeatureCenterSessionFlow_

@optional
- (void)userDidEnterFinderWithSession:(NSString *)arg1 identifier:(unsigned long long)arg2 at:(NSDate *)arg3;
- (void)userWillEnterFinderWithSession:(NSString *)arg1 identifier:(unsigned long long)arg2 at:(NSDate *)arg3;
@end

