//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "AssetExporterDelegate-Protocol.h"

@class CMessageWrap, MessageAssetThreshold, NSArray, NSMutableArray, NSString;
@protocol AssetSetExportControllerDelegate;

@interface AssetSetExportController : NSObject <AssetExporterDelegate>
{
    _Bool _isStopped;
    _Bool _isExportFail;
    CMessageWrap *_msgWrap;
    unsigned long long _startExportTime;
    id <AssetSetExportControllerDelegate> _delegate;
    NSArray *_arrOriginDataList;
    NSMutableArray *_arrExportTask;
    NSMutableArray *_arrExportingTask;
    NSMutableArray *_arrExportedDataField;
    MessageAssetThreshold *_assetThreshold;
}

- (void).cxx_destruct;
@property(retain, nonatomic) MessageAssetThreshold *assetThreshold; // @synthesize assetThreshold=_assetThreshold;
@property(retain, nonatomic) NSMutableArray *arrExportedDataField; // @synthesize arrExportedDataField=_arrExportedDataField;
@property(retain, nonatomic) NSMutableArray *arrExportingTask; // @synthesize arrExportingTask=_arrExportingTask;
@property(retain, nonatomic) NSMutableArray *arrExportTask; // @synthesize arrExportTask=_arrExportTask;
@property(retain, nonatomic) NSArray *arrOriginDataList; // @synthesize arrOriginDataList=_arrOriginDataList;
@property(nonatomic) _Bool isExportFail; // @synthesize isExportFail=_isExportFail;
@property(nonatomic) __weak id <AssetSetExportControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) unsigned long long startExportTime; // @synthesize startExportTime=_startExportTime;
@property(retain, nonatomic) CMessageWrap *msgWrap; // @synthesize msgWrap=_msgWrap;
@property(nonatomic) _Bool isStopped; // @synthesize isStopped=_isStopped;
- (void)onAssetExportFail:(id)arg1 reason:(int)arg2;
- (void)onAssetExportSucc:(id)arg1;
- (void)onAllAssetExported;
- (void)checkQueue;
- (void)start;
- (id)initWithMsgWrap:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

