//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImageView.h>

@interface AuthorizeCheckBox : UIImageView
{
    _Bool _selected;
    CDUnknownBlockType _selectBlock;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType selectBlock; // @synthesize selectBlock=_selectBlock;
@property(nonatomic) _Bool selected; // @synthesize selected=_selected;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)addSelectAction:(CDUnknownBlockType)arg1;
- (void)internalInit;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

