//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUserService.h"

#import "MMServiceProtocol-Protocol.h"

@class NSString;

@interface BrandTimelineSettingMgr : MMUserService <MMServiceProtocol>
{
    unsigned int _timelineSettingInfoControlBit;
}

@property(nonatomic) unsigned int timelineSettingInfoControlBit; // @synthesize timelineSettingInfoControlBit=_timelineSettingInfoControlBit;
- (void)clearAllData;
- (void)initData;
- (void)onServiceClearData;
- (void)onServiceInit;
- (void)runSetCgi:(id)arg1 complection:(CDUnknownBlockType)arg2;
- (void)setHeadForPaySwitch:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)setPersonalRecommendSwitch:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)getTimelineSetting:(CDUnknownBlockType)arg1;
- (unsigned int)getTimelineSettingInfoControlBit;
- (_Bool)shouldShowBrandTimelineSettingEntry;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

