//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class ConcertTicketInfo_WordResource, NSMutableArray, NSString;

@interface ConcertTicketInfo_ConcertResourceInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *bottomSplitLineColorValue; // @dynamic bottomSplitLineColorValue;
@property(retain, nonatomic) NSMutableArray *bottomTextColorValue; // @dynamic bottomTextColorValue;
@property(retain, nonatomic) NSMutableArray *buttonColorValue; // @dynamic buttonColorValue;
@property(nonatomic) _Bool enableBackgroundGlasses; // @dynamic enableBackgroundGlasses;
@property(retain, nonatomic) NSString *logoPictureUrl; // @dynamic logoPictureUrl;
@property(retain, nonatomic) NSString *qrCodeUrl; // @dynamic qrCodeUrl;
@property(retain, nonatomic) NSString *resourceId; // @dynamic resourceId;
@property(retain, nonatomic) NSMutableArray *shareColorValue; // @dynamic shareColorValue;
@property(retain, nonatomic) NSMutableArray *textColorValue; // @dynamic textColorValue;
@property(retain, nonatomic) NSString *ticketBgPictureUrl; // @dynamic ticketBgPictureUrl;
@property(retain, nonatomic) NSMutableArray *ticketNumberColorValue; // @dynamic ticketNumberColorValue;
@property(retain, nonatomic) NSString *ticketPictureUrl; // @dynamic ticketPictureUrl;
@property(retain, nonatomic) NSString *ticketSmallPictureUrl; // @dynamic ticketSmallPictureUrl;
@property(retain, nonatomic) NSString *title; // @dynamic title;
@property(retain, nonatomic) ConcertTicketInfo_WordResource *wordResource; // @dynamic wordResource;

@end

