//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSString;

@interface DataReportPageDataEntity : NSObject
{
    _Bool _isFullSubPage;
    unsigned long long _pageId;
    unsigned long long _bizGroupId;
    NSString *_pageName;
    NSMutableDictionary *_pageParams;
    NSMutableDictionary *_pageEventParams;
    NSMutableDictionary *_refPageParams;
    NSMutableDictionary *_sourcePageParams;
    NSMutableDictionary *_innerProperty;
    NSMutableDictionary *_reportPolicy;
    long long _pageStep;
    unsigned long long _pageInTime;
    unsigned long long _sessionInTime;
    CDUnknownBlockType _dynamicParamsBlock;
    NSMutableDictionary *_reportIntervals;
    NSMutableDictionary *_lastReportTimes;
    id _relatedModel;
    NSString *_sourceViewId;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool isFullSubPage; // @synthesize isFullSubPage=_isFullSubPage;
@property(retain, nonatomic) NSString *sourceViewId; // @synthesize sourceViewId=_sourceViewId;
@property(nonatomic) __weak id relatedModel; // @synthesize relatedModel=_relatedModel;
@property(retain, nonatomic) NSMutableDictionary *lastReportTimes; // @synthesize lastReportTimes=_lastReportTimes;
@property(retain, nonatomic) NSMutableDictionary *reportIntervals; // @synthesize reportIntervals=_reportIntervals;
@property(copy, nonatomic) CDUnknownBlockType dynamicParamsBlock; // @synthesize dynamicParamsBlock=_dynamicParamsBlock;
@property(nonatomic) unsigned long long sessionInTime; // @synthesize sessionInTime=_sessionInTime;
@property(nonatomic) unsigned long long pageInTime; // @synthesize pageInTime=_pageInTime;
@property(nonatomic) long long pageStep; // @synthesize pageStep=_pageStep;
@property(retain, nonatomic) NSMutableDictionary *reportPolicy; // @synthesize reportPolicy=_reportPolicy;
@property(retain, nonatomic) NSMutableDictionary *innerProperty; // @synthesize innerProperty=_innerProperty;
@property(retain, nonatomic) NSMutableDictionary *sourcePageParams; // @synthesize sourcePageParams=_sourcePageParams;
@property(retain, nonatomic) NSMutableDictionary *refPageParams; // @synthesize refPageParams=_refPageParams;
@property(retain, nonatomic) NSMutableDictionary *pageEventParams; // @synthesize pageEventParams=_pageEventParams;
@property(retain, nonatomic) NSMutableDictionary *pageParams; // @synthesize pageParams=_pageParams;
@property(retain, nonatomic) NSString *pageName; // @synthesize pageName=_pageName;
@property(nonatomic) unsigned long long bizGroupId; // @synthesize bizGroupId=_bizGroupId;
@property(nonatomic) unsigned long long pageId; // @synthesize pageId=_pageId;
- (id)toString;
- (void)reset;
- (id)init;

@end

