//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"
#import "PBCoding-Protocol.h"
#import "WCTTableCoding-Protocol.h"

@class NSString;

@interface DataReportNewUBACacheModel : NSObject <PBCoding, NSCopying, WCTTableCoding>
{
    unsigned long long _cacheTime;
    NSString *_reportStr;
}

+ (id)swift_reportStr;
+ (const void *)__wcdb_synthesize_1:(void *)arg1;
+ (const void *)reportStr;
+ (id)swift_cacheTime;
+ (const void *)__wcdb_synthesize_0:(void *)arg1;
+ (const void *)cacheTime;
+ (id)__wcdbtyper;
+ (id)allBridgeProperties;
+ (const void *)allProperties;
+ (const void *)objectRelationalMapping;
+ (void)initialize;
+ (void)PBArrayAdd_reportStr;
+ (void)PBArrayAdd_cacheTime;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *reportStr; // @synthesize reportStr=_reportStr;
@property(nonatomic) unsigned long long cacheTime; // @synthesize cacheTime=_cacheTime;
- (id)toString;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithTime:(unsigned long long)arg1 withStr:(id)arg2;
- (id)getPBPropertyTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(nonatomic) _Bool isAutoIncrement;
@property(nonatomic) long long lastInsertedRowID;
@property(readonly) Class superclass;

@end

