//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class DataReportSubstitutePage, NSMutableArray, NSMutableDictionary, NSString;

@interface DataReportPageContext : NSObject
{
    DataReportSubstitutePage *m_lastPage;
    DataReportSubstitutePage *m_curPage;
    NSMutableDictionary *m_subPageMaps;
    NSMutableDictionary *m_fullSubPageMap;
    unsigned long long m_pageStep;
    NSString *m_curBizId;
    NSString *m_lastBizId;
    NSString *m_lastClickViewId;
    NSString *m_lastReportEventId;
    NSMutableDictionary *m_sessionIdMap;
    NSMutableArray *m_sessionIdList;
    NSMutableDictionary *m_sessionParams;
    DataReportSubstitutePage *m_curBizPage;
    NSMutableDictionary *m_bizParams;
    NSMutableDictionary *m_nextBizParams;
    NSMutableDictionary *m_nextSessionParams;
}

- (void).cxx_destruct;
- (void)updatePageInfo:(id)arg1 eventId:(id)arg2;
- (void)clearPage:(id)arg1;
- (void)subPageOut:(id)arg1;
- (void)subPageIn:(id)arg1 time:(unsigned long long)arg2;
- (void)updatePage:(id)arg1 time:(unsigned long long)arg2;
- (void)sessionOut:(id)arg1;
- (void)sessionIn:(id)arg1 time:(unsigned long long)arg2;
- (void)bizOut:(id)arg1;
- (void)bizIn:(id)arg1 time:(unsigned long long)arg2;
- (void)viewClk:(id)arg1;
- (void)resetNextSessionParams:(id)arg1;
- (void)removeNextSessionParams:(id)arg1;
- (void)removeNextSessionParam:(id)arg1 key:(id)arg2;
- (void)setNextSessionParams:(id)arg1 params:(id)arg2 nextPageId:(unsigned long long)arg3;
- (void)setNextSessionParams:(id)arg1 params:(id)arg2;
- (void)setNextSessionParam:(id)arg1 key:(id)arg2 value:(id)arg3;
- (id)getNextSessionParams:(id)arg1;
- (void)resetNextBizParams:(id)arg1;
- (void)removeNextBizParams:(id)arg1;
- (void)removeNextBizParam:(id)arg1 key:(id)arg2;
- (void)setNextBizParams:(id)arg1 params:(id)arg2 nextBizGroupId:(unsigned long long)arg3;
- (void)setNextBizParams:(id)arg1 params:(id)arg2;
- (void)setNextBizParam:(id)arg1 key:(id)arg2 value:(id)arg3;
- (id)getNextBizParams:(id)arg1;
- (id)getCurSessionParams;
- (void)resetSessionParams:(id)arg1;
- (void)removeSessionParams:(id)arg1;
- (void)removeSessionParam:(id)arg1 key:(id)arg2;
- (void)setSessionParams:(id)arg1 params:(id)arg2;
- (void)setSessionParam:(id)arg1 key:(id)arg2 value:(id)arg3;
- (id)getSessionParams:(id)arg1;
- (id)getCurBizParams;
- (void)resetBizParams:(id)arg1;
- (void)removeBizParams:(id)arg1;
- (void)removeBizParam:(id)arg1 key:(id)arg2;
- (void)setBizParams:(id)arg1 params:(id)arg2;
- (void)setBizParam:(id)arg1 key:(id)arg2 value:(id)arg3;
- (id)getBizParams:(id)arg1;
- (id)getCustomSessionIds;
- (id)getSessionIds;
- (void)setLastReportEventId:(id)arg1;
- (id)getLastReportEventId;
- (id)getLastClickViewId;
- (id)getLastBizId;
- (id)getCurBizId;
- (void)removeSubPage:(id)arg1 parentPage:(id)arg2;
- (void)addSubPage:(id)arg1 parentPage:(id)arg2;
- (id)getSubPages:(id)arg1;
- (id)getFullSubPage:(id)arg1;
- (id)getCurPage;
- (id)getLastPage;
- (id)init;

@end

