//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "PBCoding-Protocol.h"
#import "WCTColumnCoding-Protocol.h"

@class NSString;

@interface DBContactOpenIM : NSObject <PBCoding, WCTColumnCoding>
{
    unsigned int _customInfoVisible;
    NSString *_openIMDescId;
    NSString *_customInfo;
    NSString *_finderUsername;
    unsigned long long _flags;
}

+ (unsigned long long)columnType;
+ (id)unarchiveWithWCTValue:(id)arg1;
+ (void)initialize;
+ (void)PBArrayAdd_flags;
+ (void)PBArrayAdd_finderUsername;
+ (void)PBArrayAdd_customInfoVisible;
+ (void)PBArrayAdd_openIMDescId;
+ (void)PBArrayAdd_customInfo;
- (void).cxx_destruct;
@property(nonatomic) unsigned long long flags; // @synthesize flags=_flags;
@property(retain, nonatomic) NSString *finderUsername; // @synthesize finderUsername=_finderUsername;
@property(retain, nonatomic) NSString *customInfo; // @synthesize customInfo=_customInfo;
@property(nonatomic) unsigned int customInfoVisible; // @synthesize customInfoVisible=_customInfoVisible;
@property(retain, nonatomic) NSString *openIMDescId; // @synthesize openIMDescId=_openIMDescId;
- (id)archivedWCTValue;
- (id)getPBPropertyTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

