//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

#import "NSCopying-Protocol.h"
#import "PBCoding-Protocol.h"
#import "WCTTableCoding-Protocol.h"

@class NSString;

@interface EdgeComputingCacheDataModel : MMObject <PBCoding, NSCopying, WCTTableCoding>
{
    NSString *_configID;
    unsigned long long _reportTimeEC;
    NSString *_data;
}

+ (id)swift_data;
+ (const void *)__wcdb_synthesize_2:(void *)arg1;
+ (const void *)data;
+ (id)swift_reportTimeEC;
+ (const void *)__wcdb_synthesize_1:(void *)arg1;
+ (const void *)reportTimeEC;
+ (id)swift_configID;
+ (const void *)__wcdb_synthesize_0:(void *)arg1;
+ (const void *)configID;
+ (id)__wcdbtyper;
+ (id)allBridgeProperties;
+ (const void *)allProperties;
+ (const void *)objectRelationalMapping;
+ (void)initialize;
+ (void)PBArrayAdd_data;
+ (void)PBArrayAdd_reportTimeEC;
+ (void)PBArrayAdd_configID;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *data; // @synthesize data=_data;
@property(nonatomic) unsigned long long reportTimeEC; // @synthesize reportTimeEC=_reportTimeEC;
@property(retain, nonatomic) NSString *configID; // @synthesize configID=_configID;
- (id)toString;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)getPBPropertyTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(nonatomic) _Bool isAutoIncrement;
@property(nonatomic) long long lastInsertedRowID;
@property(readonly) Class superclass;

@end

