//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class AVPlayer;
@protocol EditVideoBGMPlayerDelegate;

@interface EditVideoBGMPlayer : NSObject
{
    _Bool _muted;
    _Bool _playOnSystemMutedState;
    _Bool _allowsExternalPlayback;
    _Bool _hasReadyToPlayObserver;
    _Bool _hasStartedPlaying;
    id <EditVideoBGMPlayerDelegate> _delegate;
    AVPlayer *_player;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool hasStartedPlaying; // @synthesize hasStartedPlaying=_hasStartedPlaying;
@property(nonatomic) _Bool hasReadyToPlayObserver; // @synthesize hasReadyToPlayObserver=_hasReadyToPlayObserver;
@property(retain, nonatomic) AVPlayer *player; // @synthesize player=_player;
@property(nonatomic) _Bool allowsExternalPlayback; // @synthesize allowsExternalPlayback=_allowsExternalPlayback;
@property(nonatomic) _Bool playOnSystemMutedState; // @synthesize playOnSystemMutedState=_playOnSystemMutedState;
@property(nonatomic) _Bool muted; // @synthesize muted=_muted;
@property(nonatomic) __weak id <EditVideoBGMPlayerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)updatePlayerMuted;
- (void)downloadMusic:(id)arg1;
- (void)replayMusic;
- (void)onEditVideoBGMPlayerPlaytoEnd;
- (double)currentPlayerItemDuration;
- (_Bool)shouldBePlaying;
- (_Bool)isPlayingState;
- (_Bool)isPausedState;
- (void)seekToTime:(double)arg1;
- (void)resume;
- (void)pause;
- (id)urlOfCurrentlyPlayingInPlayer:(id)arg1;
- (id)getInnerPlayer;
- (long long)currentTimeControlStatus;
- (id)getPlayerUrl;
- (void)playMusicWithData:(id)arg1;
- (void)playMusic:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)removeCurrentItemReadyToPlayObserver;
- (void)addCurrentItemReadyToPlayObserver;
- (void)dealloc;
- (id)init;

@end

