//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMTextView.h"

@class EditImageTextBgView, UIColor, WCEditVideoColorConfig;

@interface EditImageTextView : MMTextView
{
    unsigned long long _textStyle;
    UIColor *_mainColor;
    double _scale;
    double _cornerRadius;
    EditImageTextBgView *_textBgView;
    WCEditVideoColorConfig *_colorConfig;
    struct UIEdgeInsets _minimumContentInsets;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WCEditVideoColorConfig *colorConfig; // @synthesize colorConfig=_colorConfig;
@property(retain, nonatomic) EditImageTextBgView *textBgView; // @synthesize textBgView=_textBgView;
@property(nonatomic) struct UIEdgeInsets minimumContentInsets; // @synthesize minimumContentInsets=_minimumContentInsets;
@property(nonatomic) double cornerRadius; // @synthesize cornerRadius=_cornerRadius;
@property(nonatomic) double scale; // @synthesize scale=_scale;
@property(retain, nonatomic) UIColor *mainColor; // @synthesize mainColor=_mainColor;
@property(nonatomic) unsigned long long textStyle; // @synthesize textStyle=_textStyle;
- (void)updateBackgroundRects;
- (void)textChanged:(id)arg1;
@property(nonatomic) double highlightAlpha;
- (void)drawRect:(struct CGRect)arg1;
- (_Bool)resignFirstResponder;
- (_Bool)becomeFirstResponder;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)setupEmotionColorConfig;
- (void)recenter;
- (void)layoutSubviews;

@end

