//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class CEmoticonIPSetInfo, CEmoticonPackageWrap;

@interface EmoticonManageDataObject : NSObject
{
    unsigned long long _type;
    CEmoticonPackageWrap *_pageWrap;
    CEmoticonIPSetInfo *_setInfo;
    unsigned long long _packedEmoticonCount;
    unsigned long long _objPosition;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned long long objPosition; // @synthesize objPosition=_objPosition;
@property(nonatomic) unsigned long long packedEmoticonCount; // @synthesize packedEmoticonCount=_packedEmoticonCount;
@property(retain, nonatomic) CEmoticonIPSetInfo *setInfo; // @synthesize setInfo=_setInfo;
@property(retain, nonatomic) CEmoticonPackageWrap *pageWrap; // @synthesize pageWrap=_pageWrap;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
- (id)keyForOrder;
- (id)pageWrapForMoving;

@end

