//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FavoritesModel.h"

@class NSString;

@interface FavExcerptItem : FavoritesModel
{
    NSString *_excerptKey;
    NSString *_content;
    NSString *_excerptUrl;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *excerptUrl; // @synthesize excerptUrl=_excerptUrl;
@property(retain, nonatomic) NSString *content; // @synthesize content=_content;
@property(retain, nonatomic) NSString *excerptKey; // @synthesize excerptKey=_excerptKey;

@end

