//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FavSearchExtendFilterPanel, NSString;

@protocol FavSearchExtendFilterPanelDelegate <NSObject>
- (void)onHideExtendFilterPanel;
- (void)onUpdateTag:(NSString *)arg1 to:(NSString *)arg2 fromFilter:(FavSearchExtendFilterPanel *)arg3;
- (void)onCancelTagFromExtendPanel:(NSString *)arg1;
- (void)onSelectTagFromExtendPanel:(NSString *)arg1;
- (void)onCancelTypeFromExtendPanel;
- (void)onSelectTypeFromExtendPanel:(NSString *)arg1;
@end

