//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class NSString;

@interface FinderWindowProductInfo_LimitDiscountInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;
@property(readonly, nonatomic) _Bool effective;

// Remaining properties
@property(nonatomic) unsigned int discountPrice; // @dynamic discountPrice;
@property(nonatomic) unsigned long long endTimeMs; // @dynamic endTimeMs;
@property(nonatomic) unsigned int stock; // @dynamic stock;
@property(retain, nonatomic) NSString *stockWording; // @dynamic stockWording;

@end

