//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class NSData, NSString;

@interface FinderLivePurchaseInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned int chargeFlag; // @dynamic chargeFlag;
@property(nonatomic) _Bool isPurchased; // @dynamic isPurchased;
@property(nonatomic) unsigned int needGetPaymentItems; // @dynamic needGetPaymentItems;
@property(retain, nonatomic) NSData *paymentBuff; // @dynamic paymentBuff;
@property(retain, nonatomic) NSString *promptWording; // @dynamic promptWording;
@property(nonatomic) unsigned long long purchaseHeat; // @dynamic purchaseHeat;
@property(nonatomic) unsigned int purchaseUserCount; // @dynamic purchaseUserCount;
@property(nonatomic) unsigned int unitPriceInWecoin; // @dynamic unitPriceInWecoin;

@end

