//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class FinderJumpInfo, FinderWxAppInfo, NSString;

@interface FinderEcObject : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) FinderJumpInfo *jumpInfo; // @dynamic jumpInfo;
@property(retain, nonatomic) NSString *objectHeadImg; // @dynamic objectHeadImg;
@property(retain, nonatomic) NSString *objectSubTitle; // @dynamic objectSubTitle;
@property(retain, nonatomic) NSString *objectTitle; // @dynamic objectTitle;
@property(nonatomic) unsigned int payTime; // @dynamic payTime;
@property(retain, nonatomic) NSString *shopHeadImg; // @dynamic shopHeadImg;
@property(retain, nonatomic) NSString *shopName; // @dynamic shopName;
@property(retain, nonatomic) FinderWxAppInfo *shopWxaInfo; // @dynamic shopWxaInfo;
@property(nonatomic) unsigned long long spuId; // @dynamic spuId;
@property(nonatomic) unsigned int status; // @dynamic status;
@property(retain, nonatomic) NSString *statusDesc; // @dynamic statusDesc;

@end

