//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class NSString;

@interface FinderMentionCount : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned int count; // @dynamic count;
@property(nonatomic) unsigned int fansAddCount; // @dynamic fansAddCount;
@property(nonatomic) unsigned int fansCount; // @dynamic fansCount;
@property(retain, nonatomic) NSString *finderUsername; // @dynamic finderUsername;
@property(nonatomic) unsigned int firstComment; // @dynamic firstComment;
@property(nonatomic) unsigned int firstLike; // @dynamic firstLike;
@property(nonatomic) unsigned int followCount; // @dynamic followCount;
@property(nonatomic) unsigned int lastCommentPostTime; // @dynamic lastCommentPostTime;
@property(nonatomic) unsigned int lastLikePostTime; // @dynamic lastLikePostTime;
@property(nonatomic) unsigned int lastOperation; // @dynamic lastOperation;
@property(retain, nonatomic) NSString *latestNotificationBriefing; // @dynamic latestNotificationBriefing;
@property(nonatomic) unsigned long long latestNotificationTime; // @dynamic latestNotificationTime;
@property(nonatomic) unsigned int mentionCommentCount; // @dynamic mentionCommentCount;
@property(nonatomic) unsigned int mentionLikeCount; // @dynamic mentionLikeCount;
@property(nonatomic) unsigned int mentionNotificationCount; // @dynamic mentionNotificationCount;
@property(nonatomic) unsigned int newFollowCount; // @dynamic newFollowCount;
@property(nonatomic) unsigned int normalCount; // @dynamic normalCount;
@property(nonatomic) unsigned int systemCount; // @dynamic systemCount;
@property(nonatomic) unsigned long long updatetime; // @dynamic updatetime;

@end

