//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class FinderJumpInfo_AccountStyle, FinderJumpInfo_BariableButtonStyle, FinderJumpInfo_BigBubbleStyle, FinderJumpInfo_BigButtonStyle, FinderJumpInfo_ButtonStyle, FinderJumpInfo_CardStyle, FinderJumpInfo_CombinationStyle, FinderJumpInfo_DynamicCardStyle, FinderJumpInfo_GradientCardStyle, FinderJumpInfo_HotBubbleStyle, FinderJumpInfo_LbsLifeCardStyle, FinderJumpInfo_LinkStyle, FinderJumpInfo_LiveLivingStyle, FinderJumpInfo_LiveReservationStyle, FinderJumpInfo_LoadingStyle, FinderJumpInfo_LuckyBag, FinderJumpInfo_NormalBubbleStyle, FinderJumpInfo_RelativePosition;

@interface FinderJumpInfo_Style : WXPBGeneratedMessage
{
}

+ (void)initialize;
- (double)expandDelayTimeInMS;
- (void)setExpandDelayTimeInMS:(double)arg1;
- (double)appearDelayTimeInMS;
- (void)setAppearDelayTimeInMS:(double)arg1;

// Remaining properties
@property(retain, nonatomic) FinderJumpInfo_AccountStyle *accountStyle; // @dynamic accountStyle;
@property(nonatomic) unsigned int appearAtPlayTimeMs; // @dynamic appearAtPlayTimeMs;
@property(nonatomic) unsigned int appearConditionType; // @dynamic appearConditionType;
@property(nonatomic) unsigned int appearTime; // @dynamic appearTime;
@property(retain, nonatomic) FinderJumpInfo_BariableButtonStyle *bariableButtonStyle; // @dynamic bariableButtonStyle;
@property(retain, nonatomic) FinderJumpInfo_BigBubbleStyle *bigBubble; // @dynamic bigBubble;
@property(retain, nonatomic) FinderJumpInfo_BigButtonStyle *bigButton; // @dynamic bigButton;
@property(retain, nonatomic) FinderJumpInfo_CardStyle *bigCard; // @dynamic bigCard;
@property(retain, nonatomic) FinderJumpInfo_ButtonStyle *buttonStyle; // @dynamic buttonStyle;
@property(retain, nonatomic) FinderJumpInfo_CombinationStyle *combiationStyle; // @dynamic combiationStyle;
@property(nonatomic) unsigned int disappearAtPlayTimeMs; // @dynamic disappearAtPlayTimeMs;
@property(nonatomic) unsigned int disappearFeedBottom; // @dynamic disappearFeedBottom;
@property(retain, nonatomic) FinderJumpInfo_DynamicCardStyle *dynamicCard; // @dynamic dynamicCard;
@property(nonatomic) unsigned int finishAppeared; // @dynamic finishAppeared;
@property(retain, nonatomic) FinderJumpInfo_GradientCardStyle *gradientCard; // @dynamic gradientCard;
@property(retain, nonatomic) FinderJumpInfo_HotBubbleStyle *hotBubble; // @dynamic hotBubble;
@property(retain, nonatomic) FinderJumpInfo_LbsLifeCardStyle *lbslifeCardStyle; // @dynamic lbslifeCardStyle;
@property(retain, nonatomic) FinderJumpInfo_LinkStyle *link; // @dynamic link;
@property(retain, nonatomic) FinderJumpInfo_LiveLivingStyle *liveLivingStyle; // @dynamic liveLivingStyle;
@property(retain, nonatomic) FinderJumpInfo_LiveReservationStyle *liveReservationStyle; // @dynamic liveReservationStyle;
@property(retain, nonatomic) FinderJumpInfo_LoadingStyle *loadingStyle; // @dynamic loadingStyle;
@property(retain, nonatomic) FinderJumpInfo_LuckyBag *luckyBag; // @dynamic luckyBag;
@property(retain, nonatomic) FinderJumpInfo_NormalBubbleStyle *normalButtle; // @dynamic normalButtle;
@property(retain, nonatomic) FinderJumpInfo_RelativePosition *relativePosition; // @dynamic relativePosition;
@property(nonatomic) unsigned int screen; // @dynamic screen;
@property(nonatomic) unsigned int showPosition; // @dynamic showPosition;
@property(nonatomic) unsigned int showStyle; // @dynamic showStyle;
@property(retain, nonatomic) FinderJumpInfo_CardStyle *smallCard; // @dynamic smallCard;

@end

