//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FlutterPlatformView-Protocol.h"

@class NSString, WCSearchBar;

@interface FlutterPlatformSearchBar : NSObject <FlutterPlatformView>
{
    long long _viewId;
    WCSearchBar *_searchBar;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WCSearchBar *searchBar; // @synthesize searchBar=_searchBar;
@property(nonatomic) long long viewId; // @synthesize viewId=_viewId;
- (id)view;
- (void)initSearchBarWithFrame:(struct CGRect)arg1 viewController:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1 viewIdentifier:(long long)arg2 arguments:(id)arg3 viewController:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

