//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class TopicInfo, UIButton, UIImageView, UILabel, UITapGestureRecognizer;
@protocol GCChatCellPublishBottomViewDelegate;

@interface GCChatCellPublishBottomView : UIView
{
    _Bool _isSelfMsg;
    id <GCChatCellPublishBottomViewDelegate> _delegate;
    TopicInfo *_topicInfo;
    double _leftStartX;
    UIButton *_publishBtn;
    UILabel *_leftLabel;
    UILabel *_rightLabel;
    UIImageView *_rightArrow;
    UITapGestureRecognizer *_tapGesture;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UITapGestureRecognizer *tapGesture; // @synthesize tapGesture=_tapGesture;
@property(retain, nonatomic) UIImageView *rightArrow; // @synthesize rightArrow=_rightArrow;
@property(retain, nonatomic) UILabel *rightLabel; // @synthesize rightLabel=_rightLabel;
@property(retain, nonatomic) UILabel *leftLabel; // @synthesize leftLabel=_leftLabel;
@property(retain, nonatomic) UIButton *publishBtn; // @synthesize publishBtn=_publishBtn;
@property(nonatomic) _Bool isSelfMsg; // @synthesize isSelfMsg=_isSelfMsg;
@property(nonatomic) double leftStartX; // @synthesize leftStartX=_leftStartX;
@property(retain, nonatomic) TopicInfo *topicInfo; // @synthesize topicInfo=_topicInfo;
@property(nonatomic) __weak id <GCChatCellPublishBottomViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)layoutSubviews;
- (void)loadOtherMsgUIStyle;
- (void)loadSelfMsgUIStyle;
- (void)configViewWithInfo:(id)arg1 isSelfMsg:(_Bool)arg2 leftStartX:(double)arg3;
- (void)onViewTaped;
- (void)publishAction;
- (id)initWithFrame:(struct CGRect)arg1;

@end

