//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IntelligentMediaItem.h"

@class IntelligentClassificationData, IntelligentFaceAlbumData, IntelligentOCRData;

@interface IntelligentMessageResultItem : IntelligentMediaItem
{
    IntelligentClassificationData *_classificationData;
    IntelligentOCRData *_ocrData;
    IntelligentFaceAlbumData *_faceAlbumData;
}

- (void).cxx_destruct;
@property(retain, nonatomic) IntelligentFaceAlbumData *faceAlbumData; // @synthesize faceAlbumData=_faceAlbumData;
@property(retain, nonatomic) IntelligentOCRData *ocrData; // @synthesize ocrData=_ocrData;
@property(retain, nonatomic) IntelligentClassificationData *classificationData; // @synthesize classificationData=_classificationData;

@end

