//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface JsAdapterOnlineLogger : NSObject
{
    struct mutex _mutex;
    scoped_refptr_c1332177 _onlineLogger;
    queue_7efded04 _logQueue;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedInstance;
- (id).cxx_construct;
- (void).cxx_destruct;
@property(nonatomic) scoped_refptr_c1332177 onlineLogger; // @synthesize onlineLogger=_onlineLogger;
@property(nonatomic) queue_7efded04 logQueue; // @synthesize logQueue=_logQueue;
- (void)log:(id)arg1;
- (void)consumeLog;
- (void)appendLog:(id)arg1;
- (void)updateUrl:(id)arg1;
- (id)init;

@end

