//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol TAVSourceSoftEncoderFactory;

@interface MAVExportOptionalParam : NSObject
{
    _Bool _useHevcEncode;
    _Bool _useHDREncode;
    _Bool _useSoftHEVCEncode;
    _Bool _useSoftEncNewThreadsControl;
    _Bool _useHDRToSDR;
    _Bool _keepsProcessInBackground;
    int _bitrateUp;
    int _bitrateDown;
    id <TAVSourceSoftEncoderFactory> _encoderFactory;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool keepsProcessInBackground; // @synthesize keepsProcessInBackground=_keepsProcessInBackground;
@property(retain, nonatomic) id <TAVSourceSoftEncoderFactory> encoderFactory; // @synthesize encoderFactory=_encoderFactory;
@property(nonatomic, getter=isUseHDRToSDR) _Bool useHDRToSDR; // @synthesize useHDRToSDR=_useHDRToSDR;
@property(nonatomic) int bitrateDown; // @synthesize bitrateDown=_bitrateDown;
@property(nonatomic) int bitrateUp; // @synthesize bitrateUp=_bitrateUp;
@property(nonatomic, getter=useSoftEncNewThreadsControl) _Bool useSoftEncNewThreadsControl; // @synthesize useSoftEncNewThreadsControl=_useSoftEncNewThreadsControl;
@property(nonatomic, getter=isUseSoftHEVCEncode) _Bool useSoftHEVCEncode; // @synthesize useSoftHEVCEncode=_useSoftHEVCEncode;
@property(nonatomic, getter=isUseHDREncode) _Bool useHDREncode; // @synthesize useHDREncode=_useHDREncode;
@property(nonatomic, getter=isUseHevcEncode) _Bool useHevcEncode; // @synthesize useHevcEncode=_useHevcEncode;

@end

