//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "PBCoding-Protocol.h"

@class NSString;

@interface MBFileSpaceStatusBizItem : NSObject <PBCoding>
{
    unsigned int _totalFileNum;
    unsigned int _contentModifyTime;
    unsigned int _lastScanTime;
    unsigned long long _totalFileSize;
}

+ (void)initialize;
+ (void)PBArrayAdd_lastScanTime;
+ (void)PBArrayAdd_contentModifyTime;
+ (void)PBArrayAdd_totalFileNum;
+ (void)PBArrayAdd_totalFileSize;
@property(nonatomic) unsigned int lastScanTime; // @synthesize lastScanTime=_lastScanTime;
@property(nonatomic) unsigned int contentModifyTime; // @synthesize contentModifyTime=_contentModifyTime;
@property(nonatomic) unsigned int totalFileNum; // @synthesize totalFileNum=_totalFileNum;
@property(nonatomic) unsigned long long totalFileSize; // @synthesize totalFileSize=_totalFileSize;
- (long long)compareByContentModifyTime:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, copy) NSString *description;
- (id)getPBPropertyTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

