//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MBRuntime.h"

#import "WAOpenGLScreenCanvasDelegate-Protocol.h"
#import "WAOpenGLViewDelegate-Protocol.h"
#import "WAOpenGlCaptureDelegate-Protocol.h"
#import "WCAudioModuleDelegate-Protocol.h"
#import "WXFileLoaderDelegate-Protocol.h"
#import "WXWASMLogDelegate-Protocol.h"
#import "WeMediaDelegate-Protocol.h"
#import "wxAudioFileLoaderDelegate-Protocol.h"
#import "wxAudioNativeLogDelegate-Protocol.h"
#import "wxAudioStateDelegate-Protocol.h"

@class JSContext, JSVirtualMachine, MBJSCJSBridgeImpl, NSMutableDictionary, NSMutableSet, NSString, NSThread, WAOpenGLView, WXAudioNative, WasmAdaptor, WeMediaApi;

@interface MBJSCRuntime : MBRuntime <WAOpenGLViewDelegate, WAOpenGLScreenCanvasDelegate, WAOpenGlCaptureDelegate, WXWASMLogDelegate, WeMediaDelegate, wxAudioNativeLogDelegate, wxAudioFileLoaderDelegate, WXFileLoaderDelegate, wxAudioStateDelegate, WCAudioModuleDelegate>
{
    void *bindingBizMap;
    void *onBizConnectedFunc;
    void *onBizDisconnectedFunc;
    void *bindingPsMap;
    _Bool _isBackground;
    int _subContextId;
    WAOpenGLView *_runtimeView;
    MBJSCJSBridgeImpl *_bridge;
    JSContext *_mainContext;
    void *_nativeGlobal;
    void *_mb;
    WasmAdaptor *_wasm;
    WXAudioNative *_wxAudioNative;
    WeMediaApi *_wemedia_api;
    NSThread *_thread;
    JSVirtualMachine *_jsvm;
    NSMutableDictionary *_subContexts;
    NSMutableSet *_playingAudioEngineSet;
    NSMutableDictionary *_extViewDict;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableDictionary *extViewDict; // @synthesize extViewDict=_extViewDict;
@property(retain, nonatomic) NSMutableSet *playingAudioEngineSet; // @synthesize playingAudioEngineSet=_playingAudioEngineSet;
@property(retain, nonatomic) NSMutableDictionary *subContexts; // @synthesize subContexts=_subContexts;
@property(nonatomic) int subContextId; // @synthesize subContextId=_subContextId;
@property(retain, nonatomic) JSVirtualMachine *jsvm; // @synthesize jsvm=_jsvm;
@property(nonatomic) _Bool isBackground; // @synthesize isBackground=_isBackground;
@property(retain) NSThread *thread; // @synthesize thread=_thread;
@property(retain, nonatomic) WeMediaApi *wemedia_api; // @synthesize wemedia_api=_wemedia_api;
@property(retain, nonatomic) WXAudioNative *wxAudioNative; // @synthesize wxAudioNative=_wxAudioNative;
@property(retain, nonatomic) WasmAdaptor *wasm; // @synthesize wasm=_wasm;
@property(nonatomic) void *mb; // @synthesize mb=_mb;
@property(nonatomic) void *nativeGlobal; // @synthesize nativeGlobal=_nativeGlobal;
@property(readonly, nonatomic) JSContext *mainContext; // @synthesize mainContext=_mainContext;
@property(retain, nonatomic) MBJSCJSBridgeImpl *bridge; // @synthesize bridge=_bridge;
@property(retain, nonatomic) WAOpenGLView *runtimeView; // @synthesize runtimeView=_runtimeView;
- (void)activeAudioSession;
- (id)getIdentifier;
- (_Bool)setActive:(_Bool)arg1;
- (void)sendAudioInterruptionEndEvent;
- (void)sendAudioInterruptionBeginEvent;
- (id)mixListForAudioModule:(id)arg1;
- (void)audioModuleInterruptionEnd:(id)arg1 param:(id)arg2;
- (void)audioModuleInterruptionBegin:(id)arg1 param:(id)arg2;
- (void)onWXAudioState:(int)arg1 audioId:(unsigned long long)arg2;
- (void)canPlayNowAndAutoActive:(unsigned long long)arg1 block:(CDUnknownBlockType)arg2;
- (void)setMute:(_Bool)arg1;
- (void)resumeAllPlayer;
- (void)pauseAllPlayer;
- (id)getAudioFilePath:(id)arg1;
- (void)logDebug:(id)arg1 target:(long long)arg2;
- (void)logWarning:(id)arg1 target:(long long)arg2;
- (void)logInfo:(id)arg1 target:(long long)arg2;
- (void)logError:(id)arg1 target:(long long)arg2;
- (id)weMediaGetAbsolutePath:(id)arg1;
- (void)weMediaLOG:(int)arg1 log:(const char *)arg2;
- (void)onScreenCapture:(unsigned int)arg1 data:(void *)arg2 size:(unsigned long long)arg3 width:(unsigned long long)arg4 height:(unsigned long long)arg5 bitsPerComponent:(unsigned long long)arg6 bytesPerRow:(unsigned long long)arg7 format:(int)arg8;
- (id)imageFromPixelBuffer:(struct __CVBuffer *)arg1;
- (void)onScreenCapture:(unsigned int)arg1 width:(unsigned long long)arg2 height:(unsigned long long)arg3 pixelBuffer:(struct __CVBuffer *)arg4;
- (void)setExternalViewStub:(id)arg1 forCanvasId:(unsigned int)arg2;
- (void)onScreenCanvasFrameChanged:(unsigned int)arg1 view:(id)arg2 frame:(struct CGRect)arg3;
- (void)onScreenCanvasDestroyed:(unsigned int)arg1 view:(id)arg2;
- (void)onScreenCanvasCreated:(unsigned int)arg1 view:(id)arg2;
- (struct CGRect)getFrame;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)handleJSException:(id)arg1 exception:(id)arg2;
- (void)resume;
- (void)pause;
- (id)getFileData:(id)arg1;
- (_Bool)isFileExist:(id)arg1;
- (void)injectLibs;
- (void)notifyOnLoad;
- (void)injectPublicResources;
- (void)endWithResult:(unsigned long long)arg1 result:(id)arg2;
- (void)onEventFinish:(id)arg1 param:(id)arg2;
- (void)realRunCodeInJsThread:(CDUnknownBlockType)arg1;
- (void)runCodeInJsThreadSync:(CDUnknownBlockType)arg1;
- (void)runCodeInJsThread:(CDUnknownBlockType)arg1;
- (void)evaluateScript:(id)arg1 sourceURL:(id)arg2 completionHandler:(CDUnknownBlockType)arg3 context:(id)arg4 inSubThread:(_Bool)arg5;
- (void)evaluateScript:(id)arg1 sourceURL:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)evaluateScript:(id)arg1 sourceURL:(id)arg2;
- (id)createObject:(id)arg1;
- (id)createObject;
- (void)setupBinding;
- (void)onFirstFrameRendered:(unsigned int)arg1;
- (void)setupEjecta;
- (void)runThread:(id)arg1;
- (id)createView:(struct CGRect)arg1 config:(id)arg2;
- (void)stopThread;
- (void)destroyRuntime;
- (void)dealloc;
- (id)init;
- (void)evaluateScript:(id)arg1 inSubContext:(int)arg2 sourceURL:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)destroySubContext:(int)arg1;
- (id)getSubContext:(int)arg1;
- (int)createSubContext:(id)arg1;
- (void)initVConsole;
- (void)disconnectBiz:(id)arg1;
- (void)connectBiz:(id)arg1;
- (void)onPublicServiceCreated;
- (void)onPublicServiceListenToBiz:(id)arg1;
- (void)receiveMessageFromPublicService:(id)arg1 message:(id)arg2;
- (void)onBizListenToPublicService:(id)arg1;
- (void)receiveMessageFromBiz:(id)arg1 message:(id)arg2;
- (void)postMessage:(id)arg1 toBiz:(id)arg2;
- (void)postMessage:(id)arg1 toPublicService:(id)arg2;
- (void)unbindPublicService:(id)arg1;
- (_Bool)bindPublicService:(id)arg1 serviceAlias:(id)arg2 bindingObj:(void *)arg3;
- (_Bool)injectPlugin:(id)arg1;
- (void)initPluginModule;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

