//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface MBNetWorkUtil : NSObject
{
}

+ (void)kv_27740:(id)arg1 functionName:(id)arg2 url:(id)arg3 method:(id)arg4 sentSize:(unsigned long long)arg5 receivedSize:(unsigned long long)arg6 statusCode:(unsigned int)arg7 result:(unsigned int)arg8 costTime:(unsigned long long)arg9 dstPath:(id)arg10 contentType:(id)arg11;
+ (id)stringByEscapingQueryString:(id)arg1;
+ (id)getNetworkType;
+ (unsigned int)getIntNetworkType;

@end

