//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMRootService.h"

#import "IExptServiceExt-Protocol.h"
#import "MMKernelExt-Protocol.h"
#import "MMServiceProtocol-Protocol.h"
#import "WCMemoryStatPluginDelegate-Protocol.h"

@class MMTimer, MemoryStatAutoDumpConfig, MemoryStatPluginConfig, MemoryStatReporter, NSMutableString, NSString, WCMemoryStatPlugin, WCMemoryStatRecord;

@interface MemoryStatManager : MMRootService <MMKernelExt, IExptServiceExt, WCMemoryStatPluginDelegate, MMServiceProtocol>
{
    NSString *m_rootDir;
    NSString *m_pluginConfigPath;
    NSString *m_autoDumpConfigPath;
    NSString *m_autoDumpDataPath;
    NSMutableString *m_launchLog;
    MemoryStatPluginConfig *m_pluginConfig;
    MemoryStatAutoDumpConfig *m_autoDumpConfig;
    unsigned long long m_userMode;
    MemoryStatReporter *m_reporter;
    WCMemoryStatPlugin *m_plugin;
    WCMemoryStatRecord *m_lastRecord;
    _Bool m_memoryLoggingEnabled;
    _Bool m_allocationsLoggerEnabled;
    _Bool m_leaksCheckerEnabled;
    _Bool m_mallocGuardEnabled;
    MMTimer *m_allocationsAutoDumpTimer;
    MMTimer *m_leaksAutoCheckTimer;
    long long m_lastDumpTimestamp;
}

- (void).cxx_destruct;
- (id)onMemoryStatPluginGetCustomInfo:(id)arg1;
- (void)onMemoryStatPlugin:(id)arg1 hasError:(int)arg2;
- (unsigned int)currUin;
- (id)currUsrName;
- (void)setupAutoDumpStrategyFromXLab;
- (void)setupPlguinStrategyFromXLab;
- (void)onExptItemListChange;
- (void)onAuthOK;
- (void)doIDKeyReport:(int)arg1 value:(int)arg2;
- (void)handleAppFirstBecomeActive:(id)arg1;
- (void)handleDidBecomeActiveNotification:(id)arg1;
- (void)saveAutoDumpConfig;
- (void)savePluginConfig;
- (void)loadAutoDumpConfig;
- (void)loadPluginConfig;
- (void)onLeaksAutoCheckTimerCallback:(id)arg1;
- (void)startLeaksAutoCheckTimer;
- (id)autoDumpDataFileNameWithID:(unsigned long long)arg1;
- (void)onAllocationsAutoDumpTimerCallback:(id)arg1;
- (void)startAllocationsAutoDumpTimer;
- (void)setCustomInfoWithKey:(id)arg1 value:(id)arg2;
- (void)removeUserType:(unsigned long long)arg1;
- (void)addUserType:(unsigned long long)arg1;
- (void)handleIPXXInBackground:(int)arg1;
- (void)onIPXX:(id)arg1;
- (void)onSignalCrash;
- (void)leaksCheckAndReport:(id)arg1;
- (void)allocationsDumpAndReport:(id)arg1;
- (id)customInfoForLastReport:(_Bool)arg1;
- (id)customInfoForLiveReport;
- (_Bool)uploadRecord:(id)arg1;
- (id)recordList;
- (void)uploadLastRecord;
- (_Bool)shouldEnterMemoryReport;
- (void)setMemoryStatDisable:(_Bool)arg1;
- (_Bool)isMemoryStatDisable;
- (void)setMemoryStatManualEnabled:(_Bool)arg1;
- (_Bool)isMemoryStatManualEnabled;
- (void)enableLeaksCheckerIfNeeded;
- (void)enableAllocationsLoggerIfNeeded;
- (void)startMallocGuardIfNeeded;
- (void)startMemoryLoggingIfNeeded;
- (_Bool)checkDeviceSatisfied;
- (void)startVMRegionsLoggingIfNeeded;
- (void)startPlugin;
- (void)checkAndRecord;
- (void)onServiceClearData;
- (void)onServiceInit;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

