//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseChatCellView.h"

#import "ChatBackgroundExt-Protocol.h"

@class MMUIActivityIndicatorView, MessageTipsViewModel, UIImageView, UILabel;

@interface MessageTipsCellView : BaseChatCellView <ChatBackgroundExt>
{
    MMUIActivityIndicatorView *_loadingView;
    UILabel *_tipsLabel;
    UIImageView *_bgImageView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIImageView *bgImageView; // @synthesize bgImageView=_bgImageView;
@property(retain, nonatomic) UILabel *tipsLabel; // @synthesize tipsLabel=_tipsLabel;
@property(retain, nonatomic) MMUIActivityIndicatorView *loadingView; // @synthesize loadingView=_loadingView;
- (void)onChatBackgroundChanged:(id)arg1;
- (double)maxLabelWidth;
- (id)lineViewOfWidth:(double)arg1;
- (void)layoutLoading;
- (void)layoutLineText;
- (void)onAppear;
- (void)layoutInternal;
- (_Bool)canBeReused;
- (void)setViewModel:(id)arg1;
- (void)dealloc;
- (id)initWithViewModel:(id)arg1;

// Remaining properties
@property(readonly, nonatomic) MessageTipsViewModel *viewModel;

@end

