//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

#import "PBCoding-Protocol.h"
#import "WCTTableCoding-Protocol.h"

@class NSString;

@interface MinimizeTaskExtInfo : MMObject <PBCoding, WCTTableCoding>
{
    unsigned int _generateScene;
    unsigned long long _generateType;
    unsigned long long _bizScene;
    NSString *_bizId;
    NSString *_bizSubId;
    NSString *_bizName;
    NSString *_generateContextId;
    NSString *_sceneNote;
    unsigned long long _taskCreateTime;
    unsigned long long _lastMinimizeTime;
    unsigned long long _lastMaximizeTime;
    NSString *_miniSessionId;
    NSString *_aggreSessionId;
}

+ (unsigned long long)columnType;
+ (id)unarchiveWithWCTValue:(id)arg1;
+ (void)initialize;
+ (void)PBArrayAdd_miniSessionId;
+ (void)PBArrayAdd_taskCreateTime;
+ (void)PBArrayAdd_bizName;
+ (void)PBArrayAdd_bizSubId;
+ (void)PBArrayAdd_bizId;
+ (void)PBArrayAdd_bizScene;
+ (void)PBArrayAdd_generateScene;
+ (void)PBArrayAdd_generateType;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *aggreSessionId; // @synthesize aggreSessionId=_aggreSessionId;
@property(retain, nonatomic) NSString *miniSessionId; // @synthesize miniSessionId=_miniSessionId;
@property(nonatomic) unsigned long long lastMaximizeTime; // @synthesize lastMaximizeTime=_lastMaximizeTime;
@property(nonatomic) unsigned long long lastMinimizeTime; // @synthesize lastMinimizeTime=_lastMinimizeTime;
@property(nonatomic) unsigned long long taskCreateTime; // @synthesize taskCreateTime=_taskCreateTime;
@property(retain, nonatomic) NSString *sceneNote; // @synthesize sceneNote=_sceneNote;
@property(retain, nonatomic) NSString *generateContextId; // @synthesize generateContextId=_generateContextId;
@property(retain, nonatomic) NSString *bizName; // @synthesize bizName=_bizName;
@property(retain, nonatomic) NSString *bizSubId; // @synthesize bizSubId=_bizSubId;
@property(retain, nonatomic) NSString *bizId; // @synthesize bizId=_bizId;
@property(nonatomic) unsigned long long bizScene; // @synthesize bizScene=_bizScene;
@property(nonatomic) unsigned int generateScene; // @synthesize generateScene=_generateScene;
@property(nonatomic) unsigned long long generateType; // @synthesize generateType=_generateType;
- (id)archivedWCTValue;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)getPBPropertyTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(nonatomic) _Bool isAutoIncrement;
@property(nonatomic) long long lastInsertedRowID;
@property(readonly) Class superclass;

@end

