//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;
@protocol MMConfSDKVideoHWdecDelegate;

@interface MMConfSDKVideoHWdec : NSObject
{
    int mStatus;
    int mDecErrCount;
    struct opaqueCMFormatDescription *m_videoFormatDes;
    struct OpaqueVTDecompressionSession *m_session;
    struct vector<unsigned char, std::allocator<unsigned char>> m_avcCData;
    struct OpaqueCMBlockBuffer *m_videoBlock;
    struct opaqueCMSampleBuffer *m_sampleBuffer;
    int mCodecType;
    int mFormat;
    char *mHWYUVbuffer;
    unsigned long long mHWYUVLength;
    _Bool mCallbackErrorOccured;
    int mMemberID;
    NSString *_mErrorStr;
    id <MMConfSDKVideoHWdecDelegate> _mHWDecDelegate;
}

- (id).cxx_construct;
- (void).cxx_destruct;
@property(nonatomic) __weak id <MMConfSDKVideoHWdecDelegate> mHWDecDelegate; // @synthesize mHWDecDelegate=_mHWDecDelegate;
@property(nonatomic) __weak NSString *mErrorStr; // @synthesize mErrorStr=_mErrorStr;
@property(nonatomic) _Bool mCallbackErrorOccured; // @synthesize mCallbackErrorOccured;
@property(nonatomic) int mMemberID; // @synthesize mMemberID;
- (_Bool)CanUse;
- (void)endDecode;
- (int)decode:(const char *)arg1 dataLen:(int)arg2 codecType:(int)arg3 frameType:(int)arg4 format:(int)arg5;
- (int)initDecode:(int)arg1;
- (void)releaseSampleBufferBlock;
- (int)UpdateHWDecSession;
- (void)RenderImg:(struct __CVBuffer *)arg1;
- (int)decodeOneFrame:(const char *)arg1 dataLen:(int)arg2;
- (int)createSampleBufferBlock:(const char *)arg1 dataLen:(int)arg2;
- (int)createVideoFormatDes:(int)arg1 pXPSData:(const char *)arg2 dataLen:(int)arg3;
- (id)init;
- (void)InitAllMembers;

@end

