//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class MMBaseTimeLabel, NSDate;

@interface MMCountDownLabel : UIView
{
    MMBaseTimeLabel *_baseTimeLabel;
    NSDate *_targetTime;
    CDUnknownBlockType _arriveTargetTime;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType arriveTargetTime; // @synthesize arriveTargetTime=_arriveTargetTime;
@property(retain, nonatomic) NSDate *targetTime; // @synthesize targetTime=_targetTime;
@property(readonly, nonatomic) MMBaseTimeLabel *baseTimeLabel; // @synthesize baseTimeLabel=_baseTimeLabel;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (struct CGSize)intrinsicContentSize;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)updateTime;

@end

