//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableSet;

@interface MMEmbedExcerptUtil : NSObject
{
    NSMutableSet *_exposeReportStrSet;
}

+ (void)reportWithMsg:(id)arg1 operateType:(unsigned int)arg2;
+ (id)createEmbedExcerptWebview:(id)arg1 visibleViewController:(id)arg2;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableSet *exposeReportStrSet; // @synthesize exposeReportStrSet=_exposeReportStrSet;

@end

