//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMFinderPivotLiveViewController.h"

#import "ForwardMessageLogicDelegate-Protocol.h"
#import "MMFinderLiveWinterOlympicLogicDelegate-Protocol.h"
#import "MMFinderLiveWinterOlympicOperationViewDelegate-Protocol.h"
#import "RecentForwardScrollViewDelegate-Protocol.h"

@class FinderLiveNoticeInfo, MMFinderLiveActivityTask, MMFinderLiveActivityTaskId, MMFinderLiveOlympicsReserveConfirmView, MMFinderLiveWinterOlympicOperationView, MMFinderLiveWinterOlympicView, NSString, WCUIAlertView;

@interface MMFinderLiveWinterOlympicViewController : MMFinderPivotLiveViewController <MMFinderLiveWinterOlympicLogicDelegate, MMFinderLiveWinterOlympicOperationViewDelegate, ForwardMessageLogicDelegate, RecentForwardScrollViewDelegate>
{
    _Bool _shouldForcePortrait;
    MMFinderLiveOlympicsReserveConfirmView *_reserveConfirmView;
    FinderLiveNoticeInfo *_liveNoticeInfo;
    WCUIAlertView *_currAlertView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WCUIAlertView *currAlertView; // @synthesize currAlertView=_currAlertView;
@property(retain, nonatomic) FinderLiveNoticeInfo *liveNoticeInfo; // @synthesize liveNoticeInfo=_liveNoticeInfo;
@property(retain, nonatomic) MMFinderLiveOlympicsReserveConfirmView *reserveConfirmView; // @synthesize reserveConfirmView=_reserveConfirmView;
@property(readonly, nonatomic) _Bool shouldForcePortrait; // @synthesize shouldForcePortrait=_shouldForcePortrait;
- (void)onNetworkStatusChange:(unsigned int)arg1;
- (void)onCertificateHidden;
- (void)onCertificateShowing;
- (void)onMMFinderLiveWinterOlympicOperationViewCertViewClose:(id)arg1;
- (void)onLiveWinterOlympicLogicTorchInfoUpdated:(id)arg1;
- (void)onLiveTaskLandScapeEnabledChanged:(id)arg1;
@property(readonly, nonatomic) MMFinderLiveWinterOlympicOperationView *winterOlympicOperationView;
@property(readonly, nonatomic) MMFinderLiveWinterOlympicView *winterOlympicsLiveView;
@property(readonly, nonatomic) MMFinderLiveActivityTaskId *activityTaskId;
@property(readonly, nonatomic) MMFinderLiveActivityTask *activityTask;
- (id)getPollingFetchRequestBufferModelForCmdIDUpdateBulletScreen;
- (void)showPrivateJoinBlockView;
- (void)onShowForbidLiveViewWithError:(id)arg1;
- (void)onShowErrorPage:(id)arg1;
- (void)onKickedOut;
- (void)superClose;
- (void)close;
- (id)createOperationViewWithTaskId:(id)arg1;
- (void)initLiveLogic;
- (void)onShowToastFromAppMsg:(id)arg1;
- (void)onShowAlertFromAppMsg:(id)arg1;
- (_Bool)showReserveConfirmView:(CDUnknownBlockType)arg1;
- (void)fetchReserveInfo;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

