//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MMFinderLiveFootageReplayModel, NSString;

@interface MMFinderLiveFootageReplayReporter : NSObject
{
    MMFinderLiveFootageReplayModel *_replayModel;
    unsigned long long _replayLengthInMilliseconds;
    NSString *_correlationId;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *correlationId; // @synthesize correlationId=_correlationId;
@property(nonatomic) unsigned long long replayLengthInMilliseconds; // @synthesize replayLengthInMilliseconds=_replayLengthInMilliseconds;
@property(retain, nonatomic) MMFinderLiveFootageReplayModel *replayModel; // @synthesize replayModel=_replayModel;
- (id)replaceCommaToSemicolon:(id)arg1;
- (void)reportEvent:(id)arg1 params:(id)arg2;
- (void)onFootageReplaySeekFromMediaTimeInMilliseconds:(unsigned long long)arg1 toMediaTimeInMilliseconds:(unsigned long long)arg2;
- (void)onFootageReplayPausedAtMediaTimeInMilliseconds:(unsigned long long)arg1;
- (void)onFootageReplayOrientationChangeInvokedWithTargetOrientation:(long long)arg1;
- (void)onFootageReplayLeaveWithDurationInMilliseconds:(unsigned long long)arg1;
- (void)onFootageReplayStartWithLengthInMilliseconds:(unsigned long long)arg1;
- (void)onFootageReplayEnter;
- (id)initWithFootageReplayModel:(id)arg1;

@end

