//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class MMFinderLiveTaskId, MMLiveShopShelfDragBar, MMUIButton, MMWebImageView, NSMutableArray, UIButton, UILabel, UIStackView;
@protocol MMFinderLiveShopShelfHeaderViewDelegate;

@interface MMFinderLiveShopShelfHeaderView : UIView
{
    _Bool _hasDisplayWindow;
    id <MMFinderLiveShopShelfHeaderViewDelegate> _delegate;
    UIView *_contentView;
    MMLiveShopShelfDragBar *_dragBar;
    MMUIButton *_shoppingCartBtn;
    MMUIButton *_shopAssistantBtn;
    MMUIButton *_goodsOrderBtn;
    MMUIButton *_anchorSettingBtn;
    UIButton *_displayWindowBtn;
    MMFinderLiveTaskId *_finderLiveTaskID;
    UIStackView *_displayWindowStackView;
    MMWebImageView *_brandLabelView;
    UILabel *_displayWindowTitle;
    NSMutableArray *_simpleConstraints;
    NSMutableArray *_twoLineModeConstraints;
    UIStackView *_secondLineView;
    UIView *_secondLineSeparator;
    UIStackView *_evaluateView;
    UILabel *_evaluateWordLabel;
    UILabel *_evaluateValueLabel;
    UILabel *_evaluateLevelLabel;
    UIStackView *_guaranteeView;
    MMWebImageView *_guaranteeIcon;
    UILabel *_guaranteeLabel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *guaranteeLabel; // @synthesize guaranteeLabel=_guaranteeLabel;
@property(retain, nonatomic) MMWebImageView *guaranteeIcon; // @synthesize guaranteeIcon=_guaranteeIcon;
@property(retain, nonatomic) UIStackView *guaranteeView; // @synthesize guaranteeView=_guaranteeView;
@property(retain, nonatomic) UILabel *evaluateLevelLabel; // @synthesize evaluateLevelLabel=_evaluateLevelLabel;
@property(retain, nonatomic) UILabel *evaluateValueLabel; // @synthesize evaluateValueLabel=_evaluateValueLabel;
@property(retain, nonatomic) UILabel *evaluateWordLabel; // @synthesize evaluateWordLabel=_evaluateWordLabel;
@property(retain, nonatomic) UIStackView *evaluateView; // @synthesize evaluateView=_evaluateView;
@property(retain, nonatomic) UIView *secondLineSeparator; // @synthesize secondLineSeparator=_secondLineSeparator;
@property(retain, nonatomic) UIStackView *secondLineView; // @synthesize secondLineView=_secondLineView;
@property(retain, nonatomic) NSMutableArray *twoLineModeConstraints; // @synthesize twoLineModeConstraints=_twoLineModeConstraints;
@property(retain, nonatomic) NSMutableArray *simpleConstraints; // @synthesize simpleConstraints=_simpleConstraints;
@property(retain, nonatomic) UILabel *displayWindowTitle; // @synthesize displayWindowTitle=_displayWindowTitle;
@property(retain, nonatomic) MMWebImageView *brandLabelView; // @synthesize brandLabelView=_brandLabelView;
@property(retain, nonatomic) UIStackView *displayWindowStackView; // @synthesize displayWindowStackView=_displayWindowStackView;
@property(nonatomic) _Bool hasDisplayWindow; // @synthesize hasDisplayWindow=_hasDisplayWindow;
@property(retain, nonatomic) MMFinderLiveTaskId *finderLiveTaskID; // @synthesize finderLiveTaskID=_finderLiveTaskID;
@property(retain, nonatomic) UIButton *displayWindowBtn; // @synthesize displayWindowBtn=_displayWindowBtn;
@property(retain, nonatomic) MMUIButton *anchorSettingBtn; // @synthesize anchorSettingBtn=_anchorSettingBtn;
@property(retain, nonatomic) MMUIButton *goodsOrderBtn; // @synthesize goodsOrderBtn=_goodsOrderBtn;
@property(retain, nonatomic) MMUIButton *shopAssistantBtn; // @synthesize shopAssistantBtn=_shopAssistantBtn;
@property(retain, nonatomic) MMUIButton *shoppingCartBtn; // @synthesize shoppingCartBtn=_shoppingCartBtn;
@property(retain, nonatomic) MMLiveShopShelfDragBar *dragBar; // @synthesize dragBar=_dragBar;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) __weak id <MMFinderLiveShopShelfHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)onClickShoppingCartButton:(id)arg1;
- (void)onClickShopAssistantButton:(id)arg1;
- (void)onClickGoodsOrderButton:(id)arg1;
- (void)onClickAnchorSettingBtn:(id)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)handleContentGestureEnd;
- (void)handleContentGestureChangeTo:(double)arg1;
- (void)updateUI;
- (void)initView;
- (void)updateAnchorSettingButtonImage;
- (void)setAnchorSettingButtonEnabled:(_Bool)arg1;
- (void)checkRightButtons;
- (_Bool)shouldInitRightButtons;
- (void)layoutSubviews;
- (id)finderLiveTask;
- (id)initWithTaskID:(id)arg1;

@end

