//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMPageSheetBaseView.h"

#import "MMFinderLiveNoticeDetailsViewControllerDelegate-Protocol.h"
#import "MMFinderLiveNoticePromoteListTableViewCellDelegate-Protocol.h"
#import "MMRefreshTableFooterDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class MMRefreshTableFooterView, MMUIActivityIndicatorView, NSMutableArray, NSMutableDictionary, NSMutableSet, NSString, UITableView, WCFinderContact;
@protocol MMFinderLiveNoticePromoteListPanelDelegate;

@interface MMFinderLiveNoticePromoteListPanel : MMPageSheetBaseView <MMFinderLiveNoticeDetailsViewControllerDelegate, UITableViewDataSource, UITableViewDelegate, MMFinderLiveNoticePromoteListTableViewCellDelegate, MMRefreshTableFooterDelegate>
{
    _Bool _hasMoreNotices;
    unsigned int _totalNoticeCount;
    id <MMFinderLiveNoticePromoteListPanelDelegate> _delegate;
    WCFinderContact *_anchorContact;
    NSMutableSet *_addedNoticeIds;
    NSMutableArray *_noticeInfoList;
    NSMutableDictionary *_noticeToIndexDict;
    double _estimatedRowHeight;
    MMUIActivityIndicatorView *_loadingIndicator;
    UITableView *_noticeTableView;
    MMRefreshTableFooterView *_refreshFooterView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) MMRefreshTableFooterView *refreshFooterView; // @synthesize refreshFooterView=_refreshFooterView;
@property(retain, nonatomic) UITableView *noticeTableView; // @synthesize noticeTableView=_noticeTableView;
@property(retain, nonatomic) MMUIActivityIndicatorView *loadingIndicator; // @synthesize loadingIndicator=_loadingIndicator;
@property(nonatomic) double estimatedRowHeight; // @synthesize estimatedRowHeight=_estimatedRowHeight;
@property(nonatomic) _Bool hasMoreNotices; // @synthesize hasMoreNotices=_hasMoreNotices;
@property(nonatomic) unsigned int totalNoticeCount; // @synthesize totalNoticeCount=_totalNoticeCount;
@property(retain, nonatomic) NSMutableDictionary *noticeToIndexDict; // @synthesize noticeToIndexDict=_noticeToIndexDict;
@property(retain, nonatomic) NSMutableArray *noticeInfoList; // @synthesize noticeInfoList=_noticeInfoList;
@property(retain, nonatomic) NSMutableSet *addedNoticeIds; // @synthesize addedNoticeIds=_addedNoticeIds;
@property(retain, nonatomic) WCFinderContact *anchorContact; // @synthesize anchorContact=_anchorContact;
@property(nonatomic) __weak id <MMFinderLiveNoticePromoteListPanelDelegate> delegate; // @synthesize delegate=_delegate;
- (void)rebuildNoticeToIndexDictFromIndex:(unsigned long long)arg1;
- (void)reloadRowWithNoticeId:(id)arg1;
- (id)indexPathOfRowWithNoticeId:(id)arg1;
- (id)appendNoticeInfoItems:(id)arg1;
- (void)fetchData;
- (id)getCurrentRightButton;
- (id)getCurrentLeftButton;
- (void)updatePageSheetTitle;
- (void)setupPageSheetConfig;
- (void)MMRefreshTableFooterDidTriggerRefresh:(id)arg1;
- (void)onAddButtonTappedForCell:(id)arg1 liveNotice:(id)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (double)tableView:(id)arg1 estimatedHeightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)noticeQRCodePreviewViewControllerDidRevokeNotice:(id)arg1;
- (void)rightButtonAction;
- (void)leftButtonAction;
- (void)pageSheetWillAppear;
- (void)layoutSubviews;
- (void)removeAddedNoticeId:(id)arg1;
- (void)addAddedNoticeId:(id)arg1;
- (id)initWithAddedNoticeIds:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

