//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface MMFinderLiveImagePickerParams : NSObject
{
    _Bool _showPreviewButton;
    unsigned long long _pickerScene;
    struct CGSize _cropImageRatio;
}

@property(nonatomic) _Bool showPreviewButton; // @synthesize showPreviewButton=_showPreviewButton;
@property(nonatomic) struct CGSize cropImageRatio; // @synthesize cropImageRatio=_cropImageRatio;
@property(nonatomic) unsigned long long pickerScene; // @synthesize pickerScene=_pickerScene;

@end

