//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMFinderLiveNotifyStyleCommentPubbleCell.h"

@class CAGradientLayer, CALayer, MMFinderLiveFansGroupSignView, MMFinderLiveGlobalRankSignView, MMUIImageView, MMUILabel, MMUIView, UIView;

@interface MMFinderLiveNotifyStyleCommentPubbleSingleHeadViewCell : MMFinderLiveNotifyStyleCommentPubbleCell
{
    _Bool _canLayout;
    unsigned int _lastRank;
    unsigned int _lastMsgSubtype;
    MMUIView *_colorBackView;
    CAGradientLayer *_gradientLayer;
    CALayer *_colorLayer;
    MMUILabel *_invisiableSignLabel;
    MMUIView *_invisiableSignView;
    MMUILabel *_signLabel;
    MMUIView *_signBackView;
    MMFinderLiveGlobalRankSignView *_globalRankSignView;
    MMFinderLiveFansGroupSignView *_fansGroupSignView;
    MMUILabel *_glorySignLabel;
    MMUIImageView *_glorySignView;
    UIView *_shineAnimationView;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool canLayout; // @synthesize canLayout=_canLayout;
@property(retain, nonatomic) UIView *shineAnimationView; // @synthesize shineAnimationView=_shineAnimationView;
@property(nonatomic) unsigned int lastMsgSubtype; // @synthesize lastMsgSubtype=_lastMsgSubtype;
@property(nonatomic) unsigned int lastRank; // @synthesize lastRank=_lastRank;
@property(retain, nonatomic) MMUIImageView *glorySignView; // @synthesize glorySignView=_glorySignView;
@property(retain, nonatomic) MMUILabel *glorySignLabel; // @synthesize glorySignLabel=_glorySignLabel;
@property(retain, nonatomic) MMFinderLiveFansGroupSignView *fansGroupSignView; // @synthesize fansGroupSignView=_fansGroupSignView;
@property(retain, nonatomic) MMFinderLiveGlobalRankSignView *globalRankSignView; // @synthesize globalRankSignView=_globalRankSignView;
@property(retain, nonatomic) MMUIView *signBackView; // @synthesize signBackView=_signBackView;
@property(retain, nonatomic) MMUILabel *signLabel; // @synthesize signLabel=_signLabel;
@property(retain, nonatomic) MMUIView *invisiableSignView; // @synthesize invisiableSignView=_invisiableSignView;
@property(retain, nonatomic) MMUILabel *invisiableSignLabel; // @synthesize invisiableSignLabel=_invisiableSignLabel;
@property(retain, nonatomic) CALayer *colorLayer; // @synthesize colorLayer=_colorLayer;
@property(retain, nonatomic) CAGradientLayer *gradientLayer; // @synthesize gradientLayer=_gradientLayer;
@property(retain, nonatomic) MMUIView *colorBackView; // @synthesize colorBackView=_colorBackView;
- (id)getSelfAccessibility;
- (void)stopGlobalRankShineAnimation;
- (void)doShineAnimation;
- (void)doScaleAnimationWithCompletion:(CDUnknownBlockType)arg1;
- (_Bool)shouldRunCustomAnimation;
- (void)startGlobalRankAnimationIfNeeded;
- (void)runCustomExitAnimationWithCompletion:(CDUnknownBlockType)arg1;
- (void)runCustomEnterAnimation;
- (void)createColorBackView;
- (void)createColorLayer;
- (void)createGradientLayer;
- (void)updateBackgroundLayers;
- (void)setupBackgroundColor:(id)arg1 colorLayerBackgroundColor:(id)arg2 gradientFromColor:(id)arg3 toColor:(id)arg4 textColor:(id)arg5;
- (void)clearBackgroundLayers;
- (id)finderLiveTask;
- (void)updateCommentLabelOrigin;
- (void)updateNickLabelOrigin;
- (void)updateGlorySignLabelOrigin;
- (void)updateFansGroupSignViewOrigin;
- (void)updateGlobalSignLabelOrigin;
- (void)updateSignLabelOrigin;
- (void)updateInvisibleSignLabelOrigin;
- (void)layoutNickLabel;
- (void)layoutCommentLabel;
- (id)getGloryBG;
- (void)layoutGlorySignView;
- (void)layoutFansGroupSignView;
- (void)layoutGlobalRankSignView;
- (void)layoutSignLabel;
- (void)layoutInvisiableSignLabel;
- (id)signText;
- (_Bool)isUITypeValid;
- (void)layoutUI;
- (void)layoutSubviews;
- (void)updateBackGroundColor;
- (id)initWithCellFrame:(id)arg1;

@end

