//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface MMFinderLiveVoteDurationPickerViewConfig : NSObject
{
    unsigned long long _minDuration;
    unsigned long long _maxDuration;
    unsigned long long _currentDuration;
}

@property(nonatomic) unsigned long long currentDuration; // @synthesize currentDuration=_currentDuration;
@property(nonatomic) unsigned long long maxDuration; // @synthesize maxDuration=_maxDuration;
@property(nonatomic) unsigned long long minDuration; // @synthesize minDuration=_minDuration;

@end

