//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MMFinderLiveSensitiveDataItem;

@interface MMFinderLiveSensitiveActionItem : NSObject
{
    unsigned long long _actionType;
    MMFinderLiveSensitiveDataItem *_sensitiveItem;
    unsigned long long _actionId;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned long long actionId; // @synthesize actionId=_actionId;
@property(retain, nonatomic) MMFinderLiveSensitiveDataItem *sensitiveItem; // @synthesize sensitiveItem=_sensitiveItem;
@property(nonatomic) unsigned long long actionType; // @synthesize actionType=_actionType;
- (id)description;

@end

