//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface MMFinderLiveGestureHandDetectionSeiModel : NSObject
{
    NSString *_u;
    double _a;
    NSArray *_ga;
    NSString *_gs;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *gs; // @synthesize gs=_gs;
@property(retain, nonatomic) NSArray *ga; // @synthesize ga=_ga;
@property(nonatomic) double a; // @synthesize a=_a;
@property(retain, nonatomic) NSString *u; // @synthesize u=_u;

@end

