//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface MMFinderLivePromoteManageReportData : NSObject
{
    int _advertisementType;
    NSString *_businessId;
}

- (void).cxx_destruct;
@property(nonatomic) int advertisementType; // @synthesize advertisementType=_advertisementType;
@property(retain, nonatomic) NSString *businessId; // @synthesize businessId=_businessId;

@end

