//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MMFinderLiveSongItem, NSArray, NSIndexPath;

@protocol MMFinderLiveSongSettingOperationTableDataDelegate <NSObject>
- (void)onSongSettingTableDataSelectAllStateChanged:(_Bool)arg1;
- (void)onSongSettingTableAllDataCountChanged:(unsigned long long)arg1;
- (void)synchronizeModifiedSongItemArray:(NSArray *)arg1;
- (void)onSongSettingTableDataDeleteDataItemList:(NSArray *)arg1;
- (void)onSongSettingTableDataDeleteDidSelectInEditingMode:(_Bool)arg1;
- (void)onSongSettingTableDataDidChangeSing:(MMFinderLiveSongItem *)arg1;
- (void)onSongSettingTableDataDidFinishSing:(MMFinderLiveSongItem *)arg1;
- (void)onSongSettingTableDataDidSelect:(MMFinderLiveSongItem *)arg1 isInEditing:(_Bool)arg2;
- (void)onSongSettingTableDataDeleteDateItem:(MMFinderLiveSongItem *)arg1 atIndexPath:(NSIndexPath *)arg2;
- (void)onSongSettingTableDidScroll;
- (void)onSongSettingTableDataEndEdit:(_Bool)arg1;
- (void)onSongSettingTableDataBeginEdit;
- (void)onSongSettingTableDataCleared;
- (void)onSongSettingTableDataLoaded;
@end

