//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface MMFinderLiveGestureHandDetectionLuaMessageModel : NSObject
{
    long long _id;
    NSArray *_actived;
    NSArray *_transX;
    NSArray *_transY;
    NSArray *_rotation;
    NSArray *_scale;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *scale; // @synthesize scale=_scale;
@property(retain, nonatomic) NSArray *rotation; // @synthesize rotation=_rotation;
@property(retain, nonatomic) NSArray *transY; // @synthesize transY=_transY;
@property(retain, nonatomic) NSArray *transX; // @synthesize transX=_transX;
@property(retain, nonatomic) NSArray *actived; // @synthesize actived=_actived;
@property(nonatomic) long long id; // @synthesize id=_id;

@end

