//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MMFinderLiveLotteryInfo, MMFinderLiveMilestoneLotteryInfo;

@interface MMFinderLiveRecordListLotteryInfo : NSObject
{
    unsigned int _type;
    MMFinderLiveMilestoneLotteryInfo *_milestoneLotteryInfo;
    MMFinderLiveLotteryInfo *_lotteryInfo;
}

- (void).cxx_destruct;
@property(retain, nonatomic) MMFinderLiveLotteryInfo *lotteryInfo; // @synthesize lotteryInfo=_lotteryInfo;
@property(retain, nonatomic) MMFinderLiveMilestoneLotteryInfo *milestoneLotteryInfo; // @synthesize milestoneLotteryInfo=_milestoneLotteryInfo;
@property(nonatomic) unsigned int type; // @synthesize type=_type;
- (id)initWithLotteryInfo:(id)arg1;

@end

