//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface MMFinderLiveBaseCardView : UIView
{
    UIView *_shadowView;
    UIView *_closeButton;
    UIView *_cardView;
    UIView *_contentView;
    CDUnknownBlockType _closeBlock;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType closeBlock; // @synthesize closeBlock=_closeBlock;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) UIView *cardView; // @synthesize cardView=_cardView;
@property(retain, nonatomic) UIView *closeButton; // @synthesize closeButton=_closeButton;
@property(retain, nonatomic) UIView *shadowView; // @synthesize shadowView=_shadowView;
- (void)hide:(CDUnknownBlockType)arg1;
- (void)showIn:(id)arg1;
- (void)createConstraints;
- (void)initSubViews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

