//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class EditImageAttr, EditVideoAttr, MMAsset, MMAssetInfo, MMAssetPickerController, MMAssetPickerControllerState, MMAssetPickerInterceptor, MMImagePickerController, MMImagePreviewBrowserController, MMImagePreviewControllerActionFlow, NSArray, NSDictionary, NSError, NSString, SightDraft, UINavigationController, UIViewController, WCFinderPostSessionModel;

@protocol MMImagePickerControllerDelegate <NSObject>

@optional
- (void)onImagePickerControllerEndExportingWithAssetId:(NSString *)arg1 error:(NSError *)arg2;
- (void)onImagePickerControllerStartExportingWithAssetId:(NSString *)arg1;
- (void)onImagePickerControllerDidDisappear;
- (void)onImagePickerControllerDidAppear;
- (void)onImagePickerControllerDidTakeMedia;
- (void)onImagePickerControllerDidCancelSightCamera;
- (void)onImagePickerControllerCancelPreview;
- (void)onImagePickerControllerStartPreview;
- (void)onImagePickerControllerCancelEditing;
- (void)onImagePickerControllerStartEditing;
- (void)onImagePickerControllerOpenFinderCamera:(UIViewController *)arg1;
- (void)onImagePickerControllerOpenCamera;
- (MMImagePreviewControllerActionFlow *)onImagePreviewBrowserController:(MMImagePreviewBrowserController *)arg1 didCreateVideoCompositionActionFlow:(MMImagePreviewControllerActionFlow *)arg2;
- (MMAssetPickerInterceptor *)assetPickerController:(MMAssetPickerController *)arg1 didEditVideoAsset:(MMAsset *)arg2 byEditAttr:(EditVideoAttr *)arg3 withCurrentState:(MMAssetPickerControllerState *)arg4;
- (MMAssetPickerInterceptor *)assetPickerController:(MMAssetPickerController *)arg1 willEditVideoAsset:(MMAssetInfo *)arg2 withCurrentState:(MMAssetPickerControllerState *)arg3;
- (MMAssetPickerInterceptor *)assetPickerController:(MMAssetPickerController *)arg1 didDeselectAsset:(MMAssetInfo *)arg2 withCurrentState:(MMAssetPickerControllerState *)arg3;
- (MMAssetPickerInterceptor *)assetPickerController:(MMAssetPickerController *)arg1 willDeselectAsset:(MMAssetInfo *)arg2 withCurrentState:(MMAssetPickerControllerState *)arg3;
- (MMAssetPickerInterceptor *)assetPickerController:(MMAssetPickerController *)arg1 didSelectAsset:(MMAssetInfo *)arg2 withCurrentState:(MMAssetPickerControllerState *)arg3;
- (MMAssetPickerInterceptor *)assetPickerController:(MMAssetPickerController *)arg1 willSelectAsset:(MMAssetInfo *)arg2 withCurrentState:(MMAssetPickerControllerState *)arg3;
- (MMAssetPickerInterceptor *)assetPickerController:(MMAssetPickerController *)arg1 didLoadPreviewForAsset:(MMAssetInfo *)arg2 withCurrentState:(MMAssetPickerControllerState *)arg3;
- (MMAssetPickerInterceptor *)assetPickerController:(MMAssetPickerController *)arg1 willLoadPreviewForAsset:(MMAssetInfo *)arg2 withCurrentState:(MMAssetPickerControllerState *)arg3;
- (MMAssetPickerInterceptor *)assetPickerController:(MMAssetPickerController *)arg1 didChangeUserActionCheckTo:(_Bool)arg2 withCurrentState:(MMAssetPickerControllerState *)arg3;
- (MMAssetPickerInterceptor *)assetPickerController:(MMAssetPickerController *)arg1 willChangeUserActionCheckTo:(_Bool)arg2 withCurrentState:(MMAssetPickerControllerState *)arg3;
- (MMAssetPickerInterceptor *)assetPickerController:(MMAssetPickerController *)arg1 willFinishPickingAssets:(NSArray *)arg2 withCurrentState:(MMAssetPickerControllerState *)arg3;
- (void)onImagePickerControllerClickFooterViewButton;
- (void)onImagePickerControllerClickPostFinderLongVideoWithPostSession:(WCFinderPostSessionModel *)arg1;
- (void)MMImagePickerController:(MMImagePickerController *)arg1 didFinishPickingImageWithEditImageAttr:(EditImageAttr *)arg2;
- (void)MMVideoPickerController:(UINavigationController *)arg1 didFinishPickingVideoWithAsset:(MMAsset *)arg2;
- (void)MMVideoPickerController:(UINavigationController *)arg1 didFinishPickingSightWithInfo:(SightDraft *)arg2;
- (void)MMVideoPickerController:(UINavigationController *)arg1 didFinishPickingMediaWithInfo:(NSDictionary *)arg2;
- (void)MMImagePickerControllerDidSkip:(MMImagePickerController *)arg1;
- (void)MMImagePickerControllerDidPopOrDismiss:(MMImagePickerController *)arg1;
- (void)MMImagePickerControllerDidCancel:(MMImagePickerController *)arg1;
- (void)MMImagePickerManager:(UINavigationController *)arg1 didFinishPickingAssetWithPostSession:(WCFinderPostSessionModel *)arg2;
- (void)MMImagePickerController:(MMImagePickerController *)arg1 didFailToPickAssets:(NSArray *)arg2;
- (void)MMImagePickerController:(MMImagePickerController *)arg1 didFinishPickingMediaWithInfo:(NSArray *)arg2;
@end

