//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class MMIotDeviceExtInfo, NSMutableArray, NSString;

@interface MMIotDeviceInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSString *deviceId; // @dynamic deviceId;
@property(nonatomic) unsigned int deviceType; // @dynamic deviceType;
@property(retain, nonatomic) MMIotDeviceExtInfo *extInfo; // @dynamic extInfo;
@property(retain, nonatomic) NSString *iconUrl; // @dynamic iconUrl;
@property(retain, nonatomic) NSString *nickName; // @dynamic nickName;
@property(retain, nonatomic) NSMutableArray *supportMsgtypeList; // @dynamic supportMsgtypeList;

@end

