//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MMITransmitKvData, MMKRect, MMVoidBinaryI32Callback, MMVoidBoolCallback, MMVoidCallback, MMVoidStringCallback, MMVoidStringStringCallback, NSString;

@protocol MMKHKFingerPrintService <NSObject>
- (void)authenticateImpl:(NSString *)arg1 challenge:(NSString *)arg2 extra:(MMITransmitKvData *)arg3 success:(MMVoidBinaryI32Callback *)arg4 fail:(MMVoidCallback *)arg5 change2Pwd:(MMVoidBoolCallback *)arg6 showErrThenChange2Pwd:(MMVoidStringCallback *)arg7;
- (void)showFaceIdAuthDialogImpl:(NSString *)arg1 success:(MMVoidBinaryI32Callback *)arg2 fail:(MMVoidCallback *)arg3 cancel:(MMVoidCallback *)arg4;
- (MMKRect *)getFingerPosition;
- (long long)getFingerType;
- (void)showBioAuthViewImpl:(NSString *)arg1 challenge:(NSString *)arg2 successEvent:(MMVoidStringStringCallback *)arg3 failEvent:(MMVoidCallback *)arg4 cancelEvent:(MMVoidCallback *)arg5 forgetPwdEvent:(MMVoidCallback *)arg6;
- (void)releaseService;
- (long long)supportBioType;
@end

