//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FinderLiveBoxId, MMLiveCommentDataItem, MMLiveTaskId;

@protocol MMLiveCommentDataExt <NSObject>

@optional
- (void)onMMLiveCommentDataItemLikeInfoUpdate:(MMLiveCommentDataItem *)arg1 forTaskId:(MMLiveTaskId *)arg2 boxId:(FinderLiveBoxId *)arg3;
- (void)onMMLiveCommentDataLoadedForTaskId:(MMLiveTaskId *)arg1 boxId:(FinderLiveBoxId *)arg2;
- (void)onMMLiveCommentDataResetForTaskId:(MMLiveTaskId *)arg1 boxId:(FinderLiveBoxId *)arg2;
- (void)onSelfMMLiveCommentDataCompleted:(MMLiveCommentDataItem *)arg1 forTaskId:(MMLiveTaskId *)arg2;
- (void)onMMLiveCommentDataDeleted:(long long)arg1 forTaskId:(MMLiveTaskId *)arg2;
- (void)onMMLiveCommentDataUpdateForTaskId:(MMLiveTaskId *)arg1 boxId:(FinderLiveBoxId *)arg2 isHistoryComment:(_Bool)arg3;
@end

