//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class LiveSdkChannelParamsDesc, MMLiveCDNPlayerItem, NSMutableArray, NSMutableDictionary;

@interface MMLiveMultiAngleChannelInfo : NSObject
{
    unsigned int _retryCount;
    unsigned long long _itemIndex;
    MMLiveCDNPlayerItem *_cdnPlayerItem;
    LiveSdkChannelParamsDesc *_channelParamsDesc;
    NSMutableDictionary *_cdnPlayUrlDict;
    NSMutableArray *_cdnPlayClarityArray;
    NSMutableDictionary *_cdnPlayLevelDict;
    struct CGSize _videoSize;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableDictionary *cdnPlayLevelDict; // @synthesize cdnPlayLevelDict=_cdnPlayLevelDict;
@property(retain, nonatomic) NSMutableArray *cdnPlayClarityArray; // @synthesize cdnPlayClarityArray=_cdnPlayClarityArray;
@property(nonatomic) struct CGSize videoSize; // @synthesize videoSize=_videoSize;
@property(nonatomic) unsigned int retryCount; // @synthesize retryCount=_retryCount;
@property(retain, nonatomic) NSMutableDictionary *cdnPlayUrlDict; // @synthesize cdnPlayUrlDict=_cdnPlayUrlDict;
@property(retain, nonatomic) LiveSdkChannelParamsDesc *channelParamsDesc; // @synthesize channelParamsDesc=_channelParamsDesc;
@property(retain, nonatomic) MMLiveCDNPlayerItem *cdnPlayerItem; // @synthesize cdnPlayerItem=_cdnPlayerItem;
@property(nonatomic) unsigned long long itemIndex; // @synthesize itemIndex=_itemIndex;
- (void)updateVideoSizeFromChannelParamsDesc;
- (void)updateVideoSizeFromPlayerEvent:(struct CGSize)arg1;
@property(readonly, nonatomic) _Bool supportScreenRotate;
- (id)getCurrentDefaultCdnTransInfo:(unsigned int)arg1;
- (_Bool)isClarityArrayContains:(id)arg1 cdnPlayClarityArray:(id)arg2;
- (void)updateCdnPlayClarityArray;
- (id)getCdnUrlOfMixing:(unsigned int)arg1 isTryViewLive:(_Bool)arg2;
- (void)cdnPlayUrlRemoveObjectWithKey:(long long)arg1;
- (void)cdnPlayUrlAddObjectWithKey:(long long)arg1 value:(id)arg2;
- (void)updateCdnPlayUrlDict;
- (void)cleanData;

@end

