//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class MMLiveCameraOperationItem, MMUIButton, MMUILabel, UIView;

@interface MMLiveCameraOperationItemCell : UICollectionViewCell
{
    CDUnknownBlockType _onTapped;
    MMUIButton *_button;
    MMLiveCameraOperationItem *_operationItem;
    MMUILabel *_label;
    MMUILabel *_secondaryLabel;
    UIView *_badgeView;
    MMUILabel *_badgeLabel;
}

+ (id)reuseId;
- (void).cxx_destruct;
@property(retain, nonatomic) MMUILabel *badgeLabel; // @synthesize badgeLabel=_badgeLabel;
@property(retain, nonatomic) UIView *badgeView; // @synthesize badgeView=_badgeView;
@property(retain, nonatomic) MMUILabel *secondaryLabel; // @synthesize secondaryLabel=_secondaryLabel;
@property(retain, nonatomic) MMUILabel *label; // @synthesize label=_label;
@property(retain, nonatomic) MMLiveCameraOperationItem *operationItem; // @synthesize operationItem=_operationItem;
@property(retain, nonatomic) MMUIButton *button; // @synthesize button=_button;
@property(copy, nonatomic) CDUnknownBlockType onTapped; // @synthesize onTapped=_onTapped;
- (void)onButtonTapped;
- (void)layoutSubviews;
- (void)updateWithItem:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

