//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, UIImage;

@interface MMLiveCameraOperationItem : NSObject
{
    _Bool _disabled;
    UIImage *_image;
    NSString *_label;
    NSString *_secondaryLabel;
    NSString *_badgeText;
    CDUnknownBlockType _action;
    NSString *_redDotPath;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *redDotPath; // @synthesize redDotPath=_redDotPath;
@property(copy, nonatomic) CDUnknownBlockType action; // @synthesize action=_action;
@property(retain, nonatomic) NSString *badgeText; // @synthesize badgeText=_badgeText;
@property(retain, nonatomic) NSString *secondaryLabel; // @synthesize secondaryLabel=_secondaryLabel;
@property(retain, nonatomic) NSString *label; // @synthesize label=_label;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(nonatomic) _Bool disabled; // @synthesize disabled=_disabled;

@end

