//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMPageSheetBaseView.h"

#import "MMCommonPickerDelegate-Protocol.h"
#import "MMPageSheetBottomViewDelegate-Protocol.h"

@class MMCommonPickerView, NSNumber, NSString, UIView;
@protocol MMLivePausePickerViewDelegate;

@interface MMLivePausePickerView : MMPageSheetBaseView <MMPageSheetBottomViewDelegate, MMCommonPickerDelegate>
{
    id <MMLivePausePickerViewDelegate> _delegate;
    UIView *_contentView;
    MMCommonPickerView *_pickerView;
    UIView *_pickerViewCustomizedIndicatorTopLine;
    UIView *_pickerViewCustomizedIndicatorBottomLine;
    NSNumber *_selectedDuration;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSNumber *selectedDuration; // @synthesize selectedDuration=_selectedDuration;
@property(retain, nonatomic) UIView *pickerViewCustomizedIndicatorBottomLine; // @synthesize pickerViewCustomizedIndicatorBottomLine=_pickerViewCustomizedIndicatorBottomLine;
@property(retain, nonatomic) UIView *pickerViewCustomizedIndicatorTopLine; // @synthesize pickerViewCustomizedIndicatorTopLine=_pickerViewCustomizedIndicatorTopLine;
@property(retain, nonatomic) MMCommonPickerView *pickerView; // @synthesize pickerView=_pickerView;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) __weak id <MMLivePausePickerViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)onPickerViewDidSelectRow:(long long)arg1 inComponent:(long long)arg2 PickItem:(id)arg3;
- (double)bottomViewBottomMargin;
- (double)bottomViewTopMargin;
- (void)onClickPageSheetConfirmButton;
- (void)onClickPageSheetCancelButton;
- (id)colorForPageSheetConfirmButton;
- (id)colorForPageSheetCancelButton;
- (id)titleForPageSheetConfirmButton;
- (id)titleForPageSheetCancelButton;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

