//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUserService.h"

#import "MMServiceProtocol-Protocol.h"

@class NSMutableDictionary, NSString;

@interface MMListenGetLyricService : MMUserService <MMServiceProtocol>
{
    NSMutableDictionary *_musicKey2GetLyricResponseItem;
    NSMutableDictionary *_musicKey2GetLyricResponseTime;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableDictionary *musicKey2GetLyricResponseTime; // @synthesize musicKey2GetLyricResponseTime=_musicKey2GetLyricResponseTime;
@property(retain, nonatomic) NSMutableDictionary *musicKey2GetLyricResponseItem; // @synthesize musicKey2GetLyricResponseItem=_musicKey2GetLyricResponseItem;
- (id)genMusicKeyWithMusicInfo:(id)arg1;
- (id)lyricItemWithListenId:(id)arg1 listenGetLyricResponse:(id)arg2;
- (void)sendGetListenItemWithSongId:(id)arg1 musicInfo:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)sendGetListenLyricWithSongId:(id)arg1 musicInfo:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)onServiceClearData;
- (void)onServiceInit;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

