//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIView.h"

@class MMUIImageView, MMUILabel;

@interface MMLiveProfileReplayCellDesc : MMUIView
{
    MMUIView *_background;
    MMUIImageView *_iconView;
    MMUILabel *_descLabel;
    MMUILabel *_paidLabel;
    unsigned long long _style;
}

+ (struct CGSize)caculateSize:(unsigned long long)arg1 data:(id)arg2;
+ (id)getDescText:(unsigned long long)arg1 data:(id)arg2;
+ (id)getDescFont:(unsigned long long)arg1;
- (void).cxx_destruct;
@property(nonatomic) unsigned long long style; // @synthesize style=_style;
@property(retain, nonatomic) MMUILabel *paidLabel; // @synthesize paidLabel=_paidLabel;
@property(retain, nonatomic) MMUILabel *descLabel; // @synthesize descLabel=_descLabel;
@property(retain, nonatomic) MMUIImageView *iconView; // @synthesize iconView=_iconView;
@property(retain, nonatomic) MMUIView *background; // @synthesize background=_background;
- (void)updateWithDataItem:(id)arg1;
- (void)layoutHide;
- (void)layoutWordingAlert;
- (void)layoutLock;
- (void)layoutNormal;
- (void)layoutPaid;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

