//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class MMUILabel, RichTextView, SnsPoiDetail;

@interface MMLocationPoiDetailView : UIView
{
    SnsPoiDetail *_poiDetail;
    _Bool _showTakeCarBtn;
    RichTextView *_priceTipsLabel;
    RichTextView *_businessHourLabel;
    RichTextView *_phoneLabel;
    MMUILabel *_noticeWordingLabel;
}

+ (double)contentHeight:(id)arg1 maxWidth:(double)arg2 showTakeCarBtn:(_Bool)arg3;
- (void).cxx_destruct;
@property(retain, nonatomic) MMUILabel *noticeWordingLabel; // @synthesize noticeWordingLabel=_noticeWordingLabel;
@property(retain, nonatomic) RichTextView *phoneLabel; // @synthesize phoneLabel=_phoneLabel;
@property(retain, nonatomic) RichTextView *businessHourLabel; // @synthesize businessHourLabel=_businessHourLabel;
@property(retain, nonatomic) RichTextView *priceTipsLabel; // @synthesize priceTipsLabel=_priceTipsLabel;
@property(nonatomic) _Bool showTakeCarBtn; // @synthesize showTakeCarBtn=_showTakeCarBtn;
- (void)updateWith:(id)arg1;
- (void)adjustLabelsPosition;
- (void)initSubviews;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

