//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "MMOrderCenterTableViewCellComponent-Protocol.h"

@class MMCustomerOrderInfo, MMUIButton, NSString;
@protocol MMOrderCenterTableViewCellComponentAggregatedDelegate;

@interface MMOrderCenterTableViewCellTimeReviewView : UIView <MMOrderCenterTableViewCellComponent>
{
    id <MMOrderCenterTableViewCellComponentAggregatedDelegate> _delegate;
    MMUIButton *_rateButton;
    MMCustomerOrderInfo *_order;
}

+ (id)rateButtonLabelForOrder:(id)arg1;
+ (id)timeStringForOrder:(id)arg1;
+ (_Bool)shouldUseComponentForOrder:(id)arg1;
+ (double)heightForOrder:(id)arg1 inWidth:(double)arg2 estimate:(_Bool)arg3;
- (void).cxx_destruct;
@property(retain, nonatomic) MMCustomerOrderInfo *order; // @synthesize order=_order;
@property(retain, nonatomic) MMUIButton *rateButton; // @synthesize rateButton=_rateButton;
@property(nonatomic) __weak id <MMOrderCenterTableViewCellComponentAggregatedDelegate> delegate; // @synthesize delegate=_delegate;
- (void)onReviewButtonTapped;
- (void)onCellWillDisplay;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (void)updateWithOrder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

