//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MMCustomerOrderInfo;
@protocol MMOrderCenterTableViewCellComponentAggregatedDelegate;

@protocol MMOrderCenterTableViewCellComponent <NSObject>
+ (_Bool)shouldUseComponentForOrder:(MMCustomerOrderInfo *)arg1;
+ (double)heightForOrder:(MMCustomerOrderInfo *)arg1 inWidth:(double)arg2 estimate:(_Bool)arg3;
@property(nonatomic) __weak id <MMOrderCenterTableViewCellComponentAggregatedDelegate> delegate;
- (void)onCellWillDisplay;
- (void)updateWithOrder:(MMCustomerOrderInfo *)arg1;
@end

