//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "PBCoding-Protocol.h"

@class NSData, NSString;

@interface MMPatternLockBufferData : NSObject <PBCoding>
{
    unsigned int _uin;
    unsigned int _version;
    unsigned int _lockStatus;
    NSData *_svrPatternHash;
    NSData *_sign;
}

+ (void)initialize;
+ (void)PBArrayAdd_sign;
+ (void)PBArrayAdd_lockStatus;
+ (void)PBArrayAdd_svrPatternHash;
+ (void)PBArrayAdd_version;
+ (void)PBArrayAdd_uin;
- (void).cxx_destruct;
@property(retain, nonatomic) NSData *sign; // @synthesize sign=_sign;
@property(nonatomic) unsigned int lockStatus; // @synthesize lockStatus=_lockStatus;
@property(retain, nonatomic) NSData *svrPatternHash; // @synthesize svrPatternHash=_svrPatternHash;
@property(nonatomic) unsigned int version; // @synthesize version=_version;
@property(nonatomic) unsigned int uin; // @synthesize uin=_uin;
- (id)getPBPropertyTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

