//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView;

@interface MMPageSheetProgressiveDragView : UIView
{
    UIView *_barView;
    UIImageView *_arrowImageView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIImageView *arrowImageView; // @synthesize arrowImageView=_arrowImageView;
@property(retain, nonatomic) UIView *barView; // @synthesize barView=_barView;
- (void)layoutSubviews;
- (void)updateArrowColor:(id)arg1;
- (void)updateBarColor:(id)arg1;
- (void)onPageSheetDragToDismissOffset:(double)arg1 animated:(_Bool)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

