//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface MMPaddingView : UIView
{
    UIView *_child;
    struct UIEdgeInsets _padding;
}

+ (id)Padding:(struct UIEdgeInsets)arg1 child:(id)arg2;
- (void).cxx_destruct;
@property(readonly, nonatomic) UIView *child; // @synthesize child=_child;
@property(nonatomic) struct UIEdgeInsets padding; // @synthesize padding=_padding;
- (id)initWithPadding:(struct UIEdgeInsets)arg1 child:(id)arg2;
- (void)layoutSubviews;
- (struct CGSize)intrinsicContentSize;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;

@end

