//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MMTableView, NSSet, UIEvent, UIGestureRecognizer;

@protocol MMTableViewDelegate <NSObject>

@optional
- (_Bool)mmTableView:(MMTableView *)arg1 shouldPassHitTest:(struct CGPoint)arg2 withEvent:(UIEvent *)arg3;
- (_Bool)mmTableView:(MMTableView *)arg1 shouldBeginRecognizeGesture:(UIGestureRecognizer *)arg2;
- (void)mmTableView:(MMTableView *)arg1 safeAreaInsetsDidChange:(struct UIEdgeInsets)arg2;
- (void)mmTableView:(MMTableView *)arg1 dragTriggerNotifyWithOffset:(double)arg2;
- (void)mmTableViewDidFinishedLoading:(MMTableView *)arg1;
- (void)mmTableView:(MMTableView *)arg1 touchesCancelled:(NSSet *)arg2 withEvent:(UIEvent *)arg3;
- (void)mmTableView:(MMTableView *)arg1 touchesEnded:(NSSet *)arg2 withEvent:(UIEvent *)arg3;
- (void)mmTableView:(MMTableView *)arg1 touchesMoved:(NSSet *)arg2 withEvent:(UIEvent *)arg3;
- (void)mmTableView:(MMTableView *)arg1 touchesBegan:(NSSet *)arg2 withEvent:(UIEvent *)arg3;
@end

