//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface MMWebViewConfig : NSObject
{
}

+ (_Bool)shouldTrickKBSnapshot;
+ (_Bool)shouldUsePlaybackPauseWhenDelayRelease;
+ (_Bool)shouldUseOneBridge;
+ (_Bool)shouldUseNewWebAttachmentDownloadInterface;
+ (_Bool)shouldOpenRecentForwardInWebMenu;
+ (_Bool)shouldDisableWebviewBottomBarWhenContentSizeChangedAdjustment;
+ (_Bool)shouldRecallWebviewBottomBarBugfix;
+ (_Bool)shouldSendAppMessageWithoutThumbUrl;
+ (unsigned int)webviewMaxFontLevel;
+ (id)arrWebViewFontSizes;
+ (_Bool)isDisableWebViewIPadNewFontSolution;
+ (_Bool)isEnableWebDebugFunctions;
+ (_Bool)shouldCloseMinimize;
+ (_Bool)disableJSAPIProtectionBeforeNavigationCommit;
+ (_Bool)abtestAllowCallJsapiBeforeLoad;
+ (long long)abTestTriggerReportCount;
+ (_Bool)isABTestUseNativeOauth;
+ (_Bool)isABTestAllowForceSyncA8Key;

@end

