//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, UIImageView, UILabel;

@interface MMWebviewOAuthRemindHalfScreenView : UIView
{
    CDUnknownBlockType _authblock;
    UIImageView *_warningIcon;
    UILabel *_remindLabel;
    UIButton *_authButton;
    UIImageView *_arrowIcon;
    UIView *_highlightView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIView *highlightView; // @synthesize highlightView=_highlightView;
@property(retain, nonatomic) UIImageView *arrowIcon; // @synthesize arrowIcon=_arrowIcon;
@property(retain, nonatomic) UIButton *authButton; // @synthesize authButton=_authButton;
@property(retain, nonatomic) UILabel *remindLabel; // @synthesize remindLabel=_remindLabel;
@property(retain, nonatomic) UIImageView *warningIcon; // @synthesize warningIcon=_warningIcon;
@property(copy, nonatomic) CDUnknownBlockType authblock; // @synthesize authblock=_authblock;
- (void)showHighlightAnimation;
- (void)onAuthButtonClicked;
- (void)setWidth:(double)arg1;
- (void)updateMaskLayer;
- (double)calcButtonPaddingWithWidth:(double)arg1;
- (double)calceRemindLabelWidthWithWidth:(double)arg1;
- (void)layoutSubviews;
- (void)initViews;
- (id)initWithAuthBlock:(CDUnknownBlockType)arg1;

@end

