//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface ModTextStatusDataItem : NSObject
{
    unsigned int _sequence;
    NSString *_username;
    NSString *_textStateId;
    NSString *_textStateExtInfo;
    double _friendScore;
}

+ (id)modelCustomPropertyMapperForConfigTag:(id)arg1;
- (void).cxx_destruct;
@property(nonatomic) unsigned int sequence; // @synthesize sequence=_sequence;
@property(nonatomic) double friendScore; // @synthesize friendScore=_friendScore;
@property(retain, nonatomic) NSString *textStateExtInfo; // @synthesize textStateExtInfo=_textStateExtInfo;
@property(retain, nonatomic) NSString *textStateId; // @synthesize textStateId=_textStateId;
@property(retain, nonatomic) NSString *username; // @synthesize username=_username;
- (id)textState;
- (_Bool)isValid;
- (id)description;

@end

