//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MMIotNavigateInfo, MMIotWordingInfo, WCDevice;

@protocol MsgToDeviceDelegate <NSObject>
- (void)onMsgToDeviceSending:(WCDevice *)arg1 progress:(double)arg2;
- (void)onMsgToDeviceFail:(WCDevice *)arg1 type:(long long)arg2 errorInfo:(MMIotWordingInfo *)arg3;
- (void)onMsgToDeviceSuccess:(WCDevice *)arg1;

@optional
- (void)onMsgToDeviceSuccessToWeApp:(MMIotNavigateInfo *)arg1;
@end

