//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol OVCGIFToVideoConverterDelegate;

@interface OVCGIFToVideoConverter : NSObject
{
    struct SharedPtr<XVCGIFToVideoConverter> _backingConvertor;
    id <OVCGIFToVideoConverterDelegate> _delegate;
}

- (id).cxx_construct;
- (void).cxx_destruct;
@property(nonatomic) __weak id <OVCGIFToVideoConverterDelegate> delegate; // @synthesize delegate=_delegate;
- (void)cancelConverting;
- (void)startConvertingWithGIFFilePath:(id)arg1 toVideo:(id)arg2 progressHandler:(CDUnknownBlockType)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (id)init;

@end

