//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary;

@interface OVCLowerThirdTextLayerBuildData : NSObject
{
    _Bool _shouldUsePlaceholder;
    NSDictionary *_mustacheData;
    NSDictionary *_userInputsByBlockID;
    NSDictionary *_defaultContentsByBlockID;
    NSDictionary *_placeholdersByBlockID;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool shouldUsePlaceholder; // @synthesize shouldUsePlaceholder=_shouldUsePlaceholder;
@property(readonly, nonatomic) NSDictionary *placeholdersByBlockID; // @synthesize placeholdersByBlockID=_placeholdersByBlockID;
@property(readonly, nonatomic) NSDictionary *defaultContentsByBlockID; // @synthesize defaultContentsByBlockID=_defaultContentsByBlockID;
@property(readonly, nonatomic) NSDictionary *userInputsByBlockID; // @synthesize userInputsByBlockID=_userInputsByBlockID;
@property(readonly, nonatomic) NSDictionary *mustacheData; // @synthesize mustacheData=_mustacheData;
- (id)initWithMustacheData:(id)arg1 userInputsByBlockID:(id)arg2 defaultContentsByBlockID:(id)arg3 placeholdersByBlockID:(id)arg4 shouldUsePlaceholder:(_Bool)arg5;

@end

