//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class FlutterPAGInfo, NSNumber, NSString;

@protocol PAGViewApi
- (void)flushPagId:(NSNumber *)arg1 completion:(void (^)(NSNumber *, FlutterError *))arg2;
- (NSNumber *)replaceImagePagId:(NSNumber *)arg1 index:(NSNumber *)arg2 filepath:(NSString *)arg3 error:(id *)arg4;
- (NSNumber *)setSolidLayerColorPagId:(NSNumber *)arg1 name:(NSString *)arg2 color:(NSNumber *)arg3 error:(id *)arg4;
- (void)seekPagId:(NSNumber *)arg1 timeMs:(NSNumber *)arg2 error:(id *)arg3;
- (void)pagViewReleasePagId:(NSNumber *)arg1 error:(id *)arg2;
- (NSNumber *)pagViewStopPagId:(NSNumber *)arg1 error:(id *)arg2;
- (NSNumber *)pagViewStartPlayPagId:(NSNumber *)arg1 error:(id *)arg2;
- (void)createInfo:(FlutterPAGInfo *)arg1 completion:(void (^)(NSNumber *, FlutterError *))arg2;
@end

