//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface PixelColorRequestTask : NSObject
{
    unsigned long long _format;
    CDUnknownBlockType _callback;
    NSArray *_coordinateList;
    struct CGSize _fromSize;
}

- (void).cxx_destruct;
@property(nonatomic) struct CGSize fromSize; // @synthesize fromSize=_fromSize;
@property(retain, nonatomic) NSArray *coordinateList; // @synthesize coordinateList=_coordinateList;
@property(copy, nonatomic) CDUnknownBlockType callback; // @synthesize callback=_callback;
@property(nonatomic) unsigned long long format; // @synthesize format=_format;

@end

