//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class BaseRequest, GetWecoinPriceListResponse, NSString;

@interface PrepareWecoinRechargeRequest : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned int agreementVersion; // @dynamic agreementVersion;
@property(retain, nonatomic) BaseRequest *baseRequest; // @dynamic baseRequest;
@property(nonatomic) unsigned int businessId; // @dynamic businessId;
@property(retain, nonatomic) NSString *currencyCode; // @dynamic currencyCode;
@property(nonatomic) unsigned long long customCount; // @dynamic customCount;
@property(nonatomic) unsigned long long diffWecoinCount; // @dynamic diffWecoinCount;
@property(retain, nonatomic) GetWecoinPriceListResponse *priceListResp; // @dynamic priceListResp;
@property(retain, nonatomic) NSString *rechargeProductId; // @dynamic rechargeProductId;
@property(retain, nonatomic) NSString *reportSessionId; // @dynamic reportSessionId;
@property(retain, nonatomic) NSString *requestId; // @dynamic requestId;
@property(nonatomic) unsigned int scene; // @dynamic scene;

@end

