//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class NSMutableArray, NSString, TipsInfo;

@interface RecvAccountInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;
+ (id)modelContainerPropertyMappingForConfigTag:(id)arg1;

// Remaining properties
@property(retain, nonatomic) TipsInfo *acctUsageTips; // @dynamic acctUsageTips;
@property(retain, nonatomic) NSString *listTitle; // @dynamic listTitle;
@property(retain, nonatomic) NSString *noAvailabelAccountWording; // @dynamic noAvailabelAccountWording;
@property(retain, nonatomic) NSMutableArray *recvChannel; // @dynamic recvChannel;

@end

