//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "RingTonePlayer-Protocol.h"
#import "RingTonePlayerExt-Protocol.h"

@class NSString, RingToneAvPlayer, RingToneFinderPlayerView;
@protocol RingTonePlayer;

@interface RingToneMixPlayer : NSObject <RingTonePlayerExt, RingTonePlayer>
{
    _Bool _customVibrateEnabled;
    _Bool _shouldPlayForcibly;
    unsigned long long _scene;
    NSString *_identifier;
    NSObject<RingTonePlayer> *_curPlayer;
    RingToneFinderPlayerView *_finderPlayerView;
    RingToneAvPlayer *_avPlayer;
}

- (void).cxx_destruct;
@property(retain, nonatomic) RingToneAvPlayer *avPlayer; // @synthesize avPlayer=_avPlayer;
@property(retain, nonatomic) RingToneFinderPlayerView *finderPlayerView; // @synthesize finderPlayerView=_finderPlayerView;
@property(retain, nonatomic) NSObject<RingTonePlayer> *curPlayer; // @synthesize curPlayer=_curPlayer;
@property(nonatomic) _Bool shouldPlayForcibly; // @synthesize shouldPlayForcibly=_shouldPlayForcibly;
@property(nonatomic) _Bool customVibrateEnabled; // @synthesize customVibrateEnabled=_customVibrateEnabled;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(nonatomic) unsigned long long scene; // @synthesize scene=_scene;
- (double)currentPlayTime;
- (void)stopAllPlay;
- (void)stopPlay;
- (void)__playRing:(id)arg1;
- (void)playRing:(id)arg1;
- (void)playDefaultRing;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

