//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AVFoundation/AVPlayer.h>

#import "RingTonePlayer-Protocol.h"
#import "RingToneVibrateDataSource-Protocol.h"

@class NSObject, NSString, RingToneDetail, RingToneVibrateController;

@interface RingToneAvPlayer : AVPlayer <RingToneVibrateDataSource, RingTonePlayer>
{
    _Bool _enableVibrate;
    _Bool _customVibrateEnabled;
    double _lastPlayTime;
    unsigned long long _playTimeStamp;
    RingToneDetail *_curRing;
    NSString *_ringId;
    RingToneVibrateController *_vibrateController;
    NSObject *_timeObserver;
    NSString *_curPlayFile;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *curPlayFile; // @synthesize curPlayFile=_curPlayFile;
@property(retain, nonatomic) NSObject *timeObserver; // @synthesize timeObserver=_timeObserver;
@property(retain, nonatomic) RingToneVibrateController *vibrateController; // @synthesize vibrateController=_vibrateController;
@property(copy, nonatomic) NSString *ringId; // @synthesize ringId=_ringId;
@property(retain, nonatomic) RingToneDetail *curRing; // @synthesize curRing=_curRing;
@property(nonatomic) unsigned long long playTimeStamp; // @synthesize playTimeStamp=_playTimeStamp;
@property(nonatomic) double lastPlayTime; // @synthesize lastPlayTime=_lastPlayTime;
@property(nonatomic) _Bool customVibrateEnabled; // @synthesize customVibrateEnabled=_customVibrateEnabled;
@property(nonatomic) _Bool enableVibrate; // @synthesize enableVibrate=_enableVibrate;
- (double)currentPlayTime;
- (void)restart;
- (void)setMute:(_Bool)arg1;
- (void)resume;
- (void)pause;
- (void)vibrateWithRing:(id)arg1;
- (void)vibrateWithCaller:(id)arg1;
- (void)setRingToneAvPlayerFailPlayCount:(unsigned int)arg1;
- (int)getRingToneAvPlayerFailPlayCount;
- (void)continuePlayWhenAppEnterForeground;
- (void)onFailPlayEnd;
- (void)onPlayEnd;
- (void)startToPlay;
- (void)playAudioFile:(id)arg1;
- (void)playMusicFile:(id)arg1;
- (void)clearResource;
- (void)stopPlay;
- (void)playDefaultRing;
- (void)playRing:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

