//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class NSString;

@interface StatusFooterJumpLivePlayerNoBg : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSString *eventHeadUrl; // @dynamic eventHeadUrl;
@property(retain, nonatomic) NSString *eventNickname; // @dynamic eventNickname;
@property(retain, nonatomic) NSString *eventUsername; // @dynamic eventUsername;
@property(nonatomic) unsigned long long feedId; // @dynamic feedId;
@property(retain, nonatomic) NSString *headUrl; // @dynamic headUrl;
@property(retain, nonatomic) NSString *nickname; // @dynamic nickname;
@property(retain, nonatomic) NSString *nonceId; // @dynamic nonceId;
@property(retain, nonatomic) NSString *relayIndex; // @dynamic relayIndex;
@property(retain, nonatomic) NSString *username; // @dynamic username;

@end

