//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary;

@interface SystemAuthConfig : NSObject
{
    NSDictionary *_webSceneMap;
    unsigned long long _version;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned long long version; // @synthesize version=_version;
@property(retain, nonatomic) NSDictionary *webSceneMap; // @synthesize webSceneMap=_webSceneMap;
- (id)initWithFile:(id)arg1;

@end

