//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionReusableView.h>

@class MMUILabel, TextStateHistoryCalendarSection;

@interface TextStateHistoryCalendarSectionHeaderView : UICollectionReusableView
{
    _Bool _singleRowLayout;
    TextStateHistoryCalendarSection *_section;
    MMUILabel *_timeLabel;
    MMUILabel *_topUseIconLabel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) MMUILabel *topUseIconLabel; // @synthesize topUseIconLabel=_topUseIconLabel;
@property(retain, nonatomic) MMUILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(nonatomic) _Bool singleRowLayout; // @synthesize singleRowLayout=_singleRowLayout;
@property(retain, nonatomic) TextStateHistoryCalendarSection *section; // @synthesize section=_section;
- (void)updateLayout;
- (void)layoutSubviews;
- (void)initSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

