//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "PBCoding-Protocol.h"

@class NSString;

@interface TextStatePublishIconRecentUseItem : NSObject <PBCoding>
{
    unsigned int _useTime;
    NSString *_iconId;
    NSString *_iconDescription;
}

+ (void)initialize;
+ (void)PBArrayAdd_useTime;
+ (void)PBArrayAdd_iconDescription;
+ (void)PBArrayAdd_iconId;
- (void).cxx_destruct;
@property(nonatomic) unsigned int useTime; // @synthesize useTime=_useTime;
@property(retain, nonatomic) NSString *iconDescription; // @synthesize iconDescription=_iconDescription;
@property(retain, nonatomic) NSString *iconId; // @synthesize iconId=_iconId;
@property(readonly) unsigned long long hash;
- (_Bool)isEqual:(id)arg1;
- (_Bool)isEqualToItem:(id)arg1;
@property(readonly, copy) NSString *description;
- (long long)compare:(id)arg1;
- (_Bool)hasExpired;
- (_Bool)isValid;
- (id)key;
- (id)getPBPropertyTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

