//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionView.h>

#import "TextStateCollectionViewLayoutHistoryCalendarDelegate-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"

@class NSString, TextStateCollectionViewLayoutHistoryCalendar, TextStateHistoryCalendar, UITapGestureRecognizer;
@protocol TextStateHistoryCalendarCollectionViewDelegate;

@interface TextStateHistoryCalendarCollectionView : UICollectionView <TextStateCollectionViewLayoutHistoryCalendarDelegate, UICollectionViewDataSource>
{
    TextStateHistoryCalendar *_calendar;
    UITapGestureRecognizer *_tapGesture;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UITapGestureRecognizer *tapGesture; // @synthesize tapGesture=_tapGesture;
@property(retain, nonatomic) TextStateHistoryCalendar *calendar; // @synthesize calendar=_calendar;
- (_Bool)shouldShowYearForSection:(unsigned long long)arg1;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)onTap:(id)arg1;
- (id)itemReuseIdentifierWithInfoCount:(unsigned long long)arg1;
@property(nonatomic) _Bool showStoryEntry; // @dynamic showStoryEntry;
@property(readonly, nonatomic) TextStateCollectionViewLayoutHistoryCalendar *calendarLayout;
- (void)configure;
- (id)initWithFrame:(struct CGRect)arg1 collectionViewLayout:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(nonatomic) __weak id <TextStateHistoryCalendarCollectionViewDelegate> delegate; // @dynamic delegate;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

