//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface TextStateSimplifiedNotifyInfo : NSObject
{
    _Bool _isContact;
    unsigned int _createTime;
    NSString *_username;
    NSString *_headImageUrl;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool isContact; // @synthesize isContact=_isContact;
@property(retain, nonatomic) NSString *headImageUrl; // @synthesize headImageUrl=_headImageUrl;
@property(nonatomic) unsigned int createTime; // @synthesize createTime=_createTime;
@property(retain, nonatomic) NSString *username; // @synthesize username=_username;
- (id)initWithNotifyInfo:(id)arg1;

@end

