//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

#import "TingVoiceInputLogicDelegate-Protocol.h"

@class NSString, TingVoiceInputLogic, WCCgiBlockHelper;
@protocol TingVoiceInputManagerDelegate;

@interface TingVoiceInputManager : MMObject <TingVoiceInputLogicDelegate>
{
    id <TingVoiceInputManagerDelegate> _delegate;
    TingVoiceInputLogic *_inputLogic;
    WCCgiBlockHelper *_lastRequestCgi;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WCCgiBlockHelper *lastRequestCgi; // @synthesize lastRequestCgi=_lastRequestCgi;
@property(retain, nonatomic) TingVoiceInputLogic *inputLogic; // @synthesize inputLogic=_inputLogic;
@property(nonatomic) __weak id <TingVoiceInputManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)tingVoiceInputLogic:(id)arg1 voiceDetectSpeakingToSlience:(long long)arg2;
- (void)tingVoiceInputLogicVoiceSilentTooLong:(id)arg1;
- (void)tingVoiceInputLogic:(id)arg1 didRecognizedWithText:(id)arg2;
- (void)tingVoiceInputLogic:(id)arg1 onPeakPower:(float)arg2;
- (void)tingVoiceInputLogicRecordEnd:(id)arg1;
- (void)tingVoiceInputLogicDidStartRecoring:(id)arg1;
- (void)buildVoiceSearchRequest;
- (void)cancelRecord;
- (void)stopRecord;
- (_Bool)startRecord;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

