//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ICCollectionViewController.h"

#import "MMNavBarInteractiveDelegate-Protocol.h"
#import "RecentForwardScrollViewDelegate-Protocol.h"
#import "SharePreConfirmViewDelegate-Protocol.h"
#import "TingFlowPlayerNotification-Protocol.h"
#import "TingRelatedLineCellDelegate-Protocol.h"
#import "TingViewController-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class MMListenCategoryItem, MMListenCommentInfo, MMScrollActionSheet, MMUILabel, NSData, NSMutableArray, NSString, SharePreConfirmView, TingFooterView, TingSingerWikiHeaderView;

@interface TingSingerWikiViewController : ICCollectionViewController <RecentForwardScrollViewDelegate, SharePreConfirmViewDelegate, TingViewController, TingRelatedLineCellDelegate, UIScrollViewDelegate, TingFlowPlayerNotification, MMNavBarInteractiveDelegate>
{
    TingSingerWikiHeaderView *_headerView;
    TingFooterView *_loadFooterView;
    MMListenCategoryItem *_categoryItem;
    NSData *_sessionBuffer;
    NSMutableArray *_sectionDataArray;
    MMListenCommentInfo *_commentInfo;
    MMUILabel *_forbiddenLabel;
    MMScrollActionSheet *_scrollActionSheet;
    SharePreConfirmView *_sharePreConfirmView;
    struct CGPoint _originOffset;
}

- (void).cxx_destruct;
@property(retain, nonatomic) SharePreConfirmView *sharePreConfirmView; // @synthesize sharePreConfirmView=_sharePreConfirmView;
@property(nonatomic) __weak MMScrollActionSheet *scrollActionSheet; // @synthesize scrollActionSheet=_scrollActionSheet;
@property(retain, nonatomic) MMUILabel *forbiddenLabel; // @synthesize forbiddenLabel=_forbiddenLabel;
@property(retain, nonatomic) MMListenCommentInfo *commentInfo; // @synthesize commentInfo=_commentInfo;
@property(retain, nonatomic) NSMutableArray *sectionDataArray; // @synthesize sectionDataArray=_sectionDataArray;
@property(retain, nonatomic) NSData *sessionBuffer; // @synthesize sessionBuffer=_sessionBuffer;
@property(retain, nonatomic) MMListenCategoryItem *categoryItem; // @synthesize categoryItem=_categoryItem;
@property(nonatomic) struct CGPoint originOffset; // @synthesize originOffset=_originOffset;
@property(retain, nonatomic) TingFooterView *loadFooterView; // @synthesize loadFooterView=_loadFooterView;
@property(retain, nonatomic) TingSingerWikiHeaderView *headerView; // @synthesize headerView=_headerView;
- (id)buildFinderSectionDataFromCurCategory;
- (id)buildDescSectionDataFromCurCategory;
- (id)genSubTitleWithItem:(id)arg1 sectionType:(long long)arg2;
- (id)sectionTitleWithLine:(id)arg1;
- (long long)sectionTypeFromLineType:(int)arg1;
- (id)buildRelatedItemModel:(id)arg1 type:(int)arg2;
- (id)buildSectionDataFromLine:(id)arg1;
- (void)buildSectionDataWithDiscoverLines:(id)arg1;
- (void)fetchMpDiscoverDataWithFeedId:(id)arg1;
- (void)fetchNewCategoryById:(id)arg1;
- (void)reloadWithTingItem:(id)arg1;
- (id)validDiscoverLineTypes;
- (void)handleTingMoreButtonAction;
- (_Bool)showTingMoreButton;
- (id)getBitsCommentInfo;
- (unsigned long long)getCommentSecureBits;
- (void)checkoutForbiddenPage;
- (void)fetchCommentInfo;
- (void)checkoutMoreItemStatus;
- (void)openFinderVideo:(id)arg1;
- (void)onDescMoreButtonClicked;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (void)onRelatedItemCellClicked:(id)arg1 sectionData:(id)arg2 index:(long long)arg3;
- (void)onRelatedItemCellDisplayed:(id)arg1 sectionData:(id)arg2 index:(long long)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForFooterInSection:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(long long)arg3;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (id)collectionLayout;
- (id)reuseIdentifierForType:(long long)arg1;
- (void)setupCollectionView;
- (id)getReportContext;
- (void)resetCollectionContentSet;
- (id)normalTintColor;
- (void)setupNavigationBar;
- (id)getDefaultForegroundColor;
- (void)setupAlbumHeader;
- (void)viewDidTransitionToNewSize;
- (void)viewDidLayoutSubviews;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithCategory:(id)arg1;
- (void)OnSharePreConfirmViewCancel:(id)arg1;
- (void)OnSharePreConfirmViewSend:(id)arg1;
- (void)relayoutScrollSheet;
- (void)clickRFItemCallBack:(id)arg1;
- (id)getNewItemSheetList;
- (void)showMoreActions;
- (_Bool)isActionSheetHasItems;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

