//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray, NSMutableSet;
@protocol TingNativeFlowSessionDelegate;

@interface TingFlowSession : NSObject
{
    _Bool _hasMore;
    _Bool _isFirstLoad;
    _Bool _isDeactived;
    _Bool _isLoading;
    _Bool _loopUntilAllPresetItemFinish;
    id <TingNativeFlowSessionDelegate> _delegate;
    NSMutableSet *_existedIdSet;
    CDUnknownBlockType _itemIdCalculator;
    NSMutableArray *_itemsFromServer;
    NSMutableArray *_displayItems;
    NSArray *_presetItems;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *presetItems; // @synthesize presetItems=_presetItems;
@property(retain, nonatomic) NSMutableArray *displayItems; // @synthesize displayItems=_displayItems;
@property(retain, nonatomic) NSMutableArray *itemsFromServer; // @synthesize itemsFromServer=_itemsFromServer;
@property(copy, nonatomic) CDUnknownBlockType itemIdCalculator; // @synthesize itemIdCalculator=_itemIdCalculator;
@property(nonatomic) _Bool loopUntilAllPresetItemFinish; // @synthesize loopUntilAllPresetItemFinish=_loopUntilAllPresetItemFinish;
@property(nonatomic) _Bool isLoading; // @synthesize isLoading=_isLoading;
@property(nonatomic) _Bool isDeactived; // @synthesize isDeactived=_isDeactived;
@property(nonatomic) _Bool isFirstLoad; // @synthesize isFirstLoad=_isFirstLoad;
@property(nonatomic) _Bool hasMore; // @synthesize hasMore=_hasMore;
@property(retain, nonatomic) NSMutableSet *existedIdSet; // @synthesize existedIdSet=_existedIdSet;
@property(nonatomic) __weak id <TingNativeFlowSessionDelegate> delegate; // @synthesize delegate=_delegate;
- (id)allPresetItems;
- (id)allFetchedItems;
- (id)allDisplayItems;
- (id)allItems;
- (id)sessionBuffer;
- (void)cancelFetching;
- (void)insertNewTingItem:(id)arg1;
- (void)swapItemSourceIndex:(int)arg1 destination:(int)arg2;
- (id)updateDisplayItems:(id)arg1 shouldShuffle:(_Bool)arg2 replace:(_Bool)arg3;
- (id)updateDisplayItems:(id)arg1 replace:(_Bool)arg2;
- (void)removeItemInDisplayItem:(id)arg1;
- (void)removeItemAtIndex:(unsigned long long)arg1;
- (unsigned int)fetchFromServierWithIsLoadMore:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (id)replacedResultFromFromResponseListenItems:(id)arg1;
- (id)filteredResultFromResponseListenItems:(id)arg1;
- (id)loadPresetItems;
- (unsigned int)loadFromPresetItemsWithCompletion:(CDUnknownBlockType)arg1;
- (unsigned int)fetchMoreWithCompletion:(CDUnknownBlockType)arg1;
- (unsigned int)fetchNewWithCompletion:(CDUnknownBlockType)arg1;
- (void)copyPropertiesToSession:(id)arg1;
- (id)init;

@end

