//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCCommentDetailHeaderView.h"

@class MMUIButton, TingSectionHeaderView, TingSectionHeaderViewConfig;

@interface TingCommentDetailHeaderView : WCCommentDetailHeaderView
{
    CDUnknownBlockType _commentButtonHandler;
    TingSectionHeaderView *_headerView;
    TingSectionHeaderViewConfig *_headerViewConfig;
    MMUIButton *_commentButton;
}

+ (id)genConfig;
+ (double)headerViewHeight;
- (void).cxx_destruct;
@property(retain, nonatomic) MMUIButton *commentButton; // @synthesize commentButton=_commentButton;
@property(retain, nonatomic) TingSectionHeaderViewConfig *headerViewConfig; // @synthesize headerViewConfig=_headerViewConfig;
@property(retain, nonatomic) TingSectionHeaderView *headerView; // @synthesize headerView=_headerView;
@property(copy, nonatomic) CDUnknownBlockType commentButtonHandler; // @synthesize commentButtonHandler=_commentButtonHandler;
- (void)onCommentButtonClicked:(id)arg1;
- (void)updateTitle:(id)arg1;
- (void)configureLayout;
- (void)adjustLayout;
- (id)initWithFrame:(struct CGRect)arg1;

@end

