//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TingPTBPageLineCell.h"

@interface TingPTBFinderVideoLineCell : TingPTBPageLineCell
{
}

+ (double)autosizingLineHeight:(id)arg1;
+ (double)textHeightPerLine;
+ (double)cellWidth;
+ (struct UIEdgeInsets)sectionInset;
- (id)cellForItem:(id)arg1 indexPath:(id)arg2;
- (int)velocityHighPageDiff;
- (int)velocityLowPageDiff;
- (void)setupCollectionView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

