//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TingMinimizeBaseTask.h"

#import "MMImageLoaderObserver-Protocol.h"
#import "MiniAudioTaskContentViewDelegate-Protocol.h"

@class MiniAudioTaskContentView, NSString, TingTapePlayingInfo;

@interface TingMinimizePlayerTask : TingMinimizeBaseTask <MiniAudioTaskContentViewDelegate, MMImageLoaderObserver>
{
    _Bool _bActive;
    MiniAudioTaskContentView *_contentView;
    TingTapePlayingInfo *_playingInfo;
}

+ (_Bool)isInPlayerListScene;
- (void).cxx_destruct;
@property(retain, nonatomic) TingTapePlayingInfo *playingInfo; // @synthesize playingInfo=_playingInfo;
@property(nonatomic) _Bool bActive; // @synthesize bActive=_bActive;
@property(retain, nonatomic) MiniAudioTaskContentView *contentView; // @synthesize contentView=_contentView;
- (void)onMiniAudioContentViewOuterContentClicked;
- (void)onMiniAudioContentViewPlayPauseButtonClicked:(_Bool)arg1;
- (void)onMiniAudioContentViewCloseButtonClicked;
- (_Bool)isTaskActive;
- (void)hideTaskAnimated:(_Bool)arg1;
- (void)tryShowTaskAnimated:(_Bool)arg1 voiceTic:(_Bool)arg2;
- (void)updateMinimizeTaskStateWithContext:(id)arg1 animated:(_Bool)arg2 voiceTic:(_Bool)arg3;
- (void)updateMinimizeTaskStateWithContext:(id)arg1 animated:(_Bool)arg2;
- (void)onMinimizeTaskEngaged;
- (void)onMinimizeTaskActive;
- (id)taskContainerView;
- (void)ImageDidLoad:(id)arg1 Url:(id)arg2;
- (void)updatePlayingInfo:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

