//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIView.h"

@class MMUIButton, MMUILabel;

@interface TingCategoryInfoFooterView : MMUIView
{
    CDUnknownBlockType _clickCommentBlock;
    MMUILabel *_infoLabel;
    MMUILabel *_publicTimeLabel;
    MMUIButton *_commentButton;
}

+ (double)containerHeight;
- (void).cxx_destruct;
@property(retain, nonatomic) MMUIButton *commentButton; // @synthesize commentButton=_commentButton;
@property(retain, nonatomic) MMUILabel *publicTimeLabel; // @synthesize publicTimeLabel=_publicTimeLabel;
@property(retain, nonatomic) MMUILabel *infoLabel; // @synthesize infoLabel=_infoLabel;
@property(copy, nonatomic) CDUnknownBlockType clickCommentBlock; // @synthesize clickCommentBlock=_clickCommentBlock;
- (void)onCommentButtonClicked:(id)arg1;
- (void)updateCommentBtnDisplay:(_Bool)arg1 wording:(id)arg2;
- (void)updateContentWithInfo:(id)arg1 publicTime:(id)arg2;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

