//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSProxy.h>

@class TPDataTransportManagerProxyDelegate, TPPlayerEventPublisher, TPProxyPlayManager;
@protocol TPProxyPlayDelegate;

@interface TPDataTransportManagerProxy : NSProxy
{
    TPProxyPlayManager *_manager;
    id <TPProxyPlayDelegate> _outerDelegate;
    TPDataTransportManagerProxyDelegate *_proxyDelegate;
    TPPlayerEventPublisher *_publisher;
}

- (void).cxx_destruct;
@property(retain, nonatomic) TPPlayerEventPublisher *publisher; // @synthesize publisher=_publisher;
@property(retain, nonatomic) TPDataTransportManagerProxyDelegate *proxyDelegate; // @synthesize proxyDelegate=_proxyDelegate;
@property(nonatomic) __weak id <TPProxyPlayDelegate> outerDelegate; // @synthesize outerDelegate=_outerDelegate;
@property(retain, nonatomic) TPProxyPlayManager *manager; // @synthesize manager=_manager;
- (void)pushEventAfterInvokeIfNeed:(id)arg1;
- (void)hookDelegateIfNeed:(id)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;
- (void)forwardInvocation:(id)arg1;
- (id)initDataTransportManagerProxy:(id)arg1 withContext:(id)arg2;

@end

