//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface TPLiveReportParamRecord : NSObject
{
    long long _prepareEndSinceBootTimeMs;
    long long _playerFirstStartSinceBootTimeMs;
    long long _playerStartSinceBootTimeMs;
    long long _retentionDurationMs;
    long long _bufferingStartSinceBootTimeMs;
    long long _periodBufferingTotalDurationMs;
    long long _periodBufferingCount;
    long long _periodPlayedDurationMs;
}

@property(nonatomic) long long periodPlayedDurationMs; // @synthesize periodPlayedDurationMs=_periodPlayedDurationMs;
@property(nonatomic) long long periodBufferingCount; // @synthesize periodBufferingCount=_periodBufferingCount;
@property(nonatomic) long long periodBufferingTotalDurationMs; // @synthesize periodBufferingTotalDurationMs=_periodBufferingTotalDurationMs;
@property(nonatomic) long long bufferingStartSinceBootTimeMs; // @synthesize bufferingStartSinceBootTimeMs=_bufferingStartSinceBootTimeMs;
@property(nonatomic) long long retentionDurationMs; // @synthesize retentionDurationMs=_retentionDurationMs;
@property(nonatomic) long long playerStartSinceBootTimeMs; // @synthesize playerStartSinceBootTimeMs=_playerStartSinceBootTimeMs;
@property(nonatomic) long long playerFirstStartSinceBootTimeMs; // @synthesize playerFirstStartSinceBootTimeMs=_playerFirstStartSinceBootTimeMs;
@property(nonatomic) long long prepareEndSinceBootTimeMs; // @synthesize prepareEndSinceBootTimeMs=_prepareEndSinceBootTimeMs;

@end

