//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface TPRichMediaFeatureData : NSObject
{
    NSString *_featureType;
    NSString *_env;
    NSString *_version;
    NSArray *_featureContents;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSArray *featureContents; // @synthesize featureContents=_featureContents;
@property(copy, nonatomic) NSString *version; // @synthesize version=_version;
@property(copy, nonatomic) NSString *env; // @synthesize env=_env;
@property(copy, nonatomic) NSString *featureType; // @synthesize featureType=_featureType;

@end

