//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, TXCHardwareVideoEncoder;

@interface TXCHardwareVideoEncoderParams : NSObject
{
    TXCHardwareVideoEncoder *_encoder;
    CDUnknownBlockType _complete;
    NSDate *_encodeStartTime;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSDate *encodeStartTime; // @synthesize encodeStartTime=_encodeStartTime;
@property(copy, nonatomic) CDUnknownBlockType complete; // @synthesize complete=_complete;
@property __weak TXCHardwareVideoEncoder *encoder; // @synthesize encoder=_encoder;

@end

