//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "TXIIOSScreenCapturerInterface-Protocol.h"
#import "TXIVideoCaptureInterface-Protocol.h"
#import "TXReplayKitAppDelegate-Protocol.h"

@class NSMutableSet, NSString, TXCDispatchQueue;

@interface TXCIOSScreenCapturer : NSObject <TXReplayKitAppDelegate, TXIVideoCaptureInterface, TXIIOSScreenCapturerInterface>
{
    struct EncodeParamsTypeHeader _currentEncodeParams;
    _Bool _isRunning;
    TXCDispatchQueue *_queue;
    TXCDispatchQueue *_outputQueue;
    NSMutableSet *_subscribers;
    NSString *_appGroupId;
}

- (void).cxx_destruct;
@property _Bool isRunning; // @synthesize isRunning=_isRunning;
@property(retain, nonatomic) NSString *appGroupId; // @synthesize appGroupId=_appGroupId;
@property(retain, nonatomic) NSMutableSet *subscribers; // @synthesize subscribers=_subscribers;
@property(retain, nonatomic) TXCDispatchQueue *outputQueue; // @synthesize outputQueue=_outputQueue;
@property(retain, nonatomic) TXCDispatchQueue *queue; // @synthesize queue=_queue;
- (void)requestKeyFrame;
- (void)setEncodeParams:(const void *)arg1;
- (void)onBroadcastExtResumed;
- (void)onBroadcastExtPaused;
- (void)onBroadcastExtFinished;
- (void)onBroadcastExtStarted;
- (void)onReceiveVideoPacket:(const void *)arg1;
- (void)stop;
- (void)start;
- (void)setFrameRate:(long long)arg1;
- (void)applyConfigs:(id)arg1;
@property(readonly, nonatomic) unsigned long long captureType;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (id)initWithQueue:(id)arg1 outputQueue:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

