//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TXCBeautifyBaseFilter.h"

@class TXCMaskFilter, TXCSharpFilter, TXCSmoothHorizontalFilter, TXCSmoothMixFilter, TXCSmoothVerticalFilter;

@interface TXCSmoothBeautifyFilter : TXCBeautifyBaseFilter
{
    TXCMaskFilter *_maskFilter;
    TXCSmoothHorizontalFilter *_smoothHorizontalFilter;
    TXCSmoothVerticalFilter *_smoothVerticalFilter;
    TXCSmoothMixFilter *_smoothMixFilter;
    TXCSharpFilter *_sharpFilter;
}

- (void).cxx_destruct;
@property(retain, nonatomic) TXCSharpFilter *sharpFilter; // @synthesize sharpFilter=_sharpFilter;
@property(retain, nonatomic) TXCSmoothMixFilter *smoothMixFilter; // @synthesize smoothMixFilter=_smoothMixFilter;
@property(retain, nonatomic) TXCSmoothVerticalFilter *smoothVerticalFilter; // @synthesize smoothVerticalFilter=_smoothVerticalFilter;
@property(retain, nonatomic) TXCSmoothHorizontalFilter *smoothHorizontalFilter; // @synthesize smoothHorizontalFilter=_smoothHorizontalFilter;
@property(retain, nonatomic) TXCMaskFilter *maskFilter; // @synthesize maskFilter=_maskFilter;
- (id)processVideoFrame:(id)arg1;
- (unsigned long long)beautyStyle;
- (id)fragmentShaderString;
- (id)initWithContext:(id)arg1;

@end

