//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface VideoEncodeTaskParams : NSObject
{
    _Bool _isHighPriority;
    _Bool _isTaskReplicable;
    _Bool _keepsProcessInBackground;
    _Bool _isAutoRetryEnabled;
}

@property(nonatomic) _Bool isAutoRetryEnabled; // @synthesize isAutoRetryEnabled=_isAutoRetryEnabled;
@property(nonatomic) _Bool keepsProcessInBackground; // @synthesize keepsProcessInBackground=_keepsProcessInBackground;
@property(nonatomic) _Bool isTaskReplicable; // @synthesize isTaskReplicable=_isTaskReplicable;
@property(nonatomic) _Bool isHighPriority; // @synthesize isHighPriority=_isHighPriority;

@end

