//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUserService.h"

#import "MMServiceProtocol-Protocol.h"

@class CMMotionManager, NSString;

@interface VoIPOrientationService : MMUserService <MMServiceProtocol>
{
    _Bool _isSystemLockActived;
    double _deviceAngleDegree;
    long long _deviceOrientation;
    long long _motionOrientation;
    CMMotionManager *_motion;
}

+ (long long)interfaceOrientation;
+ (long long)realtimeDeviceOrientation;
+ (_Bool)isMiniInAppViewEnableWithRemoteClientVersion:(unsigned int)arg1 remoteDevice:(id)arg2;
+ (_Bool)shouldShowSystemLockToastWithRemoteClientVersion:(unsigned int)arg1 remoteDevice:(id)arg2;
+ (_Bool)isEnableWithRemoteClientVersion:(unsigned int)arg1 remoteDevice:(id)arg2;
+ (_Bool)shouldUpdateDeviceAngleDegree;
+ (_Bool)isEnable;
+ (int)flagWithOrientation:(long long)arg1 isFrontCamera:(_Bool)arg2;
- (void).cxx_destruct;
@property(retain, nonatomic) CMMotionManager *motion; // @synthesize motion=_motion;
@property(nonatomic) _Bool isSystemLockActived; // @synthesize isSystemLockActived=_isSystemLockActived;
@property(nonatomic) long long motionOrientation; // @synthesize motionOrientation=_motionOrientation;
@property(nonatomic) long long deviceOrientation; // @synthesize deviceOrientation=_deviceOrientation;
@property(nonatomic) double deviceAngleDegree; // @synthesize deviceAngleDegree=_deviceAngleDegree;
- (void)didChangeRotation:(id)arg1;
- (void)onServiceEnterForeground;
- (void)onServiceEnterBackground;
- (void)dealloc;
- (id)init;
- (void)close;
- (void)open;
@property(readonly, nonatomic) _Bool isMotionActived;
- (void)updateDeviceOrientation:(long long)arg1;
- (void)updateDeviceAngleDegree:(double)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

