//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WCTTableCoding-Protocol.h"

@class NSData, NSString;

@interface WAABTestPermissionInfo : NSObject <WCTTableCoding>
{
    unsigned int _appType;
    unsigned int _versionType;
    NSString *_appID;
    NSData *_control_bytes;
}

+ (void)__wcdb_column_constraint_4:(void *)arg1;
+ (id)swift_versionType;
+ (const void *)__wcdb_synthesize_3:(void *)arg1;
+ (const void *)versionType;
+ (id)swift_appType;
+ (const void *)__wcdb_synthesize_2:(void *)arg1;
+ (const void *)appType;
+ (id)swift_control_bytes;
+ (const void *)__wcdb_synthesize_1:(void *)arg1;
+ (const void *)control_bytes;
+ (id)swift_appID;
+ (const void *)__wcdb_synthesize_0:(void *)arg1;
+ (const void *)appID;
+ (id)__wcdbtyper;
+ (id)allBridgeProperties;
+ (const void *)allProperties;
+ (const void *)objectRelationalMapping;
- (void).cxx_destruct;
@property(nonatomic) unsigned int versionType; // @synthesize versionType=_versionType;
@property(nonatomic) unsigned int appType; // @synthesize appType=_appType;
@property(retain, nonatomic) NSData *control_bytes; // @synthesize control_bytes=_control_bytes;
@property(retain, nonatomic) NSString *appID; // @synthesize appID=_appID;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(nonatomic) _Bool isAutoIncrement;
@property(nonatomic) long long lastInsertedRowID;
@property(readonly) Class superclass;

@end

