//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAJSContextPluginBase.h"

#import "IWAJSContextPlugin_AudioPlayer-Protocol.h"
#import "WCAudioModuleDelegate-Protocol.h"
#import "WMPFAudioAPIProtocol-Protocol.h"
#import "wxAudioOutputDelegate-Protocol.h"
#import "wxAudioStateDelegate-Protocol.h"

@class NSMutableDictionary, NSMutableSet, NSObject, NSString, WAAppTask, WXAudioNative;
@protocol OS_dispatch_queue;

@interface WAJSContextPlugin_WxAudioPlayer : WAJSContextPluginBase <WMPFAudioAPIProtocol, wxAudioOutputDelegate, WCAudioModuleDelegate, IWAJSContextPlugin_AudioPlayer, wxAudioStateDelegate>
{
    _Bool _isNeedResumeWXMusic;
    _Bool _obeyMuteSwitch;
    _Bool _mixWithOthers;
    _Bool _speakerOn;
    _Bool _useWXAUDIO;
    _Bool _isAudioModuleActiveNow;
    _Bool _bInterruptNow;
    _Bool _bInterruptByInnerApp;
    _Bool _bInterruptBySystem;
    WXAudioNative *_wxaudionative;
    NSObject<OS_dispatch_queue> *_backgroundQueue;
    NSMutableDictionary *_playBackDelegates;
    NSMutableSet *_playingAudioEngineSet;
}

- (void).cxx_destruct;
@property _Bool bInterruptBySystem; // @synthesize bInterruptBySystem=_bInterruptBySystem;
@property _Bool bInterruptByInnerApp; // @synthesize bInterruptByInnerApp=_bInterruptByInnerApp;
@property _Bool bInterruptNow; // @synthesize bInterruptNow=_bInterruptNow;
@property(retain, nonatomic) NSMutableSet *playingAudioEngineSet; // @synthesize playingAudioEngineSet=_playingAudioEngineSet;
@property _Bool isAudioModuleActiveNow; // @synthesize isAudioModuleActiveNow=_isAudioModuleActiveNow;
@property(retain, nonatomic) NSMutableDictionary *playBackDelegates; // @synthesize playBackDelegates=_playBackDelegates;
@property(nonatomic) _Bool useWXAUDIO; // @synthesize useWXAUDIO=_useWXAUDIO;
@property(nonatomic) _Bool speakerOn; // @synthesize speakerOn=_speakerOn;
@property(nonatomic) _Bool mixWithOthers; // @synthesize mixWithOthers=_mixWithOthers;
@property(nonatomic) _Bool obeyMuteSwitch; // @synthesize obeyMuteSwitch=_obeyMuteSwitch;
@property(nonatomic) _Bool isNeedResumeWXMusic; // @synthesize isNeedResumeWXMusic=_isNeedResumeWXMusic;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *backgroundQueue; // @synthesize backgroundQueue=_backgroundQueue;
@property(readonly, nonatomic) WXAudioNative *wxaudionative; // @synthesize wxaudionative=_wxaudionative;
- (void)checkIfSendInterruptionEvent;
- (void)setJSContextOwner:(id)arg1;
- (void)innerAppAudioInterruptionEnd;
- (void)innerAppAudioInterruptionBegan;
- (void)audioSessionInterruptionEnd;
- (void)audioSessionInterruptionBegan;
- (id)getIdentifier;
- (void)setActiveAsync:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (id)mixList;
- (id)mixListForAudioModule:(id)arg1;
- (void)audioModuleInterruptionEnd:(id)arg1 param:(id)arg2;
- (void)audioModuleInterruptionBegin:(id)arg1 param:(id)arg2;
- (void)onWXAudioState:(int)arg1 audioId:(unsigned long long)arg2;
- (void)canPlayNowAndAutoActive:(unsigned long long)arg1 block:(CDUnknownBlockType)arg2;
- (_Bool)shouldForceUseBuiltinMic;
- (void)onPcmOutput:(char *)arg1 size:(unsigned int)arg2 channels:(unsigned int)arg3 samplerate:(unsigned int)arg4 fmt:(int)arg5;
- (void)setAudioSessionByWeAppEnterBackground;
- (void)applicationDidBecomeActive;
- (void)applicationWillResignActive;
- (void)resumeMusicIfNeed:(_Bool)arg1;
- (_Bool)handleEvent:(long long)arg1 userInfo:(id)arg2;
- (_Bool)existPlayerWaiting;
- (_Bool)existPlayerPlaying;
- (void)forcePauseAllPlayer;
- (void)forceResumeAllPlayer;
- (void)activeAudioSession;
- (void)removeObserver;
- (void)addObserver;
@property(readonly, nonatomic) WAAppTask *task;
@property(readonly, nonatomic) _Bool isGameApp;
- (void)setPlayBackDelegate:(unsigned int)arg1 delegate:(id)arg2;
- (void)setInnerAudioSession:(_Bool)arg1 mixWithOthers:(_Bool)arg2 speakerOn:(_Bool)arg3;
- (_Bool)isPlayingAudio;
- (id)localPathByAudioData:(id)arg1 pathExtension:(id)arg2;
- (id)audioCacheDataPathForSrc:(id)arg1;
- (id)audioTmpPathByfileName:(id)arg1;
- (id)audioTmpRootPath;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

