//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAJSEventHandler_BaseEvent.h"

@interface WAJSEventHandler_operateSmCryptoSensitive : WAJSEventHandler_BaseEvent
{
}

- (void)sm4DecryptCTR:(id)arg1;
- (void)sm4EncryptCTR:(id)arg1;
- (void)sm4DecryptGCM:(id)arg1;
- (void)sm4EncryptGCM:(id)arg1;
- (void)sm4DecryptCBC:(id)arg1;
- (void)sm4EncryptCBC:(id)arg1;
- (void)sm3Hmac:(id)arg1;
- (void)sm2Sign:(id)arg1;
- (void)sm2Decrypt:(id)arg1;
- (void)sm2GenPublicKey:(id)arg1;
- (void)sm2GenKeyPair;
- (void)handleJSEvent:(id)arg1;

@end

