//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

@class NSString;

@interface WASilentOpenCheckInfo : MMObject
{
    unsigned int _beginTimeStamp;
    unsigned int _cacheSeconds;
    NSString *_appid;
    NSString *_username;
    unsigned long long _ret;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned int cacheSeconds; // @synthesize cacheSeconds=_cacheSeconds;
@property(nonatomic) unsigned int beginTimeStamp; // @synthesize beginTimeStamp=_beginTimeStamp;
@property(nonatomic) unsigned long long ret; // @synthesize ret=_ret;
@property(copy, nonatomic) NSString *username; // @synthesize username=_username;
@property(copy, nonatomic) NSString *appid; // @synthesize appid=_appid;

@end

