//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMRootService.h"

#import "MMServiceProtocol-Protocol.h"

@class AVPlayer, MPVolumeView, NSMutableArray, NSString;

@interface WATemplateAudioPlayer : MMRootService <MMServiceProtocol>
{
    float _m_lastVolume;
    NSMutableArray *_queue;
    AVPlayer *_audioPlayer;
    MPVolumeView *_m_privateVoulmeView;
}

- (void).cxx_destruct;
@property(nonatomic) float m_lastVolume; // @synthesize m_lastVolume=_m_lastVolume;
@property(retain, nonatomic) MPVolumeView *m_privateVoulmeView; // @synthesize m_privateVoulmeView=_m_privateVoulmeView;
@property(retain, nonatomic) AVPlayer *audioPlayer; // @synthesize audioPlayer=_audioPlayer;
@property(retain, nonatomic) NSMutableArray *queue; // @synthesize queue=_queue;
- (void)resumeLastVolumn;
- (void)setSystemVolume:(float)arg1;
- (void)forceSetSystemVolume;
- (void)removeVolumeView;
- (void)forceSetVolumeView;
@property(readonly, nonatomic) _Bool isPlaying;
- (_Bool)playNextIfNeed;
- (void)playFinished;
- (void)stop;
- (void)play:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

