//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCAdvertiseOperationLogicBase.h"

@class UIView;

@interface WCAdSocialLikeCheerPlayerLogic : WCAdvertiseOperationLogicBase
{
    _Bool _attractingViewPlayed;
    _Bool _attractingViewErrorReported;
    UIView *_playerViewCache;
    UIView *_attractingViewCache;
    UIView *_attractingIconCache;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool attractingViewErrorReported; // @synthesize attractingViewErrorReported=_attractingViewErrorReported;
@property(retain, nonatomic) UIView *attractingIconCache; // @synthesize attractingIconCache=_attractingIconCache;
@property(retain, nonatomic) UIView *attractingViewCache; // @synthesize attractingViewCache=_attractingViewCache;
@property(nonatomic) _Bool attractingViewPlayed; // @synthesize attractingViewPlayed=_attractingViewPlayed;
@property(retain, nonatomic) UIView *playerViewCache; // @synthesize playerViewCache=_playerViewCache;

@end

