//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIView.h"

#import "PAGViewListener-Protocol.h"

@class NSString, PAGView, UIView, WCAdSocialLikeCheerPlayerLogic, WCAdSocialLikeInfo, WCDataItem;
@protocol WCAdSocialLikeCheerPlayerViewDelegate;

@interface WCAdSocialLikeCheerPlayerView : MMUIView <PAGViewListener>
{
    _Bool _bTimelineScene;
    id <WCAdSocialLikeCheerPlayerViewDelegate> _delegate;
    WCAdSocialLikeInfo *_adSocialLikeInfo;
    WCDataItem *_dataItem;
    PAGView *_cheerPlayer;
    UIView *_cheerPlayerContainer;
    WCAdSocialLikeCheerPlayerLogic *_cheerPlayerLogic;
    PAGView *_attractingPlayer;
    struct CGRect _likeBottomFrame;
    struct CGRect _referenceFrame;
}

- (void).cxx_destruct;
@property(retain, nonatomic) PAGView *attractingPlayer; // @synthesize attractingPlayer=_attractingPlayer;
@property(retain, nonatomic) WCAdSocialLikeCheerPlayerLogic *cheerPlayerLogic; // @synthesize cheerPlayerLogic=_cheerPlayerLogic;
@property(retain, nonatomic) UIView *cheerPlayerContainer; // @synthesize cheerPlayerContainer=_cheerPlayerContainer;
@property(retain, nonatomic) PAGView *cheerPlayer; // @synthesize cheerPlayer=_cheerPlayer;
@property(nonatomic) struct CGRect referenceFrame; // @synthesize referenceFrame=_referenceFrame;
@property(nonatomic) struct CGRect likeBottomFrame; // @synthesize likeBottomFrame=_likeBottomFrame;
@property(nonatomic) _Bool bTimelineScene; // @synthesize bTimelineScene=_bTimelineScene;
@property(retain, nonatomic) WCDataItem *dataItem; // @synthesize dataItem=_dataItem;
@property(retain, nonatomic) WCAdSocialLikeInfo *adSocialLikeInfo; // @synthesize adSocialLikeInfo=_adSocialLikeInfo;
@property(nonatomic) __weak id <WCAdSocialLikeCheerPlayerViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)reportAttractingAnimationPlayedWithErrorCode:(int)arg1;
- (void)onAnimationCancel:(id)arg1;
- (void)onAnimationEnd:(id)arg1;
- (void)onAnimationStart:(id)arg1;
- (void)playAttractingIconAnimation:(_Bool)arg1 uponLikeView:(id)arg2;
- (void)cleanUpAttractingIconPlayer;
- (id)fetchAttractingIconPlayer;
- (void)generateAttractingIconPlayer;
- (id)fetchAttractingIconPAGFile;
- (void)hideAttractingView:(_Bool)arg1;
- (void)playAttractingAnimation;
- (void)tryToResumeAttractingPlayer;
- (void)updateAttractingPlayerFrame;
- (void)configAttractingPlayer;
- (void)cleanUpAttractingPlayer;
- (_Bool)generateAttractingPlayer;
- (id)fetchAttractingPAGFile;
- (id)fetchPAGFilePath;
- (void)resumeOrCreatePlayerView;
- (void)createPlayerView;
- (void)tryResumePlayerViewFromCache;
- (struct CGRect)calcPlayerFrameWithPagWidth:(double)arg1 pagHeight:(double)arg2 rangeFrame:(struct CGRect)arg3 offsetY:(double)arg4;
- (_Bool)isPlaying;
- (void)stop;
- (void)play;
- (void)setFrame:(struct CGRect)arg1 likeBottomFrame:(struct CGRect)arg2 referenceFrame:(struct CGRect)arg3;
- (id)initWithFrame:(struct CGRect)arg1 adSocialLikeInfo:(id)arg2 dataItem:(id)arg3 bTimelineScene:(_Bool)arg4 likeBottomFrame:(struct CGRect)arg5 referenceFrame:(struct CGRect)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

