//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WCTTableCoding-Protocol.h"

@class NSString;

@interface WCBackupRecoverInfo : NSObject <WCTTableCoding>
{
    NSString *_sessionName;
    long long _startTime;
    long long _endTime;
}

+ (void)__wcdb_column_constraint_8:(void *)arg1;
+ (id)swift_endTime;
+ (const void *)__wcdb_synthesize_7:(void *)arg1;
+ (const void *)endTime;
+ (id)swift_startTime;
+ (const void *)__wcdb_synthesize_6:(void *)arg1;
+ (const void *)startTime;
+ (id)swift_sessionName;
+ (const void *)__wcdb_synthesize_5:(void *)arg1;
+ (const void *)sessionName;
+ (id)__wcdbtyper;
+ (id)allBridgeProperties;
+ (const void *)allProperties;
+ (const void *)objectRelationalMapping;
- (void).cxx_destruct;
@property(nonatomic) long long endTime; // @synthesize endTime=_endTime;
@property(nonatomic) long long startTime; // @synthesize startTime=_startTime;
@property(retain, nonatomic) NSString *sessionName; // @synthesize sessionName=_sessionName;
@property(readonly, copy) NSString *description;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(nonatomic) _Bool isAutoIncrement;
@property(nonatomic) long long lastInsertedRowID;
@property(readonly) Class superclass;

@end

