//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

@class GetWecoinPriceListResponse, NSString;
@protocol MMFinderLivePayMgrExt, MMPageSheetProvider;

@interface WCCoinBuyCoinParameter : MMObject
{
    _Bool _panelAlwaysDarkMode;
    _Bool _shouldStartNewSession;
    int _scene;
    unsigned int _diffWecoinCount;
    id <MMPageSheetProvider> _pageSheetProvider;
    unsigned long long _businessId;
    unsigned long long _panelShowType;
    NSString *_directBuyProductId;
    GetWecoinPriceListResponse *_priceListResponse;
    id _customData;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool shouldStartNewSession; // @synthesize shouldStartNewSession=_shouldStartNewSession;
@property(retain, nonatomic) id customData; // @synthesize customData=_customData;
@property(nonatomic) unsigned int diffWecoinCount; // @synthesize diffWecoinCount=_diffWecoinCount;
@property(retain, nonatomic) GetWecoinPriceListResponse *priceListResponse; // @synthesize priceListResponse=_priceListResponse;
@property(copy, nonatomic) NSString *directBuyProductId; // @synthesize directBuyProductId=_directBuyProductId;
@property(nonatomic) unsigned long long panelShowType; // @synthesize panelShowType=_panelShowType;
@property(nonatomic) int scene; // @synthesize scene=_scene;
@property(nonatomic) unsigned long long businessId; // @synthesize businessId=_businessId;
@property(nonatomic) __weak id <MMPageSheetProvider> pageSheetProvider; // @synthesize pageSheetProvider=_pageSheetProvider;
@property(nonatomic) _Bool panelAlwaysDarkMode; // @synthesize panelAlwaysDarkMode=_panelAlwaysDarkMode;
- (id)init;
@property(nonatomic) __weak id <MMFinderLivePayMgrExt> payLogicOberver;

@end

