//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, UIButton, UILabel;

@interface WCCommentListTipsView : UIView
{
    CDUnknownBlockType _clickBlock;
    NSString *_tips;
    UILabel *_tipsLabel;
    UIButton *_clickButton;
}

+ (double)heightForTips:(id)arg1 width:(double)arg2;
- (void).cxx_destruct;
@property(retain, nonatomic) UIButton *clickButton; // @synthesize clickButton=_clickButton;
@property(retain, nonatomic) UILabel *tipsLabel; // @synthesize tipsLabel=_tipsLabel;
@property(retain, nonatomic) NSString *tips; // @synthesize tips=_tips;
@property(copy, nonatomic) CDUnknownBlockType clickBlock; // @synthesize clickBlock=_clickBlock;
- (void)onClickButton;
- (void)layoutSubviews;
- (id)createMaskShapeLayer;
- (void)initClickButton;
- (void)initTipsLabel;
- (void)initBackgroundView;
- (void)initView;
- (id)initWithFrame:(struct CGRect)arg1 title:(id)arg2;

@end

