//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "PBCoding-Protocol.h"

@class NSString, UIColor;

@interface WCFinderProfileMemberShipInfo : NSObject <PBCoding>
{
    NSString *_title;
    NSString *_summary;
    NSString *_iconName;
    UIColor *_iconColor;
    unsigned long long _memberShipStatus;
    unsigned long long _visitorStatus;
}

+ (id)formatIconColor:(unsigned long long)arg1;
+ (id)formatIconName:(unsigned long long)arg1;
+ (id)formatSummaryTitle:(id)arg1;
+ (id)fromMemberShipResponse:(id)arg1;
+ (void)initialize;
+ (void)PBArrayAdd_visitorStatus;
+ (void)PBArrayAdd_memberShipStatus;
+ (void)PBArrayAdd_iconName;
+ (void)PBArrayAdd_summary;
+ (void)PBArrayAdd_title;
- (void).cxx_destruct;
@property(nonatomic) unsigned long long visitorStatus; // @synthesize visitorStatus=_visitorStatus;
@property(nonatomic) unsigned long long memberShipStatus; // @synthesize memberShipStatus=_memberShipStatus;
@property(retain, nonatomic) UIColor *iconColor; // @synthesize iconColor=_iconColor;
@property(copy, nonatomic) NSString *iconName; // @synthesize iconName=_iconName;
@property(copy, nonatomic) NSString *summary; // @synthesize summary=_summary;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (_Bool)isEqualToMemberShipInfo:(id)arg1;
- (id)getPBPropertyTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

