//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WCFinderCacheBaseProtocol-Protocol.h"

@class NSMutableDictionary, NSRecursiveLock, NSString, WCFinderDoublyLinkedList;
@protocol WCFinderCacheDelegate;

@interface WCFinderLFUCache : NSObject <WCFinderCacheBaseProtocol>
{
    unsigned long long _costLimit;
    unsigned long long _countLimit;
    id <WCFinderCacheDelegate> _delegate;
    long long _strategy;
    NSString *_name;
    unsigned long long _totalCount;
    unsigned long long _totalCost;
    WCFinderDoublyLinkedList *_freqNodeList;
    NSMutableDictionary *_nodeDict;
    NSRecursiveLock *_lock;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSRecursiveLock *lock; // @synthesize lock=_lock;
@property(retain, nonatomic) NSMutableDictionary *nodeDict; // @synthesize nodeDict=_nodeDict;
@property(retain, nonatomic) WCFinderDoublyLinkedList *freqNodeList; // @synthesize freqNodeList=_freqNodeList;
@property(nonatomic) unsigned long long totalCost; // @synthesize totalCost=_totalCost;
@property(nonatomic) unsigned long long totalCount; // @synthesize totalCount=_totalCount;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) long long strategy; // @synthesize strategy=_strategy;
@property(nonatomic) __weak id <WCFinderCacheDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) unsigned long long countLimit; // @synthesize countLimit=_countLimit;
@property(nonatomic) unsigned long long costLimit; // @synthesize costLimit=_costLimit;
@property(readonly, copy) NSString *description;
- (void)trimToCost:(unsigned long long)arg1;
- (void)trimToCount:(unsigned long long)arg1;
- (id)objectForKey:(id)arg1;
- (_Bool)containsObjectForKey:(id)arg1;
- (void)removeAllObjects;
- (void)safeRemoveObjectForKey:(id)arg1;
- (void)safeSetObject:(id)arg1 forKey:(id)arg2 withCost:(unsigned long long)arg3;
- (void)safeSetObject:(id)arg1 forKey:(id)arg2;
- (id)initWithName:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

