//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class WCEditImageSafeAreaScrollView, WCFinderCoverPreviewView;

@interface WCFinderCoverBackGroundView : UIView
{
    WCFinderCoverPreviewView *_previewView;
    WCEditImageSafeAreaScrollView *_eIScrollView;
}

- (void).cxx_destruct;
@property(nonatomic) __weak WCEditImageSafeAreaScrollView *eIScrollView; // @synthesize eIScrollView=_eIScrollView;
@property(nonatomic) __weak WCFinderCoverPreviewView *previewView; // @synthesize previewView=_previewView;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;

@end

