//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "WCFinderLBSCardContentViewDelegate-Protocol.h"

@class FinderJumpInfo_Style, FinderLocation, NSString, WCFinderJumpInfo, WCFinderLBSCardContentView;
@protocol WCFinderJumpInfoLBSCardViewDelegate;

@interface WCFinderJumpInfoLBSCardView : UIView <WCFinderLBSCardContentViewDelegate>
{
    id <WCFinderJumpInfoLBSCardViewDelegate> _delegate;
    WCFinderLBSCardContentView *_cardContent;
    FinderJumpInfo_Style *_style;
    long long _showPosition;
    WCFinderJumpInfo *_jumpInfo;
    FinderLocation *_locationInfo;
}

- (void).cxx_destruct;
@property(retain, nonatomic) FinderLocation *locationInfo; // @synthesize locationInfo=_locationInfo;
@property(retain, nonatomic) WCFinderJumpInfo *jumpInfo; // @synthesize jumpInfo=_jumpInfo;
@property(nonatomic) long long showPosition; // @synthesize showPosition=_showPosition;
@property(retain, nonatomic) FinderJumpInfo_Style *style; // @synthesize style=_style;
@property(retain, nonatomic) WCFinderLBSCardContentView *cardContent; // @synthesize cardContent=_cardContent;
@property(nonatomic) __weak id <WCFinderJumpInfoLBSCardViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)lbsCardSetupFavButtonReport:(id)arg1;
- (void)lbsCardLayoutHeightChanged;
- (void)lbsCardDidClickCard;
- (void)lbsCardChangeFavState:(_Bool)arg1;
- (void)layoutSubviews;
- (void)updateWithJumpInfo:(id)arg1 style:(id)arg2;
- (void)updateWithJumpInfo:(id)arg1 showPosition:(long long)arg2;
- (void)setupSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

