//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WCFinderMembershipFirstPageCacheInfo : NSObject
{
    NSString *_tid;
    NSString *_username;
    unsigned long long _pageType;
    unsigned long long _cacheIndex;
}

+ (void)__wcdb_index_7:(void *)arg1;
+ (void)__wcdb_index_6:(void *)arg1;
+ (void)__wcdb_table_constraint_5:(void *)arg1;
+ (void)__wcdb_table_constraint_4:(void *)arg1;
+ (id)swift_cacheIndex;
+ (const void *)__wcdb_synthesize_3:(void *)arg1;
+ (const void *)cacheIndex;
+ (id)swift_pageType;
+ (const void *)__wcdb_synthesize_2:(void *)arg1;
+ (const void *)pageType;
+ (id)swift_username;
+ (const void *)__wcdb_synthesize_1:(void *)arg1;
+ (const void *)username;
+ (id)swift_tid;
+ (const void *)__wcdb_synthesize_0:(void *)arg1;
+ (const void *)tid;
+ (id)__wcdbtyper;
+ (id)allBridgeProperties;
+ (const void *)allProperties;
+ (const void *)objectRelationalMapping;
- (void).cxx_destruct;
@property(nonatomic) unsigned long long cacheIndex; // @synthesize cacheIndex=_cacheIndex;
@property(nonatomic) unsigned long long pageType; // @synthesize pageType=_pageType;
@property(copy, nonatomic) NSString *username; // @synthesize username=_username;
@property(copy, nonatomic) NSString *tid; // @synthesize tid=_tid;

@end

