//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface WCFinderHSVModel : NSObject
{
    unsigned long long _hValue;
    unsigned long long _sValue;
    unsigned long long _vValue;
}

@property(nonatomic) unsigned long long vValue; // @synthesize vValue=_vValue;
@property(nonatomic) unsigned long long sValue; // @synthesize sValue=_sValue;
@property(nonatomic) unsigned long long hValue; // @synthesize hValue=_hValue;

@end

