//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSMutableArray, NSMutableSet, NSString;
@protocol WCFinderMemberShipPreviewListViewModelDelegate;

@interface WCFinderMemberShipPreviewListViewModel : NSObject
{
    _Bool _continueFlag;
    _Bool _isFetchingData;
    int _feedType;
    id <WCFinderMemberShipPreviewListViewModelDelegate> _delegate;
    unsigned long long _state;
    NSMutableArray *_contentVMS;
    NSString *_finderMemberTicket;
    NSString *_finderUsername;
    NSData *_lastBuffer;
    NSMutableSet *_tidContainSet;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableSet *tidContainSet; // @synthesize tidContainSet=_tidContainSet;
@property(nonatomic) _Bool isFetchingData; // @synthesize isFetchingData=_isFetchingData;
@property(nonatomic) _Bool continueFlag; // @synthesize continueFlag=_continueFlag;
@property(retain, nonatomic) NSData *lastBuffer; // @synthesize lastBuffer=_lastBuffer;
@property(nonatomic) int feedType; // @synthesize feedType=_feedType;
@property(copy, nonatomic) NSString *finderUsername; // @synthesize finderUsername=_finderUsername;
@property(copy, nonatomic) NSString *finderMemberTicket; // @synthesize finderMemberTicket=_finderMemberTicket;
@property(retain, nonatomic) NSMutableArray *contentVMS; // @synthesize contentVMS=_contentVMS;
@property(nonatomic) unsigned long long state; // @synthesize state=_state;
@property(nonatomic) __weak id <WCFinderMemberShipPreviewListViewModelDelegate> delegate; // @synthesize delegate=_delegate;
- (unsigned long long)feedViewControllerPageId;
- (unsigned long long)feedViewControllerScene;
- (void)onGetDataArray:(id)arg1 pullFromTop:(_Bool)arg2 lastBuff:(id)arg3 continueFlag:(_Bool)arg4;
- (void)requestDataWithPullType:(unsigned long long)arg1;
- (void)requestNextPageData;
- (void)requestFirstPageData;
- (void)getLocalFirstPageData;
- (void)updateState;
- (id)initWithFinderMemberTicket:(id)arg1 finderUsername:(id)arg2 feedType:(int)arg3;

@end

