//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WCTTableCoding-Protocol.h"

@class NSString, WCFinderVideoPlayInfoImagePathArray;

@interface WCFinderVideoPlayInfo : NSObject <WCTTableCoding>
{
    NSString *_tid;
    unsigned long long _playingTimeRecently;
    NSString *_tempPath;
    NSString *_mediaPath;
    WCFinderVideoPlayInfoImagePathArray *_imagePathArray;
    double _playbackTime;
    NSString *_contextID;
}

+ (void)__wcdb_index_8:(void *)arg1;
+ (void)__wcdb_column_constraint_7:(void *)arg1;
+ (id)swift_contextID;
+ (const void *)__wcdb_synthesize_6:(void *)arg1;
+ (const void *)contextID;
+ (id)swift_playbackTime;
+ (const void *)__wcdb_synthesize_5:(void *)arg1;
+ (const void *)playbackTime;
+ (id)swift_imagePathArray;
+ (const void *)__wcdb_synthesize_4:(void *)arg1;
+ (const void *)imagePathArray;
+ (id)swift_mediaPath;
+ (const void *)__wcdb_synthesize_3:(void *)arg1;
+ (const void *)mediaPath;
+ (id)swift_tempPath;
+ (const void *)__wcdb_synthesize_2:(void *)arg1;
+ (const void *)tempPath;
+ (id)swift_playingTimeRecently;
+ (const void *)__wcdb_synthesize_1:(void *)arg1;
+ (const void *)playingTimeRecently;
+ (id)swift_tid;
+ (const void *)__wcdb_synthesize_0:(void *)arg1;
+ (const void *)tid;
+ (id)__wcdbtyper;
+ (id)allBridgeProperties;
+ (const void *)allProperties;
+ (const void *)objectRelationalMapping;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *contextID; // @synthesize contextID=_contextID;
@property(nonatomic) double playbackTime; // @synthesize playbackTime=_playbackTime;
@property(retain, nonatomic) WCFinderVideoPlayInfoImagePathArray *imagePathArray; // @synthesize imagePathArray=_imagePathArray;
@property(retain, nonatomic) NSString *mediaPath; // @synthesize mediaPath=_mediaPath;
@property(retain, nonatomic) NSString *tempPath; // @synthesize tempPath=_tempPath;
@property(nonatomic) unsigned long long playingTimeRecently; // @synthesize playingTimeRecently=_playingTimeRecently;
@property(retain, nonatomic) NSString *tid; // @synthesize tid=_tid;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(nonatomic) _Bool isAutoIncrement;
@property(nonatomic) long long lastInsertedRowID;
@property(readonly) Class superclass;

@end

