//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMBaseSessionTableViewCell.h"

#import "WCFinderMsgSessionNicknameTailViewDelegate-Protocol.h"

@class NSString, WCFinderMsgSessionCellViewModel, WCFinderMsgSessionNicknameTailView;

@interface WCFinderMsgSessionCell : MMBaseSessionTableViewCell <WCFinderMsgSessionNicknameTailViewDelegate>
{
    WCFinderMsgSessionCellViewModel *_viewModel;
    WCFinderMsgSessionNicknameTailView *_tailView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WCFinderMsgSessionNicknameTailView *tailView; // @synthesize tailView=_tailView;
@property(retain, nonatomic) WCFinderMsgSessionCellViewModel *viewModel; // @synthesize viewModel=_viewModel;
- (void)onTailViewNeedLayout;
- (id)GetNickNameTailView;
- (id)genMessageListTimeStringByUInt:(unsigned int)arg1;
- (void)updateWithSessionCellData:(id)arg1;
- (void)prepareForReuse;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

