//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSMutableDictionary, WCFinderCompleteHandler;

@interface WCFinderJSAPIFeedListBehavior : NSObject
{
    _Bool _allowTopPull;
    _Bool _allowInfiniteTopPull;
    _Bool _reportFeedRead;
    _Bool _feedFocusChangeNotify;
    _Bool _fromSearchTemplate;
    WCFinderCompleteHandler *_compelteHandler;
    CDUnknownBlockType _sendTemplateEvent;
    NSMutableArray *_completeActions;
    NSMutableDictionary *_bckInfo;
}

+ (_Bool)boolValueForKey:(id)arg1 inDict:(id)arg2;
+ (id)behaviorDict:(id)arg1;
+ (id)behaviorWithParams:(id)arg1 event:(id)arg2;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableDictionary *bckInfo; // @synthesize bckInfo=_bckInfo;
@property(retain, nonatomic) NSMutableArray *completeActions; // @synthesize completeActions=_completeActions;
@property(copy, nonatomic) CDUnknownBlockType sendTemplateEvent; // @synthesize sendTemplateEvent=_sendTemplateEvent;
@property(nonatomic) _Bool fromSearchTemplate; // @synthesize fromSearchTemplate=_fromSearchTemplate;
@property(retain, nonatomic) WCFinderCompleteHandler *compelteHandler; // @synthesize compelteHandler=_compelteHandler;
@property(nonatomic) _Bool feedFocusChangeNotify; // @synthesize feedFocusChangeNotify=_feedFocusChangeNotify;
@property(nonatomic) _Bool reportFeedRead; // @synthesize reportFeedRead=_reportFeedRead;
@property(nonatomic) _Bool allowInfiniteTopPull; // @synthesize allowInfiniteTopPull=_allowInfiniteTopPull;
@property(nonatomic) _Bool allowTopPull; // @synthesize allowTopPull=_allowTopPull;
- (void)updateBckInfo:(CDUnknownBlockType)arg1;
- (void)onComplete;
- (void)addCompleteAction:(CDUnknownBlockType)arg1;
- (id)createPlugin;
- (void)notifyTemplate:(id)arg1 params:(id)arg2;
- (_Bool)delayCallResultCallback;

@end

