//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "ILinkEventExt-Protocol.h"
#import "MMFinderLiveLotteryGetPrizeMethodOperationViewDelegate-Protocol.h"
#import "MMFinderLiveLotteryMethodOperationViewDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"
#import "WCActionSheetDelegate-Protocol.h"
#import "WCFinderLiveStartLotteryGoodViewDelegate-Protocol.h"
#import "WCFinderLiveStartLotteryItemViewDelegate-Protocol.h"
#import "WCFinderUserPrepareCgiDelegate-Protocol.h"

@class FinderJumpInfo_LiteApp, MMFinderLiveLotteryCommentInputView, MMFinderLiveLotteryCommentInputViewController, MMFinderLiveLotteryGetPrizeMethodOperationView, MMFinderLiveLotteryMethodOperationView, MMFinderLiveTask, MMUIButton, MMUILabel, NSMutableArray, NSString, RichTextView, UIButton, UIScrollView, UIView, WCFinderLiveStartLotteryGoodView, WCFinderLiveStartLotteryItemView, WCFinderLiveStartLotteryProductInfo, WCFinderLiveStartSelectLotteryTypeButton;
@protocol WCFinderLiveStartLotteryViewControllerDelegate;

@interface WCFinderLiveStartLotteryViewController : MMUIViewController <WCActionSheetDelegate, WCFinderLiveStartLotteryItemViewDelegate, MMFinderLiveLotteryMethodOperationViewDelegate, WCFinderUserPrepareCgiDelegate, MMFinderLiveLotteryGetPrizeMethodOperationViewDelegate, ILinkEventExt, UIScrollViewDelegate, WCFinderLiveStartLotteryGoodViewDelegate>
{
    _Bool _showLottteryDurationTipLable;
    _Bool _sOpening;
    _Bool _enterBackground;
    _Bool _isKeyBoardShow;
    _Bool _hasCreateLotteryPanel;
    _Bool _isAgreementChecked;
    int _attendType;
    id <WCFinderLiveStartLotteryViewControllerDelegate> _delegate;
    MMFinderLiveTask *_liveTask;
    MMUILabel *_lottteryDurationTipLable;
    UIButton *_createLotteryButton;
    MMFinderLiveLotteryCommentInputViewController *_commentInputViewController;
    double _keyboardHeight;
    MMFinderLiveLotteryMethodOperationView *_lottertMethodOperationView;
    NSMutableArray *_lotteryDataArray;
    WCFinderLiveStartLotteryItemView *_lotteryMethodSelectItemView;
    WCFinderLiveStartLotteryItemView *_lotteryMethodSelectContentItemView;
    WCFinderLiveStartLotteryItemView *_lotteryDurationInputItemView;
    WCFinderLiveStartLotteryItemView *_lotteryWinnerCntInputItemView;
    WCFinderLiveStartLotteryItemView *_lotteryDescriptionInputItemView;
    WCFinderLiveStartLotteryItemView *_lotteryGetPrizeMethodInputItemView;
    WCFinderLiveStartLotteryItemView *_lotteryGetPrizeMethodContentItemView;
    WCFinderLiveStartLotteryItemView *_lotteryParticipateExcludeSwitchItemView;
    UIView *_contentView;
    MMFinderLiveLotteryGetPrizeMethodOperationView *_getPrizeMethodOperationView;
    UIView *_checkBoxView;
    MMUIButton *_agreementCheckbox;
    RichTextView *_agreementText;
    UIScrollView *_contentScrollView;
    FinderJumpInfo_LiteApp *_selectProductsAppInfo;
    NSString *_commentInput;
    long long _lotteryStartType;
    WCFinderLiveStartLotteryProductInfo *_productInfo;
    WCFinderLiveStartSelectLotteryTypeButton *_selectTypeButton;
    unsigned long long _selectLotteryType;
    WCFinderLiveStartLotteryGoodView *_goodView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WCFinderLiveStartLotteryGoodView *goodView; // @synthesize goodView=_goodView;
@property(nonatomic) unsigned long long selectLotteryType; // @synthesize selectLotteryType=_selectLotteryType;
@property(retain, nonatomic) WCFinderLiveStartSelectLotteryTypeButton *selectTypeButton; // @synthesize selectTypeButton=_selectTypeButton;
@property(retain, nonatomic) WCFinderLiveStartLotteryProductInfo *productInfo; // @synthesize productInfo=_productInfo;
@property(nonatomic) long long lotteryStartType; // @synthesize lotteryStartType=_lotteryStartType;
@property(copy, nonatomic) NSString *commentInput; // @synthesize commentInput=_commentInput;
@property(retain, nonatomic) FinderJumpInfo_LiteApp *selectProductsAppInfo; // @synthesize selectProductsAppInfo=_selectProductsAppInfo;
@property(retain, nonatomic) UIScrollView *contentScrollView; // @synthesize contentScrollView=_contentScrollView;
@property(retain, nonatomic) RichTextView *agreementText; // @synthesize agreementText=_agreementText;
@property(retain, nonatomic) MMUIButton *agreementCheckbox; // @synthesize agreementCheckbox=_agreementCheckbox;
@property(retain, nonatomic) UIView *checkBoxView; // @synthesize checkBoxView=_checkBoxView;
@property(nonatomic) _Bool isAgreementChecked; // @synthesize isAgreementChecked=_isAgreementChecked;
@property(nonatomic) _Bool hasCreateLotteryPanel; // @synthesize hasCreateLotteryPanel=_hasCreateLotteryPanel;
@property(retain, nonatomic) MMFinderLiveLotteryGetPrizeMethodOperationView *getPrizeMethodOperationView; // @synthesize getPrizeMethodOperationView=_getPrizeMethodOperationView;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) WCFinderLiveStartLotteryItemView *lotteryParticipateExcludeSwitchItemView; // @synthesize lotteryParticipateExcludeSwitchItemView=_lotteryParticipateExcludeSwitchItemView;
@property(retain, nonatomic) WCFinderLiveStartLotteryItemView *lotteryGetPrizeMethodContentItemView; // @synthesize lotteryGetPrizeMethodContentItemView=_lotteryGetPrizeMethodContentItemView;
@property(retain, nonatomic) WCFinderLiveStartLotteryItemView *lotteryGetPrizeMethodInputItemView; // @synthesize lotteryGetPrizeMethodInputItemView=_lotteryGetPrizeMethodInputItemView;
@property(retain, nonatomic) WCFinderLiveStartLotteryItemView *lotteryDescriptionInputItemView; // @synthesize lotteryDescriptionInputItemView=_lotteryDescriptionInputItemView;
@property(retain, nonatomic) WCFinderLiveStartLotteryItemView *lotteryWinnerCntInputItemView; // @synthesize lotteryWinnerCntInputItemView=_lotteryWinnerCntInputItemView;
@property(retain, nonatomic) WCFinderLiveStartLotteryItemView *lotteryDurationInputItemView; // @synthesize lotteryDurationInputItemView=_lotteryDurationInputItemView;
@property(retain, nonatomic) WCFinderLiveStartLotteryItemView *lotteryMethodSelectContentItemView; // @synthesize lotteryMethodSelectContentItemView=_lotteryMethodSelectContentItemView;
@property(retain, nonatomic) WCFinderLiveStartLotteryItemView *lotteryMethodSelectItemView; // @synthesize lotteryMethodSelectItemView=_lotteryMethodSelectItemView;
@property(retain, nonatomic) NSMutableArray *lotteryDataArray; // @synthesize lotteryDataArray=_lotteryDataArray;
@property(nonatomic) int attendType; // @synthesize attendType=_attendType;
@property(retain, nonatomic) MMFinderLiveLotteryMethodOperationView *lottertMethodOperationView; // @synthesize lottertMethodOperationView=_lottertMethodOperationView;
@property(nonatomic) double keyboardHeight; // @synthesize keyboardHeight=_keyboardHeight;
@property(nonatomic) _Bool isKeyBoardShow; // @synthesize isKeyBoardShow=_isKeyBoardShow;
@property(nonatomic) _Bool enterBackground; // @synthesize enterBackground=_enterBackground;
@property(nonatomic) _Bool sOpening; // @synthesize sOpening=_sOpening;
@property(retain, nonatomic) MMFinderLiveLotteryCommentInputViewController *commentInputViewController; // @synthesize commentInputViewController=_commentInputViewController;
@property(retain, nonatomic) UIButton *createLotteryButton; // @synthesize createLotteryButton=_createLotteryButton;
@property(retain, nonatomic) MMUILabel *lottteryDurationTipLable; // @synthesize lottteryDurationTipLable=_lottteryDurationTipLable;
@property(nonatomic) _Bool showLottteryDurationTipLable; // @synthesize showLottteryDurationTipLable=_showLottteryDurationTipLable;
@property(retain, nonatomic) MMFinderLiveTask *liveTask; // @synthesize liveTask=_liveTask;
@property(nonatomic) __weak id <WCFinderLiveStartLotteryViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)getFirstResponder;
- (_Bool)isSubWidgetsFirstResponder;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)traitCollectionDidChange:(id)arg1;
- (void)applicationWillEnterForeground;
- (void)applicationDidEnterBackground;
- (_Bool)isCommentEnable;
- (void)showAlter:(id)arg1;
- (void)showToastForCreateLotteryWithErrorType:(int)arg1 errorPage:(id)arg2;
- (void)updateAnchorStatusLotterySetting;
- (void)onCreateLotteryButtonClicked:(id)arg1;
- (void)updateSelectedProductInfo:(id)arg1;
- (void)onSwitchModeButtonClicked;
- (void)resetAllData;
- (void)handleSelectLotteryType:(unsigned long long)arg1;
- (void)selectTypeButtonClick;
- (void)onStartLotteryGoodViewTextFieldChanged:(id)arg1;
- (void)onStartLotteryGoodViewChangeGoodClicked:(id)arg1;
- (void)onSaveLotteryButtonClicked:(id)arg1;
- (void)onLotteryButtonClicked:(id)arg1;
- (void)onMoreButtonClicked:(id)arg1;
- (void)onBackButtonClicked:(id)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (int)typeFromObject:(int)arg1;
- (void)updateSelectIndex:(int)arg1;
- (int)getIndexFromSelectAttendType:(int)arg1;
- (id)getAttendTypeSting;
- (void)updateUIWithUserLotterySetting;
- (_Bool)isLikeEnable;
- (_Bool)isFansGroupEnable;
- (unsigned long long)getCellTtype:(int)arg1;
- (_Bool)isCloseGetPrizeMethod;
- (void)lotteryMethodSelect:(id)arg1 indexPath:(id)arg2;
- (void)deleteLotteryClick:(id)arg1 session:(long long)arg2;
- (void)lotteryGetPrizeMethodSelect:(id)arg1 indexPath:(id)arg2;
- (void)onStartLotteryItemViewTextFieldChanged:(id)arg1;
- (void)updateCurrentSelectLotteryType:(int)arg1;
- (void)onStartLotteryItemViewSelectionTypeOnClicked:(id)arg1;
- (_Bool)isLotterySelectModeOpenSwitch;
- (_Bool)isChooseGoodsSelectLotteryType;
- (void)commentInputDidChanged:(id)arg1;
- (void)endEditing;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (_Bool)isShowGetPrizeMethodSpecifiedContent;
- (void)newUpdateCreateLotteryButtonEnableStatus;
- (_Bool)isLiveLotteryPolicyCheckedElsewhere;
- (_Bool)shouldAgreementCheckBoxShown;
- (void)onCheckBoxClicked;
- (void)onLinkClicked:(id)arg1 withRect:(struct CGRect)arg2;
- (void)updateAccessbility;
- (void)layoutCheckBoxView;
- (void)layoutUI;
- (void)layoutCreateLotteryButton;
- (void)updateCreateLotteryButtonStyle;
@property(readonly, nonatomic) MMFinderLiveLotteryCommentInputView *commentInputView;
- (void)updateUIWhenLotteryDuringChangge:(unsigned long long)arg1;
- (void)setupUI;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)viewDidLayoutSubviews;
- (id)getCurrentMainColor;
- (void)viewDidLoad;
- (void)addNotifications;
- (void)dealloc;
- (id)initWithLiveTask:(id)arg1 hasCreateLotteryPanel:(_Bool)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

