//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSMutableArray, NSMutableSet, NSString, WCFinderStreamLocationInfo;
@protocol WCFinderNearbyRelatedViewModelDelegate;

@interface WCFinderNearbyRelatedViewModel : NSObject
{
    _Bool _isEnableContinueFetch;
    _Bool _isFetchingData;
    id <WCFinderNearbyRelatedViewModelDelegate> _delegate;
    NSString *_enterFeedTid;
    unsigned long long _refreshTime;
    NSMutableArray *_allDataItems;
    NSMutableSet *_tidContainSet;
    NSData *_lastBuff;
    NSString *_enterNonceTid;
    unsigned long long _commentScene;
    WCFinderStreamLocationInfo *_locationInfo;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool isFetchingData; // @synthesize isFetchingData=_isFetchingData;
@property(retain, nonatomic) WCFinderStreamLocationInfo *locationInfo; // @synthesize locationInfo=_locationInfo;
@property(nonatomic) unsigned long long commentScene; // @synthesize commentScene=_commentScene;
@property(retain, nonatomic) NSString *enterNonceTid; // @synthesize enterNonceTid=_enterNonceTid;
@property(retain, nonatomic) NSData *lastBuff; // @synthesize lastBuff=_lastBuff;
@property(retain, nonatomic) NSMutableSet *tidContainSet; // @synthesize tidContainSet=_tidContainSet;
@property(nonatomic) _Bool isEnableContinueFetch; // @synthesize isEnableContinueFetch=_isEnableContinueFetch;
@property(retain, nonatomic) NSMutableArray *allDataItems; // @synthesize allDataItems=_allDataItems;
@property(nonatomic) unsigned long long refreshTime; // @synthesize refreshTime=_refreshTime;
@property(retain, nonatomic) NSString *enterFeedTid; // @synthesize enterFeedTid=_enterFeedTid;
@property(nonatomic) __weak id <WCFinderNearbyRelatedViewModelDelegate> delegate; // @synthesize delegate=_delegate;
- (_Bool)deleteDataItemWithIndex:(unsigned long long)arg1 tid:(id)arg2;
- (unsigned long long)feedViewControllerScene;
- (id)contentVMAtIndex:(long long)arg1;
- (id)contentVMWithTid:(id)arg1;
- (long long)contentIndexOfTid:(id)arg1;
- (unsigned long long)dataSourceItemCount;
- (unsigned long long)firstPageRefreshTime;
- (id)transformDataItems:(id)arg1;
- (void)appendFinderContentVM:(id)arg1;
- (void)fetchMoreNearbyRelated;
- (void)fetchRelatedFirstPage;
- (_Bool)isEnableFetchNextPage;
- (void)addContentVM:(id)arg1;
- (id)initWithTid:(id)arg1 nonceID:(id)arg2 isFromSNSPoi:(_Bool)arg3 location:(id)arg4;

@end

