//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCFinderLiveHomePageBaseSectionView.h"

#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegateFlowLayout-Protocol.h"
#import "WCFinderLiveHomePageBannerCellDelegate-Protocol.h"
#import "WCGeneralMonitorDelegate-Protocol.h"

@class NSString, WCFinderLiveHomePageAutoPlayModel;
@protocol WCFinderLiveHomePageBannerSectionViewDelegate;

@interface WCFinderLiveHomePageBannerSectionView : WCFinderLiveHomePageBaseSectionView <UICollectionViewDataSource, UICollectionViewDelegateFlowLayout, WCGeneralMonitorDelegate, WCFinderLiveHomePageBannerCellDelegate>
{
    id <WCFinderLiveHomePageBannerSectionViewDelegate> _delegate;
    WCFinderLiveHomePageAutoPlayModel *_autoPlayModel;
}

+ (double)viewHeightInWidth:(double)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) WCFinderLiveHomePageAutoPlayModel *autoPlayModel; // @synthesize autoPlayModel=_autoPlayModel;
@property(nonatomic) __weak id <WCFinderLiveHomePageBannerSectionViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)onContainerSectionVMHomePageDeleteTid:(id)arg1;
- (void)onContainerSectionVMHomePageResetState;
- (void)onBaseLiveCellForwardAction:(id)arg1;
- (void)clickRecommendUrl:(id)arg1;
- (void)onClickCoverContact:(id)arg1 dataItem:(id)arg2;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)collectionView:(id)arg1 didEndDisplayingCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (id)generateCollectionView;
- (void)autoPlayStart;
- (void)autoPlayStop;
- (void)updateWithVM:(id)arg1;
- (void)prepareForReuse;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

