//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MMUIViewController, NSArray, WCFinderFeedContentVM, WCFinderLandScapeVideoView, WCFinderRefreshTableFooterView;
@protocol WCFinderFeedBaseViewControllerProtocol;

@protocol WCFinderLandScapeVideoViewDelegate <NSObject>
- (MMUIViewController<WCFinderFeedBaseViewControllerProtocol> *)finderLandScapeVideoViewGetCurrentViewController;

@optional
- (NSArray *)finderLandScapeVideoView:(WCFinderLandScapeVideoView *)arg1 actionConfigureWithContentVM:(WCFinderFeedContentVM *)arg2;
- (void)finderLandScapeListFooterDidTriggerRefresh:(WCFinderRefreshTableFooterView *)arg1;
- (_Bool)finderLandScapeListFooteIsEnableTriggerRefreshAtScroll:(WCFinderRefreshTableFooterView *)arg1;
- (void)finderLandScapeVideoView:(WCFinderLandScapeVideoView *)arg1 didSelectRowAtIndex:(long long)arg2;
@end

