//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCFinderBaseCgi.h"

@class NSData, NSMutableArray, WCFinderStreamRequestParams;

@interface WCFinderStreamCGI : WCFinderBaseCgi
{
    _Bool _isCancel;
    CDUnknownBlockType _successful;
    CDUnknownBlockType _failure;
    NSData *_buffer;
    unsigned long long _pullType;
    long long _tabType;
    NSMutableArray *_unreadItems;
    CDUnknownBlockType _cancelBlock;
    unsigned long long _commentscene;
    WCFinderStreamRequestParams *_params;
}

+ (id)convertFinderObjectListToUnreadItems:(id)arg1 tabType:(long long)arg2;
+ (id)getUnreadItemsWithParams:(id)arg1 tabType:(long long)arg2 commentScene:(unsigned long long)arg3;
+ (id)prefetchCacheHashKey:(long long)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) WCFinderStreamRequestParams *params; // @synthesize params=_params;
@property(nonatomic) unsigned long long commentscene; // @synthesize commentscene=_commentscene;
@property(copy, nonatomic) CDUnknownBlockType cancelBlock; // @synthesize cancelBlock=_cancelBlock;
@property(nonatomic) _Bool isCancel; // @synthesize isCancel=_isCancel;
@property(retain, nonatomic) NSMutableArray *unreadItems; // @synthesize unreadItems=_unreadItems;
@property(nonatomic) long long tabType; // @synthesize tabType=_tabType;
@property(nonatomic) unsigned long long pullType; // @synthesize pullType=_pullType;
@property(retain, nonatomic) NSData *buffer; // @synthesize buffer=_buffer;
@property(copy, nonatomic) CDUnknownBlockType failure; // @synthesize failure=_failure;
@property(copy, nonatomic) CDUnknownBlockType successful; // @synthesize successful=_successful;
- (void)prefetchCacheWillBeDropped:(id)arg1;
- (_Bool)hasReddotFinderObject:(id)arg1;
- (id)getStreamRequestTopObjects:(id)arg1 bubbleInfo:(id)arg2;
- (_Bool)isEqualWithRequest:(id)arg1 extraData:(id)arg2;
- (unsigned long long)cacheValidityPeriod;
- (id)prefetchExtraData;
- (id)cachedHashKey;
- (_Bool)isConsumeRequest;
- (_Bool)isPrefetchRequest;
- (id)getRoomStateWithAvgSpeed:(unsigned int)arg1;
- (void)reportCGIFail;
- (void)reportCGIFinishWithDebugMessage:(id)arg1;
- (void)reportCGIStart;
- (_Bool)needADDeviceInfo;
- (void)cancelCGIWithBlock:(CDUnknownBlockType)arg1;
- (void)cancelCGI;
- (void)finderCgiDidFailWithError:(id)arg1 response:(id)arg2;
- (void)didGetResponse:(id)arg1;
- (void)start;
- (void)createRequest;
- (id)initWithPullType:(unsigned long long)arg1 buffer:(id)arg2 tabType:(long long)arg3 commentscene:(unsigned long long)arg4 params:(id)arg5 successBlock:(CDUnknownBlockType)arg6 failureBlock:(CDUnknownBlockType)arg7;

@end

