//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WCTTableCoding-Protocol.h"

@class NSString;

@interface WCFinderRedDotUltraHighPriorityInstance : NSObject <WCTTableCoding>
{
    NSString *_instanceId;
    double _updateTime;
    double _startTime;
    double _expireTime;
}

+ (void)__wcdb_column_constraint_4:(void *)arg1;
+ (id)swift_expireTime;
+ (const void *)__wcdb_synthesize_3:(void *)arg1;
+ (const void *)expireTime;
+ (id)swift_startTime;
+ (const void *)__wcdb_synthesize_2:(void *)arg1;
+ (const void *)startTime;
+ (id)swift_updateTime;
+ (const void *)__wcdb_synthesize_1:(void *)arg1;
+ (const void *)updateTime;
+ (id)swift_instanceId;
+ (const void *)__wcdb_synthesize_0:(void *)arg1;
+ (const void *)instanceId;
+ (id)__wcdbtyper;
+ (id)allBridgeProperties;
+ (const void *)allProperties;
+ (const void *)objectRelationalMapping;
- (void).cxx_destruct;
@property(nonatomic) double expireTime; // @synthesize expireTime=_expireTime;
@property(nonatomic) double startTime; // @synthesize startTime=_startTime;
@property(nonatomic) double updateTime; // @synthesize updateTime=_updateTime;
@property(retain, nonatomic) NSString *instanceId; // @synthesize instanceId=_instanceId;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(nonatomic) _Bool isAutoIncrement;
@property(nonatomic) long long lastInsertedRowID;
@property(readonly) Class superclass;

@end

