//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface WCFinderNavTabTitleViewLayout : NSObject
{
    NSArray *_defines;
    long long _selectedIdx;
    double _expectPadding;
    double _navTabPaddingButton;
}

- (void).cxx_destruct;
@property(nonatomic) double navTabPaddingButton; // @synthesize navTabPaddingButton=_navTabPaddingButton;
@property(nonatomic) double expectPadding; // @synthesize expectPadding=_expectPadding;
@property(nonatomic) long long selectedIdx; // @synthesize selectedIdx=_selectedIdx;
@property(retain, nonatomic) NSArray *defines; // @synthesize defines=_defines;
- (id)init;

@end

