//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCFinderNotifyUnifiedTableViewCell.h"

@class UIImageView;

@interface WCFinderNotifyUnifiedLikeTableViewCell : WCFinderNotifyUnifiedTableViewCell
{
    UIImageView *_likeImageView;
}

+ (double)getHeightWithViewModel:(id)arg1 width:(double)arg2;
+ (_Bool)shouldShowFollowMeLabel;
- (void).cxx_destruct;
@property(nonatomic) __weak UIImageView *likeImageView; // @synthesize likeImageView=_likeImageView;
- (void)updateNofiyCenterCellWithViewModel:(id)arg1 width:(double)arg2;
- (void)prepareForReuse;
- (void)setUpViewLayout;
- (void)setUpUI;

@end

