//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSMutableArray, NSMutableDictionary, NSString;
@protocol WCFinderFriendsAlsoFollowViewModelDelegate;

@interface WCFinderFriendsAlsoFollowViewModel : NSObject
{
    _Bool _hasMoreData;
    id <WCFinderFriendsAlsoFollowViewModelDelegate> _delegate;
    long long _scene;
    long long _firstPageCount;
    NSString *_username;
    NSString *_fromUsername;
    unsigned long long _commentScene;
    NSMutableArray *_dataInfos;
    NSData *_lastBuf;
    NSMutableDictionary *_pendingFollowStateMap;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableDictionary *pendingFollowStateMap; // @synthesize pendingFollowStateMap=_pendingFollowStateMap;
@property(nonatomic) _Bool hasMoreData; // @synthesize hasMoreData=_hasMoreData;
@property(retain, nonatomic) NSData *lastBuf; // @synthesize lastBuf=_lastBuf;
@property(retain, nonatomic) NSMutableArray *dataInfos; // @synthesize dataInfos=_dataInfos;
@property(nonatomic) unsigned long long commentScene; // @synthesize commentScene=_commentScene;
@property(retain, nonatomic) NSString *fromUsername; // @synthesize fromUsername=_fromUsername;
@property(copy, nonatomic) NSString *username; // @synthesize username=_username;
@property(nonatomic) long long firstPageCount; // @synthesize firstPageCount=_firstPageCount;
@property(nonatomic) long long scene; // @synthesize scene=_scene;
@property(nonatomic) __weak id <WCFinderFriendsAlsoFollowViewModelDelegate> delegate; // @synthesize delegate=_delegate;
- (unsigned long long)feedViewControllerScene;
- (void)changeContactState:(id)arg1;
- (void)onFinderContactFollowStatusUpdateFailure:(id)arg1;
- (void)onFinderContactFollowStatusUpdate:(id)arg1;
- (unsigned long long)dataCount;
- (long long)indexOfContact:(id)arg1;
- (id)dataAtIndex:(unsigned long long)arg1;
- (void)cleanPendingFollowState:(unsigned long long)arg1 username:(id)arg2;
- (void)followContactAtIndex:(unsigned long long)arg1 followAction:(unsigned long long)arg2;
- (void)fetchDataWithCompletion:(CDUnknownBlockType)arg1 isFirstPage:(_Bool)arg2;
- (void)refretchDataWithCompletion:(CDUnknownBlockType)arg1;
- (void)fetchDataWithCompletion:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (id)initWithUsername:(id)arg1 scene:(long long)arg2 fromUsername:(id)arg3 commentScene:(unsigned long long)arg4;

@end

