//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WCFinderJSApiPreloadFeedItem : NSObject
{
    NSString *_encryptId;
    NSString *_nonceId;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *nonceId; // @synthesize nonceId=_nonceId;
@property(retain, nonatomic) NSString *encryptId; // @synthesize encryptId=_encryptId;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;

@end

