//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMScrollActionSheet.h"

@class MMFinderLiveReplayTask;

@interface WCFinderLiveReplayActionSheet : MMScrollActionSheet
{
    MMFinderLiveReplayTask *_replayLiveTask;
}

- (void).cxx_destruct;
@property(retain, nonatomic) MMFinderLiveReplayTask *replayLiveTask; // @synthesize replayLiveTask=_replayLiveTask;
- (id)seperatorBackgroundColor;
- (id)containerViewBlurBackgroundColor;
- (id)cancelButtonBackgroundColor;
- (id)cancelButtonTitleColor;
- (id)titleLabelColor;
- (id)bottomPadddingViewBackgroundColor;
- (id)transparentViewBackgroundColor;
- (_Bool)isConcertTicket;
- (id)loadItemArray;
- (void)loadData;
- (id)initWithLiveTask:(id)arg1;

@end

