//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class MMUIButton, MMUILabel, UIColor;

@interface WCFinderLiveNoticePayActionView : UIView
{
    UIColor *_contentColor;
    MMUIButton *_coinButton;
    MMUILabel *_payLabel;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) MMUILabel *payLabel; // @synthesize payLabel=_payLabel;
@property(readonly, nonatomic) MMUIButton *coinButton; // @synthesize coinButton=_coinButton;
@property(retain, nonatomic) UIColor *contentColor; // @synthesize contentColor=_contentColor;
- (void)layoutSubviews;
- (void)sizeToFit;
- (id)initWithFrame:(struct CGRect)arg1;

@end

