//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WCFinderMPVideoInteractionInfo : NSObject
{
    _Bool _isLike;
    _Bool _isFav;
    NSString *_feedKey;
    unsigned long long _likeCount;
    unsigned long long _favCount;
}

+ (id)interactionInfoWithDataItem:(id)arg1;
- (void).cxx_destruct;
@property(nonatomic) unsigned long long favCount; // @synthesize favCount=_favCount;
@property(nonatomic) _Bool isFav; // @synthesize isFav=_isFav;
@property(nonatomic) unsigned long long likeCount; // @synthesize likeCount=_likeCount;
@property(nonatomic) _Bool isLike; // @synthesize isLike=_isLike;
@property(retain, nonatomic) NSString *feedKey; // @synthesize feedKey=_feedKey;

@end

