//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIImageView, UILabel, UIView, WCFinderHeadImageView;

@interface WCFinderAccountSelectedInWXTableViewCell : UITableViewCell
{
    WCFinderHeadImageView *_avatarImageView;
    UILabel *_titleLabel;
    UILabel *_fansLabel;
    UIImageView *_selectedView;
    UIView *_addIconView;
    UIImageView *_addIconImageView;
    UIView *_selectBGView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIView *selectBGView; // @synthesize selectBGView=_selectBGView;
@property(retain, nonatomic) UIImageView *addIconImageView; // @synthesize addIconImageView=_addIconImageView;
@property(retain, nonatomic) UIView *addIconView; // @synthesize addIconView=_addIconView;
@property(retain, nonatomic) UIImageView *selectedView; // @synthesize selectedView=_selectedView;
@property(retain, nonatomic) UILabel *fansLabel; // @synthesize fansLabel=_fansLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) WCFinderHeadImageView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)layoutSubviews;
- (void)updateWithContact:(id)arg1 fansCount:(unsigned long long)arg2 isSelected:(_Bool)arg3;
- (void)prepareForReuse;
- (void)setUpUI;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

