//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface WCFinderPostHelperParams : NSObject
{
    unsigned int _profileEnterType;
    unsigned long long _enterScene;
    unsigned long long _createFrom;
    unsigned long long _createScene;
}

+ (id)paramsWithEnterScene:(unsigned long long)arg1 createFrom:(unsigned long long)arg2 createScene:(unsigned long long)arg3;
@property(nonatomic) unsigned int profileEnterType; // @synthesize profileEnterType=_profileEnterType;
@property(nonatomic) unsigned long long createScene; // @synthesize createScene=_createScene;
@property(nonatomic) unsigned long long createFrom; // @synthesize createFrom=_createFrom;
@property(nonatomic) unsigned long long enterScene; // @synthesize enterScene=_enterScene;

@end

