//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSMutableArray, NSString, WCFinderCustomCGI;

@interface WCFinderInteractiveSearchStore : NSObject
{
    NSString *_lastKeyword;
    NSMutableArray *_dataItems;
    NSData *_lastBuff;
    unsigned long long _loadState;
    WCFinderCustomCGI *_lastCGI;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WCFinderCustomCGI *lastCGI; // @synthesize lastCGI=_lastCGI;
@property(nonatomic) unsigned long long loadState; // @synthesize loadState=_loadState;
@property(retain, nonatomic) NSData *lastBuff; // @synthesize lastBuff=_lastBuff;
@property(retain, nonatomic) NSMutableArray *dataItems; // @synthesize dataItems=_dataItems;
@property(retain, nonatomic) NSString *lastKeyword; // @synthesize lastKeyword=_lastKeyword;
- (void)requestNextPage:(CDUnknownBlockType)arg1 commentScene:(unsigned long long)arg2;
- (void)search:(id)arg1 firstPage:(_Bool)arg2 commentScene:(unsigned long long)arg3 complete:(CDUnknownBlockType)arg4;
- (void)search:(id)arg1 commentScene:(unsigned long long)arg2 complete:(CDUnknownBlockType)arg3;
- (id)init;
- (void)dealloc;

@end

