//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIView.h"

@class NSString, UIImageView, UILabel;

@interface WCFinderRecommendBubbleView : MMUIView
{
    UIImageView *_leftImageView;
    UILabel *_recommendTipsLabel;
    UILabel *_nextTipsLabel;
    double _maxWidth;
    NSString *_railTips;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *railTips; // @synthesize railTips=_railTips;
@property(nonatomic) double maxWidth; // @synthesize maxWidth=_maxWidth;
@property(retain, nonatomic) UILabel *nextTipsLabel; // @synthesize nextTipsLabel=_nextTipsLabel;
@property(retain, nonatomic) UILabel *recommendTipsLabel; // @synthesize recommendTipsLabel=_recommendTipsLabel;
@property(retain, nonatomic) UIImageView *leftImageView; // @synthesize leftImageView=_leftImageView;
- (void)layoutAllSubviews;
- (void)updateWithLeftIcon:(id)arg1 recommendTips:(id)arg2 nextTips:(id)arg3 nextBlock:(CDUnknownBlockType)arg4;
- (id)initWithFrame:(struct CGRect)arg1 maxWidth:(double)arg2 railTips:(id)arg3;

@end

