//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WCFinderExternalCommentModel : NSObject
{
    NSString *_postContent;
    long long _sourceScene;
}

- (void).cxx_destruct;
@property(nonatomic) long long sourceScene; // @synthesize sourceScene=_sourceScene;
@property(copy, nonatomic) NSString *postContent; // @synthesize postContent=_postContent;
- (_Bool)isValid;
- (id)initWithPostContent:(id)arg1 sourceScene:(long long)arg2;

@end

