//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIButton.h"

@class NSNumber, UIView, WCFinderTabSwitchCustomViewInfo;

@interface WCFinderTabSwitchViewButton : MMUIButton
{
    long long _index;
    NSNumber *_uniqueId;
    double _titleFontSize;
    UIView *_customView;
    WCFinderTabSwitchCustomViewInfo *_customViewInfo;
    CDUnknownBlockType _customLayout;
    struct CGSize _expandSize;
}

- (void).cxx_destruct;
@property(nonatomic) struct CGSize expandSize; // @synthesize expandSize=_expandSize;
@property(copy, nonatomic) CDUnknownBlockType customLayout; // @synthesize customLayout=_customLayout;
@property(retain, nonatomic) WCFinderTabSwitchCustomViewInfo *customViewInfo; // @synthesize customViewInfo=_customViewInfo;
@property(retain, nonatomic) UIView *customView; // @synthesize customView=_customView;
@property(nonatomic) double titleFontSize; // @synthesize titleFontSize=_titleFontSize;
@property(retain, nonatomic) NSNumber *uniqueId; // @synthesize uniqueId=_uniqueId;
@property(nonatomic) long long index; // @synthesize index=_index;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)layoutSubviews;
- (void)prepareForReuse;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)setSelected:(_Bool)arg1;

@end

