//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUserService.h"

#import "MMServiceProtocol-Protocol.h"

@class NSString;

@interface WCKeyboardMgr : MMUserService <MMServiceProtocol>
{
    _Bool _externalKeyboardConnected;
    _Bool _receiveNotification;
}

@property(nonatomic) _Bool receiveNotification; // @synthesize receiveNotification=_receiveNotification;
@property(nonatomic) _Bool externalKeyboardConnected; // @synthesize externalKeyboardConnected=_externalKeyboardConnected;
- (void)externalKeyboardDisconnect:(id)arg1;
- (void)externalKeyboardConnect:(id)arg1;
- (_Bool)isExternalKeyboardConnected;
- (void)onServiceClearData;
- (void)onServiceInit;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

