//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WCMomentsCompositorTabCellViewModel : NSObject
{
    _Bool _isSelected;
    NSString *_sectionId;
    NSString *_sectionTitle;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool isSelected; // @synthesize isSelected=_isSelected;
@property(copy, nonatomic) NSString *sectionTitle; // @synthesize sectionTitle=_sectionTitle;
@property(copy, nonatomic) NSString *sectionId; // @synthesize sectionId=_sectionId;
- (id)initWithSectionId:(id)arg1 sectionTitle:(id)arg2;

@end

