//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class ApplyNFCCardResponse, NSString, WCPayIssueNFCCardCgi;

@protocol WCPayIssueNFCCardCgiDelegate <NSObject>
- (void)onWCPayIssueNFCCardCgiResponseError:(WCPayIssueNFCCardCgi *)arg1 errorMsg:(NSString *)arg2 errorCode:(unsigned int)arg3;
- (void)onWCPayIssueNFCCardCgiResponseOK:(WCPayIssueNFCCardCgi *)arg1 result:(ApplyNFCCardResponse *)arg2;
@end

