//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "PBCoding-Protocol.h"

@class NSString;

@interface WCPayOfflinePayCardItem : NSObject <PBCoding>
{
    NSString *_bankType;
    NSString *_bindSerial;
    long long _cardId;
    NSString *_forbidWord;
}

+ (void)initialize;
+ (void)PBArrayAdd_forbidWord;
+ (void)PBArrayAdd_cardId;
+ (void)PBArrayAdd_bindSerial;
+ (void)PBArrayAdd_bankType;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *forbidWord; // @synthesize forbidWord=_forbidWord;
@property(nonatomic) long long cardId; // @synthesize cardId=_cardId;
@property(retain, nonatomic) NSString *bindSerial; // @synthesize bindSerial=_bindSerial;
@property(retain, nonatomic) NSString *bankType; // @synthesize bankType=_bankType;
- (id)getPBPropertyTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

