//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCAccountBaseViewController.h"

@class MMUIActivityIndicatorView, UIButton, UIImageView, UILabel;

@interface WCPlayLiveWithoutLoginQRCodeViewController : WCAccountBaseViewController
{
    CDUnknownBlockType _cancelCompletion;
    CDUnknownBlockType _didAppearCompletion;
    CDUnknownBlockType _refreshQrcodeCompletion;
    UIImageView *_qrCodeImgView;
    UILabel *_descriptionLabel;
    MMUIActivityIndicatorView *_loadingView;
    UIButton *_refreshButton;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIButton *refreshButton; // @synthesize refreshButton=_refreshButton;
@property(retain, nonatomic) MMUIActivityIndicatorView *loadingView; // @synthesize loadingView=_loadingView;
@property(retain, nonatomic) UILabel *descriptionLabel; // @synthesize descriptionLabel=_descriptionLabel;
@property(retain, nonatomic) UIImageView *qrCodeImgView; // @synthesize qrCodeImgView=_qrCodeImgView;
@property(copy, nonatomic) CDUnknownBlockType refreshQrcodeCompletion; // @synthesize refreshQrcodeCompletion=_refreshQrcodeCompletion;
@property(copy, nonatomic) CDUnknownBlockType didAppearCompletion; // @synthesize didAppearCompletion=_didAppearCompletion;
@property(copy, nonatomic) CDUnknownBlockType cancelCompletion; // @synthesize cancelCompletion=_cancelCompletion;
- (void)willEnterForeground;
- (void)showRefreshView;
- (void)cleanQrcode;
- (void)stopLoadingView;
- (void)showLoadingView;
- (void)onRefreshBtnClicked:(id)arg1;
- (void)onCancel;
- (void)updateQRCode:(id)arg1;
- (void)layoutUI;
- (void)viewDidTransitionToNewSize;
- (void)viewDidAppear:(_Bool)arg1;
- (_Bool)useTableView;
- (_Bool)useSheetView;
- (void)viewDidLoad;
- (void)dealloc;

@end

