//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class MMTagTextField, MMUILabel, NSString, UIBarButtonItem, UIButton, UIColor, UIImage, UIImageView, UILabel, UIStackView, WCSearchViewController;

@interface WCSearchBar : UIView
{
    UIBarButtonItem *_leftBarButtonItem;
    UIBarButtonItem *_rightBarButtonItem;
    unsigned long long _clearButtonMode;
    WCSearchViewController *_presentingViewController;
    MMUILabel *_titleLabel;
    UIColor *_searchBoxContainerColor;
    UIView *_bottomLineView;
    MMTagTextField *_textField;
    UIButton *_clearButton;
    UIView *_searchBoxContainer;
    UIStackView *_rootStackView;
    UIStackView *_searchBox;
    UIImageView *_leftIconView;
    UILabel *_placeHolderLabel;
    CDUnknownBlockType _tapHandler;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType tapHandler; // @synthesize tapHandler=_tapHandler;
@property(retain, nonatomic) UILabel *placeHolderLabel; // @synthesize placeHolderLabel=_placeHolderLabel;
@property(retain, nonatomic) UIImageView *leftIconView; // @synthesize leftIconView=_leftIconView;
@property(retain, nonatomic) UIStackView *searchBox; // @synthesize searchBox=_searchBox;
@property(retain, nonatomic) UIStackView *rootStackView; // @synthesize rootStackView=_rootStackView;
@property(retain, nonatomic) UIView *searchBoxContainer; // @synthesize searchBoxContainer=_searchBoxContainer;
@property(retain, nonatomic) UIButton *clearButton; // @synthesize clearButton=_clearButton;
@property(retain, nonatomic) MMTagTextField *textField; // @synthesize textField=_textField;
@property(retain, nonatomic) UIView *bottomLineView; // @synthesize bottomLineView=_bottomLineView;
@property(retain, nonatomic) UIColor *searchBoxContainerColor; // @synthesize searchBoxContainerColor=_searchBoxContainerColor;
@property(retain, nonatomic) MMUILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak WCSearchViewController *presentingViewController; // @synthesize presentingViewController=_presentingViewController;
@property(nonatomic) unsigned long long clearButtonMode; // @synthesize clearButtonMode=_clearButtonMode;
@property(retain, nonatomic) UIBarButtonItem *rightBarButtonItem; // @synthesize rightBarButtonItem=_rightBarButtonItem;
@property(retain, nonatomic) UIBarButtonItem *leftBarButtonItem; // @synthesize leftBarButtonItem=_leftBarButtonItem;
- (void)setPresentSearchActive:(_Bool)arg1;
- (void)addTapSearchAction:(CDUnknownBlockType)arg1;
- (void)makeConstraintsForBarButton:(id)arg1;
- (void)showsCancelButton:(_Bool)arg1 animated:(_Bool)arg2;
@property(retain, nonatomic) UIImage *leftIconImage;
@property(nonatomic) _Bool isShowSearchBoxBorder;
@property(copy, nonatomic) NSString *placeholder;
- (void)showTextField;
- (void)showTitle:(id)arg1;
- (void)onTextFieldEditingDidEnd:(id)arg1;
- (void)onTextFieldEditingDidBegin:(id)arg1;
- (void)onTextFieldChanged:(id)arg1;
@property(nonatomic) _Bool showBottomLine;
- (void)arrangeBaseUIElements;
- (void)initContanerView;
- (void)setUnactiveStyle;
- (id)initWithFrame:(struct CGRect)arg1;

@end

