//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUINavigationController.h"

@interface WCSplitDetailNavigationController : MMUINavigationController
{
    _Bool _isPresented;
    _Bool _isViewDisappear;
    _Bool _isSizeChanged;
    struct CGSize _lastViewSize;
}

@property(nonatomic) _Bool isSizeChanged; // @synthesize isSizeChanged=_isSizeChanged;
@property(nonatomic) struct CGSize lastViewSize; // @synthesize lastViewSize=_lastViewSize;
@property(nonatomic) _Bool isViewDisappear; // @synthesize isViewDisappear=_isViewDisappear;
@property(nonatomic) _Bool isPresented; // @synthesize isPresented=_isPresented;
- (void)viewDidLayoutSubviews;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (_Bool)isBeingPresented;
- (id)initWithRootViewController:(id)arg1 isBeingPresent:(_Bool)arg2;

@end

