//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCTogetherBaseFeedCell.h"

@class RichTextView;

@interface WCTogetherTextFeedCell : WCTogetherBaseFeedCell
{
    RichTextView *_richTextView;
}

+ (double)heightForItemContentViewWithViewItem:(id)arg1 inTableView:(id)arg2;
+ (id)createRichTextView;
+ (id)cellIdentifier;
- (void).cxx_destruct;
@property(retain, nonatomic) RichTextView *richTextView; // @synthesize richTextView=_richTextView;
- (void)contentDidTap;
- (void)layoutItemContentView;
- (void)loadItemContentView;
- (void)updateValueForKeyPath:(id)arg1;
- (id)observingKeyPathsForViewModel;

@end

