//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCTogetherReusableView.h"

@class UILabel, WCTogetherFeedViewSection;

@interface WCTogetherFeedHeaderView : WCTogetherReusableView
{
    UILabel *_yearTextLabel;
    UILabel *_dayTextLabel;
}

+ (double)heightForViewSection:(id)arg1 inTableView:(id)arg2;
+ (id)reusableViewIdentifier;
- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *dayTextLabel; // @synthesize dayTextLabel=_dayTextLabel;
@property(retain, nonatomic) UILabel *yearTextLabel; // @synthesize yearTextLabel=_yearTextLabel;
- (void)layoutSubviews;
- (id)initWithReuseIdentifier:(id)arg1;
- (void)updateValueForKeyPath:(id)arg1;
- (id)observingKeyPathsForViewModel;

// Remaining properties
@property(retain, nonatomic) WCTogetherFeedViewSection *viewSection; // @dynamic viewSection;

@end

