//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "MJTemplateSessionDelegate-Protocol.h"
#import "WCVideoProducerFlavorsDelegate-Protocol.h"

@class MJTemplateSession, MJVideoTemplate, NSArray, NSString, OMJMusicInfo, OMJTemplateInfo, UIImage, UIView, WCMomentsPostReportSession, WCVideoProducerActionRecorder, WCVideoProducerDataManager, WCVideoProducerFlavors, WCVideoProducerOptions;
@protocol WCVideoProducerViewModelDelegate;

@interface WCVideoProducerViewModel : NSObject <WCVideoProducerFlavorsDelegate, MJTemplateSessionDelegate>
{
    CDUnknownBlockType _templateComparatorBlock;
    UIImage *_firstAssetThumbImage;
    _Bool _isStartingPlayingVideo;
    _Bool _isStoppingPlayingVideo;
    WCVideoProducerOptions *_options;
    WCMomentsPostReportSession *_postReportSession;
    id <WCVideoProducerViewModelDelegate> _delegate;
    WCVideoProducerDataManager *_dataManager;
    WCVideoProducerFlavors *_flavors;
    MJTemplateSession *_sessionAssistant;
    MJVideoTemplate *_changingTemplate;
    OMJMusicInfo *_changingMusic;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool isStoppingPlayingVideo; // @synthesize isStoppingPlayingVideo=_isStoppingPlayingVideo;
@property(nonatomic) _Bool isStartingPlayingVideo; // @synthesize isStartingPlayingVideo=_isStartingPlayingVideo;
@property(retain, nonatomic) OMJMusicInfo *changingMusic; // @synthesize changingMusic=_changingMusic;
@property(retain, nonatomic) MJVideoTemplate *changingTemplate; // @synthesize changingTemplate=_changingTemplate;
@property(retain, nonatomic) MJTemplateSession *sessionAssistant; // @synthesize sessionAssistant=_sessionAssistant;
@property(retain, nonatomic) WCVideoProducerFlavors *flavors; // @synthesize flavors=_flavors;
@property(retain, nonatomic) WCVideoProducerDataManager *dataManager; // @synthesize dataManager=_dataManager;
@property(nonatomic) __weak id <WCVideoProducerViewModelDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) WCMomentsPostReportSession *postReportSession; // @synthesize postReportSession=_postReportSession;
@property(retain, nonatomic) WCVideoProducerOptions *options; // @synthesize options=_options;
- (id)_maasSession;
@property(readonly, nonatomic) CDStruct_1b6d18a9 renderingVideoDuration;
@property(readonly, nonatomic) OMJMusicInfo *renderingMusicInfo;
@property(readonly, nonatomic) OMJTemplateInfo *renderingTemplateInfo;
@property(readonly, nonatomic) UIView *previewRenderView;
@property(readonly, nonatomic) double previewRenderRatio;
@property(readonly, nonatomic) UIImage *previewThumbImage;
@property(readonly, nonatomic) NSArray *inputAssetIdList;
@property(readonly, nonatomic) NSArray *inputAssetInfoList;
@property(readonly, nonatomic) WCVideoProducerActionRecorder *actionRecorder;
@property(readonly, nonatomic) NSString *sessionKey;
- (_Bool)templateSessionCanContinueStartUpCore;
- (void)onAudioModuleAbilityChanged:(_Bool)arg1;
- (void)_onMusicBarVCShowed;
- (void)_preloadMusicsStartWithId:(id)arg1;
- (void)_preloadTemplatesStartWithId:(id)arg1;
- (void)_applyMovieOptions;
- (void)_prepareMovieOptions:(id)arg1 forTemplateWithId:(id)arg2;
- (id)_generatePreviewOptionsForTemplateWithId:(id)arg1;
- (id)_generateExportOptions;
- (CDStruct_e83c9415)_generateTimeRangeForExporting;
- (CDStruct_e83c9415)_generateTimeRangeForPlaying;
- (id)_getRecommendSceneStr;
- (void)insertUniqueSearchMusic:(id)arg1 atIndex:(unsigned long long)arg2;
- (_Bool)removeExtRecommendTemplateById:(id)arg1;
- (void)removeAllStubTemplates;
- (void)addPickOutTemplate:(id)arg1;
- (void)loadMoreRecommendTemplatesWithCompletionBlock:(CDUnknownBlockType)arg1;
- (id)findTemplateById:(id)arg1;
- (id)assembleAllProvidedTemplateList;
- (id)findAssetInfoByLocalIdentifier:(id)arg1;
- (id)getSearchMusicList;
- (id)getRecommendMusicList;
- (id)getPickOutTemplateList;
- (id)getExtRecommendTemplateList;
- (id)getRecommendTemplateList;
- (id)getFolderTemplateList;
- (id)getLauncherTemplateList;
- (id)getStubTemplateList;
- (id)getCreateSameTemplateList;
- (id)getDefaultTemplateList;
- (void)updateVideoProducerFlavorsToEnableExternalPlayback:(_Bool)arg1;
- (void)updateVideoProducerFlavorsToEnablePreviewBGM:(_Bool)arg1;
- (void)updateVideoProducerFlavorsToEnablePreviewOST:(_Bool)arg1;
- (void)updateVideoProducerFlavorsToMuteAllPreview:(_Bool)arg1;
- (void)updateVideoProducerFlavorsToEnableAudioModule:(_Bool)arg1;
- (void)updatePreloadConfigs:(id)arg1;
- (void)updateVideoProducerOptionsToEnableOST:(_Bool)arg1 enableBGM:(_Bool)arg2 enableLyrics:(_Bool)arg3;
- (void)cleanUpWithCompletionBlock:(CDUnknownBlockType)arg1;
- (void)startExportingWithProgressBlock:(CDUnknownBlockType)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (id)seekAssetSegmentWithId:(id)arg1 toTimeInClip:(CDStruct_1b6d18a9)arg2;
- (_Bool)canSeekAssetSegment;
- (id)getAllAssetClipSegment;
- (void)stopAssetClippingWithCompletionBlock:(CDUnknownBlockType)arg1;
- (void)startAssetClippingWithCompletionBlock:(CDUnknownBlockType)arg1;
- (_Bool)isChangingMusic:(id)arg1;
- (void)changeMusicInfo:(id)arg1 progressBlock:(CDUnknownBlockType)arg2 completion:(CDUnknownBlockType)arg3;
- (_Bool)isChangingTemplate:(id)arg1;
- (void)changeTemplateWithTemplate:(id)arg1 progressBlock:(CDUnknownBlockType)arg2 completion:(CDUnknownBlockType)arg3;
- (_Bool)isPlayingVideo;
- (void)stopPlayWithCompletionBlock:(CDUnknownBlockType)arg1;
- (void)startPlayingSegmentWithId:(id)arg1 forTimeRange:(CDStruct_e83c9415)arg2 completion:(CDUnknownBlockType)arg3;
- (void)startPlayWithCompletionBlock:(CDUnknownBlockType)arg1;
- (void)createVideoWithCompleteBlock:(CDUnknownBlockType)arg1 updateBlock:(CDUnknownBlockType)arg2 progressBlock:(CDUnknownBlockType)arg3;
- (void)prepareWithStartupBlock:(CDUnknownBlockType)arg1;
- (void)filterLocalResourceWithCompleteBlock:(CDUnknownBlockType)arg1;
- (void)_initData;
- (void)dealloc;
- (id)initWithAssetInfoList:(id)arg1 options:(id)arg2 postReportSession:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

