//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WXGRoamDownloadSessionInfo : NSObject
{
    NSString *_userName;
    unsigned long long _sessionSize;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned long long sessionSize; // @synthesize sessionSize=_sessionSize;
@property(copy, nonatomic) NSString *userName; // @synthesize userName=_userName;

@end

