//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImageView.h>

#import "YYImageDelegate-Protocol.h"

@class NSString, YYImage;

@interface YYAsyncImageView : UIImageView <YYImageDelegate>
{
    YYImage *m_image;
    YYImage *m_highlightedImage;
    YYImage *m_defaultImage;
    _Bool m_highlighted;
    _Bool _didSetDarkModeObserver;
}

+ (Class)layerClass;
- (void).cxx_destruct;
@property(nonatomic) _Bool didSetDarkModeObserver; // @synthesize didSetDarkModeObserver=_didSetDarkModeObserver;
- (void)didSetDynamicYYImage;
- (long long)overrideStyle;
- (void)willMoveToWindow:(id)arg1;
- (id)newAsyncDisplayTask;
- (void)resetAllImage;
- (void)setDefaultImage:(id)arg1;
- (void)setHighlighted:(_Bool)arg1;
- (void)setHighlightedImage:(id)arg1;
- (void)setImage:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

